# Shallow LSTM Benchmark with Optuna & Symlog

In [13]:
!pip install optuna

Requirement already satisfied: optuna in /usr/local/lib/python3.12/dist-packages (4.9.0)
Requirement already satisfied: alembic>=1.5.0 in /usr/local/lib/python3.12/dist-packages (from optuna) (1.18.4)
Requirement already satisfied: colorlog in /usr/local/lib/python3.12/dist-packages (from optuna) (6.10.1)
Requirement already satisfied: numpy in /usr/local/lib/python3.12/dist-packages (from optuna) (2.0.2)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from optuna) (26.2)
Requirement already satisfied: sqlalchemy>=1.4.2 in /usr/local/lib/python3.12/dist-packages (from optuna) (2.0.50)
Requirement already satisfied: tqdm in /usr/local/lib/python3.12/dist-packages (from optuna) (4.67.3)
Requirement already satisfied: PyYAML in /usr/local/lib/python3.12/dist-packages (from optuna) (6.0.3)
Requirement already satisfied: Mako in /usr/local/lib/python3.12/dist-packages (from alembic>=1.5.0->optuna) (1.3.12)
Requirement already satisfied: typing-extensions>=4.12 in /usr/local/lib/python3.12/dist-packages (from alembic>=1.5.0->optuna) (4.15.0)
Requirement already satisfied: greenlet>=1 in /usr/local/lib/python3.12/dist-packages (from sqlalchemy>=1.4.2->optuna) (3.5.1)
Requirement already satisfied: MarkupSafe>=0.9.2 in /usr/local/lib/python3.12/dist-packages (from Mako->alembic>=1.5.0->optuna) (3.0.3)

In [14]:
from pathlib import Path
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import torch
import torch.nn as nn
from sklearn.preprocessing import StandardScaler, RobustScaler
from torch.utils.data import DataLoader, Dataset
from torch.nn.utils.rnn import pack_padded_sequence
from torch.optim.lr_scheduler import ReduceLROnPlateau
import optuna

SEED = 42
DATA_PATH = Path("Merged_Dataset_yoy.csv")
PREDICTION_TARGETS = ["EBITDA", "Net_Income", "ROA"]
DEFAULT_LOOKBACK_DAYS = 365

MAX_EPOCHS = 100
PATIENCE = 10
TRAIN_YEAR_CUTOFF = 2019
VALID_YEAR_CUTOFF = 2021
OPTUNA_TRIALS = 100

np.random.seed(SEED)
torch.manual_seed(SEED)
torch.set_num_threads(max(1, torch.get_num_threads() // 2))
DEVICE = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print(f"Using device: {DEVICE}")

Using device: cuda

## Data Processing (Baseline)

In [15]:
def load_and_prepare_yoy_data(data_path: Path, lookback_days: int = 365):
    try:
        df = pd.read_csv(data_path)
    except FileNotFoundError:
        df = pd.read_csv("Merged_Dataset_yoy.csv")

    df["Date"] = pd.to_datetime(df["Date"])
    df = df.sort_values(["Company", "Date"]).reset_index(drop=True)
    df["year"] = df["Date"].dt.year

    df["has_targets"] = df[PREDICTION_TARGETS].notna().any(axis=1)
    year_end_records = df[df["has_targets"]].copy()
    exclude_cols = {"Date", "Company", "year", "has_targets"} | set(PREDICTION_TARGETS)
    feature_cols = [col for col in df.columns if col not in exclude_cols and pd.api.types.is_numeric_dtype(df[col])]

    sequences = []
    for company in df["Company"].unique():
        company_records = year_end_records[year_end_records["Company"] == company].copy()
        company_data = df[df["Company"] == company].copy()

        for _, year_end_row in company_records.iterrows():
            year = int(year_end_row["year"])
            year_end_date = year_end_row["Date"]

            prior_year_records = year_end_records[
                (year_end_records["Company"] == company) & (year_end_records["year"] == year - 1)
            ]
            if prior_year_records.empty:
                continue

            prior_row = prior_year_records.iloc[0]
            window_start = year_end_date - pd.Timedelta(days=lookback_days)
            window = company_data[(company_data["Date"] > window_start) & (company_data["Date"] <= year_end_date)].copy()

            if len(window) < 200:
                continue

            window[feature_cols] = window[feature_cols].ffill().bfill()
            if window[feature_cols].isna().any().any():
                continue

            sequences.append({
                "company": company, "year": year, "year_end_date": year_end_date,
                "window_data": window[feature_cols].to_numpy(dtype=np.float32),
                **{f"current_{t.lower()}": year_end_row[t] for t in PREDICTION_TARGETS},
                **{f"prior_{t.lower()}": prior_row[t] for t in PREDICTION_TARGETS},
            })

    data_records = []
    for seq in sequences:
        for target_name in PREDICTION_TARGETS:
            current_val = seq[f"current_{target_name.lower()}"]
            prior_val = seq[f"prior_{target_name.lower()}"]
            if pd.isna(current_val) or pd.isna(prior_val):
                continue

            label_value = (current_val - prior_val) / (np.abs(prior_val) + 1e-8)

            data_records.append({
                "company": seq["company"], "year": seq["year"], "year_end_date": seq["year_end_date"],
                "target": target_name, "label_value": label_value,
                "window_data": seq["window_data"]
            })

    return pd.DataFrame(data_records), feature_cols

data_df, feature_cols = load_and_prepare_yoy_data(DATA_PATH, lookback_days=DEFAULT_LOOKBACK_DAYS)

def split_by_year(data_df: pd.DataFrame, train_cutoff: int, valid_cutoff: int):
    train_data = data_df[data_df["year"] <= train_cutoff].copy()
    val_data = data_df[(data_df["year"] > train_cutoff) & (data_df["year"] <= valid_cutoff)].copy()
    test_data = data_df[data_df["year"] > valid_cutoff].copy()
    return train_data, val_data, test_data

train_data, val_data, test_data = split_by_year(data_df, TRAIN_YEAR_CUTOFF, VALID_YEAR_CUTOFF)

scaler = StandardScaler()
train_windows = np.vstack([row for row in train_data["window_data"]])
scaler.fit(train_windows)

max_seq_length = max(len(row) for row in data_df["window_data"])

## Enhanced Pipeline Setup (Symlog, RobustScaler, Packing)

In [16]:
SELECTED_FEATURES = feature_cols.copy() # Can apply feature selection here
selected_indices = [feature_cols.index(f) for f in SELECTED_FEATURES]

improved_data_df = data_df.copy()

# SYMLOG TRANSFORMATION instead of Winsorization
idx_value = improved_data_df["target"].isin(PREDICTION_TARGETS)
y_val = improved_data_df.loc[idx_value, "label_value"]
improved_data_df.loc[idx_value, "label_value"] = np.sign(y_val) * np.log1p(np.abs(y_val))

train_data_imp, val_data_imp, test_data_imp = split_by_year(improved_data_df, TRAIN_YEAR_CUTOFF, VALID_YEAR_CUTOFF)

robust_scaler = RobustScaler()
train_windows_imp = np.vstack([row[:, selected_indices] for row in train_data_imp["window_data"]])
robust_scaler.fit(train_windows_imp)

def collate_fn_improved(batch):
    batch.sort(key=lambda x: x[2], reverse=True)
    sequences = [x[0] for x in batch]
    targets = torch.stack([x[1] for x in batch])
    lengths = torch.tensor([x[2] for x in batch])
    padded_seqs = torch.nn.utils.rnn.pad_sequence(sequences, batch_first=True)
    return padded_seqs, targets, lengths

## Model Definitions

In [17]:
class ShallowLSTMClassifier(nn.Module):
    def __init__(self, input_size: int, hidden_size: int, num_targets: int = 1, dropout: float = 0.2):
        super().__init__()
        self.lstm = nn.LSTM(input_size=input_size, hidden_size=hidden_size, num_layers=1, batch_first=True)
        self.dropout = nn.Dropout(p=dropout)
        self.head = nn.Linear(hidden_size, num_targets)

    def forward(self, x: torch.Tensor) -> torch.Tensor:
        lstm_out, _ = self.lstm(x)
        hidden = self.dropout(lstm_out[:, -1, :])
        logits = self.head(hidden)
        if logits.size(-1) == 1: logits = logits.squeeze(-1)
        return logits

class ImprovedShallowLSTM(nn.Module):
    def __init__(self, input_size: int, hidden_size: int, num_targets: int = 1, dropout: float = 0.2):
        super().__init__()
        self.lstm = nn.LSTM(input_size, hidden_size, num_layers=1, batch_first=True)
        self.dropout = nn.Dropout(p=dropout)
        self.head = nn.Linear(hidden_size, num_targets)

    def forward(self, x, lengths):
        packed_x = pack_padded_sequence(x, lengths.cpu(), batch_first=True, enforce_sorted=True)
        _, (hn, _) = self.lstm(packed_x)
        hidden = self.dropout(hn[-1])
        logits = self.head(hidden)
        if logits.size(-1) == 1: logits = logits.squeeze(-1)
        return logits

## Helpers for Optuna and Evaluation

In [18]:
def extract_mtl_df(df: pd.DataFrame) -> pd.DataFrame:
    mtl_records = []
    for (company, year), group in df.groupby(["company", "year"]):
        window_data = group.iloc[0]["window_data"]
        year_end_date = group.iloc[0]["year_end_date"]
        label_value = np.full(len(PREDICTION_TARGETS), np.nan, dtype=np.float32)
        for i, t in enumerate(PREDICTION_TARGETS):
            t_row = group[group["target"] == t]
            if not t_row.empty:
                label_value[i] = t_row.iloc[0]["label_value"]
        mtl_records.append({
            "company": company, "year": year, "year_end_date": year_end_date,
            "window_data": window_data, "label_value": label_value
        })
    return pd.DataFrame(mtl_records)

# Baseline MTL dfs
mtl_train_data = extract_mtl_df(train_data)
mtl_val_data = extract_mtl_df(val_data)
mtl_test_data = extract_mtl_df(test_data)

# Improved MTL dfs
mtl_train_data_imp = extract_mtl_df(train_data_imp)
mtl_val_data_imp = extract_mtl_df(val_data_imp)
mtl_test_data_imp = extract_mtl_df(test_data_imp)

class YoYSequenceDatasetMTL(Dataset):
    def __init__(self, data_df: pd.DataFrame, max_seq_length: int, scaler: StandardScaler = None):
        self.data_df = data_df.reset_index(drop=True)
        self.max_seq_length = max_seq_length
        self.scaler = scaler

    def __len__(self) -> int: return len(self.data_df)

    def __getitem__(self, idx: int):
        row = self.data_df.iloc[idx]
        window = row["window_data"].copy()
        if self.scaler is not None: window = self.scaler.transform(window)
        seq_len = len(window)
        if seq_len < self.max_seq_length:
            padding = np.zeros((self.max_seq_length - seq_len, window.shape[1]), dtype=np.float32)
            window = np.vstack([padding, window])
        target = row["label_value"]
        mask = ~np.isnan(target)
        target_clean = np.nan_to_num(target, nan=0.0)
        return torch.from_numpy(window), torch.tensor(target_clean, dtype=torch.float32), torch.tensor(mask, dtype=torch.bool)


class ImprovedYoYDatasetMTL(Dataset):
    def __init__(self, data_df, scaler, feature_indices):
        self.data_df = data_df.reset_index(drop=True)
        self.scaler = scaler
        self.feature_indices = feature_indices

    def __len__(self): return len(self.data_df)

    def __getitem__(self, idx):
        row = self.data_df.iloc[idx]
        window = row["window_data"][:, self.feature_indices].copy()
        if self.scaler: window = self.scaler.transform(window)
        target = row["label_value"]
        mask = ~np.isnan(target)
        target_clean = np.nan_to_num(target, nan=0.0)
        return torch.from_numpy(window), torch.tensor(target_clean, dtype=torch.float32), torch.tensor(mask, dtype=torch.bool), len(window)

def collate_fn_improved_mtl(batch):
    batch.sort(key=lambda x: x[3], reverse=True)
    sequences = [x[0] for x in batch]
    targets = torch.stack([x[1] for x in batch])
    masks = torch.stack([x[2] for x in batch])
    lengths = torch.tensor([x[3] for x in batch])
    padded_seqs = torch.nn.utils.rnn.pad_sequence(sequences, batch_first=True)
    return padded_seqs, targets, masks, lengths

In [19]:
def build_loaders_and_model(is_improved, params):
    dropout_val = params.get("dropout", 0.2)
    if is_improved:
        train_ds = ImprovedYoYDatasetMTL(mtl_train_data_imp, robust_scaler, selected_indices)
        val_ds = ImprovedYoYDatasetMTL(mtl_val_data_imp, robust_scaler, selected_indices)
        test_ds = ImprovedYoYDatasetMTL(mtl_test_data_imp, robust_scaler, selected_indices)
        collate = collate_fn_improved_mtl
        model = ImprovedShallowLSTM(len(selected_indices), params["hidden_size"], len(PREDICTION_TARGETS), dropout_val).to(DEVICE)
    else:
        train_ds = YoYSequenceDatasetMTL(mtl_train_data, max_seq_length, scaler)
        val_ds = YoYSequenceDatasetMTL(mtl_val_data, max_seq_length, scaler)
        test_ds = YoYSequenceDatasetMTL(mtl_test_data, max_seq_length, scaler)
        collate = None
        model = ShallowLSTMClassifier(len(feature_cols), params["hidden_size"], len(PREDICTION_TARGETS), dropout_val).to(DEVICE)

    if collate:
        train_loader = DataLoader(train_ds, batch_size=params["batch_size"], shuffle=True, collate_fn=collate)
        val_loader = DataLoader(val_ds, batch_size=params["batch_size"], shuffle=False, collate_fn=collate)
        test_loader = DataLoader(test_ds, batch_size=params["batch_size"], shuffle=False, collate_fn=collate)
    else:
        train_loader = DataLoader(train_ds, batch_size=params["batch_size"], shuffle=True)
        val_loader = DataLoader(val_ds, batch_size=params["batch_size"], shuffle=False)
        test_loader = DataLoader(test_ds, batch_size=params["batch_size"], shuffle=False)

    return model, train_loader, val_loader, test_loader


def evaluate_loader(model, loader, is_improved):
    model.eval()
    all_preds, all_targets, all_masks = [], [], []
    with torch.no_grad():
        for batch in loader:
            if is_improved:
                bx, by, bmask, lengths = batch
                logits = model(bx.to(DEVICE), lengths)
                all_masks.append(bmask.numpy())
            else:
                bx, by, bmask = batch
                logits = model(bx.to(DEVICE))
                all_masks.append(bmask.numpy())

            all_preds.append(logits.cpu().numpy())
            all_targets.append(by.numpy())

    if not all_preds:
        return None

    y_pred = np.vstack(all_preds)
    y_true = np.vstack(all_targets)

    if is_improved:
        y_pred = np.sign(y_pred) * np.expm1(np.abs(y_pred))
        y_true = np.sign(y_true) * np.expm1(np.abs(y_true))

    mask = np.vstack(all_masks)
    res = {}
    for i, t in enumerate(PREDICTION_TARGETS):
        m = mask[:, i]
        if m.sum() == 0:
            continue
        res[t] = np.mean(np.abs(y_pred[m, i] - y_true[m, i]))
    return res


def final_train_and_test(is_improved, params):
    model, train_loader, val_loader, test_loader = build_loaders_and_model(
        is_improved, params
    )

    optimizer = torch.optim.Adam(model.parameters(), lr=params["lr"], weight_decay=params["weight_decay"])
    huber_delta = params.get("huber_delta", 1.0)

    model, _ = train_and_eval(
        model, train_loader, val_loader, optimizer,
        is_improved=is_improved, huber_delta=huber_delta
    )

    return evaluate_loader(model, test_loader, is_improved=is_improved)

def set_seed(seed):
    np.random.seed(seed)
    torch.manual_seed(seed)

N_RUNS = 20
print(f"Computing Final Test Metrics using Test Sets across {N_RUNS} runs...")
final_results = []

def run_multiple_times(pipeline_name, is_improved, best_params_dict):
    if "value" not in best_params_dict:
        return
    params = best_params_dict["value"]

    target_results = {t: [] for t in PREDICTION_TARGETS}
    for run_idx in range(N_RUNS):
        set_seed(SEED + run_idx)
        res = final_train_and_test(is_improved, params)
        for target, val in res.items():
            target_results[target].append(val)

    for target in PREDICTION_TARGETS:
        avg_mae = np.mean(target_results[target])
        std_mae = np.std(target_results[target])
        final_results.append({
            "Pipeline": pipeline_name,
            "Target": target,
            "Test MAE (Mean)": avg_mae,
            "Deviation": std_mae
        })

Computing Final Test Metrics using Test Sets across 20 runs...

In [20]:
mib_tickers = [
    "A2A", "AMPLIFON", "AZIMUT", "BANCA MEDIOLANUM", "BANCA MONTE DEI PASCHI",
    "BANCA PPO.DI SONDRIO", "BANCO BPM", "BPER BANCA", "BRUNELLO CUCINELLI",
    "BUZZI", "DAVIDE CAMPARI MILANO", "DIASORIN", "ENEL", "ENI",
    "FERRARI (MIL)", "FINCANTIERI", "FINECOBANK", "GENERALI", "HERA",
    "INFRASTRUTTURE WIRELESS ITALIANE NPV", "INTESANPAOLO", "ITALGAS",
    "IVECO", "LEONARDO", "LOTTOMATICA", "MEDIOBANCA BC.FIN", "MONCLER",
    "NEXI", "POSTE ITALIANE", "PRYSMIAN", "RECORDATI INDUA.CHIMICA",
    "SAIPEM", "SNAM", "STELLANTIS", "STMICROELECTRONICS (MIL)",
    "TELECOM ITALIA", "TENARIS", "TERNA RETE ELETTRICA NAZ", "UNICREDIT",
    "UNIPOL ASSICURAZIONI"
]

mid_tickers = [
    "ACEA", "ALERION CLEAN POWER", "ANIMA", "ARISTON",
    "ARNOLDO MONDADORI EDI.", "ASCOPIAVE", "AVIO", "BANCA GENERALI",
    "BANCA IFIS", "BFF BANK", "BNC.DI DESIO E DELB.", "CALTAGIRONE",
    "CAREL", "CEMBRE", "CEMENTIR", "COMPAGNIE INDUSTRIALI RIUNITE SHS",
    "CREDITO EMILIANO", "D'AMICO INTL.SHIP.", "DANIELI", "DATALOGIC",
    "DE LONGHI", "EL EN", "ENAV", "ERG", "FERRETTI (MIL)",
    "FIERA MILANO", "FRENI BREMBO", "GVS", "INTERCOS", "INTERPUMP",
    "IREN", "ITALMOBILIARE", "JUVENTUS FOOTBALL CLUB", "LUVE", "MARIE",
    "MARR", "MFE B", "MFE-MEDIAFOREUROPE", "MOLTIPLY", "NEWPRINCES",
    "OVS", "PHARMANUTRA", "PHILOGEN", "PIRELLI & C", "RAI WAY",
    "REPLY", "RIZZOLI CRER.DLSM.GP.", "SAFILO", "SALVATORE FERRAGAMO",
    "SANLORENZO", "SESA", "SOL", "TECHNOGYM", "TECHNOPROBE", "TINEXTA",
    "WEBUILD", "WIIT", "ZIGNAGO VETRO"
]

small_tickers = [
    "ABITARE IN", "AEDES", "AEFFE", "AEROP GUGL MARCO",
    "ALTEA GREEN POWER", "ANTARES VISION", "AQUAFIL", "B&C SPEAKERS",
    "BANCA PROFILO", "BANCA SISTEMA", "BASICNET", "BASTOGI", "BEEWIZE",
    "BIESSE", "BORGOSESIA", "BRIOSCHI SVILUPPO IMMBL", "CAIRO COMMUNICATION",
    "CALEFFI", "CALTAGIRONE EDITORE", "CELLULARLINE",
    "CENTRALE DEL LATTE D'ITALIA", "CLASS EDITORI", "CSP INTERNATIONAL",
    "CY4GATE", "DIGITAL BROS", "DIGITAL VALUE", "DOVALUE", "ELICA", "EMAK",
    "ENERVIT", "EPRICE", "EQUITA", "ESPRINET", "EUROGROUP LAMINATIONS A",
    "EUROTECH", "FIDIA", "FILA", "FNM", "GABETTI PROPERTY SLTN.",
    "GAROFALO HEALTH CARE", "GAS PLUS", "GEFRAN", "GENERALFINANCE",
    "GEOX", "GPI", "GRANDI VIAGGI", "IMMOBILIARE GRDE. DTBZ. SO.DI INVM.IMMB.",
    "IMMSI", "INDEL B", "INDUSTRIE DE NORA", "IRCE", "IT WAY",
    "ITALIAN DESIGN BRAND", "ITALIAN EXHIBITION", "ITALIAN SEA",
    "LANDI RENZO", "MET EXTRA", "MONDO TV", "NEODECORTECH", "OLIDATA",
    "OPS ITALIA", "OPS RETAIL", "ORSERO", "PININFARINA", "PIQUADRO",
    "PLC", "RATTI", "REVO INSURANCE", "RISANAMENTO", "SABAF", "SECO",
    "SERI INDUSTRIAL", "SIT", "SOFTLAB", "SOGEFI", "SOMEC", "SS LAZIO",
    "SYS-DAT", "TESMEC", "TESSELLIS", "TREVI FIN INDUSTRIALE", "TRIBOO",
    "TXT E-SOLUTION", "UNIDATA", "VALSOIA", "VINCENZO ZUCCHI", "ZEST"
]

ticker_groups = {"MIB": mib_tickers, "Mid-cap": mid_tickers, "Small-cap": small_tickers}

## Core Training Logic & Optuna Integration

In [21]:
def train_and_eval(model, train_loader, val_loader, optimizer, is_improved, trial=None, loss_type='l1', huber_delta=1.0):
    if loss_type == 'l1':
        criterion = nn.L1Loss(reduction='none')
    elif loss_type == 'mse':
        criterion = nn.MSELoss(reduction='none')
    elif loss_type == 'huber':
        criterion = nn.HuberLoss(delta=huber_delta, reduction='none')
    else:
        raise ValueError(f"Unknown loss_type: {loss_type}")

    scheduler = ReduceLROnPlateau(optimizer, mode='min', patience=5, factor=0.5)

    best_state = None
    best_metric = float("inf")
    epochs_without_improvement = 0

    for epoch in range(1, MAX_EPOCHS + 1):
        model.train()
        for batch in train_loader:
            optimizer.zero_grad(set_to_none=True)
            if is_improved:
                bx, by, bmask, lengths = batch
                bx, by, bmask = bx.to(DEVICE), by.to(DEVICE), bmask.to(DEVICE)
                logits = model(bx, lengths)
                loss_m = criterion(logits, by)
                loss = loss_m[bmask].mean() if loss_m[bmask].numel() > 0 else 0*loss_m.sum()
            else:
                bx, by, bmask = batch
                bx, by, bmask = bx.to(DEVICE), by.to(DEVICE), bmask.to(DEVICE)
                logits = model(bx)
                loss_m = criterion(logits, by)
                loss = loss_m[bmask].mean() if loss_m[bmask].numel() > 0 else 0*loss_m.sum()

            if isinstance(loss, torch.Tensor) and loss.requires_grad:
                loss.backward()
                torch.nn.utils.clip_grad_norm_(model.parameters(), max_norm=1.0)
                optimizer.step()

        # Eval
        model.eval()
        all_preds = []
        all_targets = []
        all_masks = []
        with torch.no_grad():
            for batch in val_loader:
                if is_improved:
                    bx, by, bmask, lengths = batch
                    bx = bx.to(DEVICE)
                    logits = model(bx, lengths)
                    all_masks.append(bmask.numpy())
                else:
                    bx, by, bmask = batch
                    bx = bx.to(DEVICE)
                    logits = model(bx)
                    all_masks.append(bmask.numpy())

                all_preds.append(logits.cpu().numpy())
                all_targets.append(by.numpy())

        if len(all_preds) == 0:
            break

        y_pred = np.vstack(all_preds)
        y_true = np.vstack(all_targets)

        if is_improved:
            y_pred = np.sign(y_pred) * np.expm1(np.abs(y_pred))
            y_true = np.sign(y_true) * np.expm1(np.abs(y_true))

        mask = np.vstack(all_masks)
        valid_sum, count = 0, 0
        for i in range(len(PREDICTION_TARGETS)):
            m = mask[:, i]
            if m.sum() == 0: continue
            valid_sum += np.mean(np.abs(y_pred[m, i] - y_true[m, i]))
            count += 1
        current_metric = valid_sum / max(1, count)

        scheduler.step(current_metric)

        improved = current_metric < best_metric
        if improved:
            best_metric = current_metric
            best_state = {name: tensor.detach().cpu().clone() for name, tensor in model.state_dict().items()}
            epochs_without_improvement = 0
        else:
            epochs_without_improvement += 1

        if trial is not None:
            trial.report(current_metric, epoch)
            if trial.should_prune():
                raise optuna.exceptions.TrialPruned()

        if epochs_without_improvement >= PATIENCE:
            break

    if best_state is not None:
        model.load_state_dict(best_state)
    return model, best_metric

def get_hpo_objective(is_improved, loss_type='l1'):
    def objective(trial):
        hidden_size = trial.suggest_categorical("hidden_size", [32, 64, 128])
        lr = trial.suggest_float("lr", 1e-4, 1e-2, log=True)
        batch_size = trial.suggest_categorical("batch_size", [16, 32, 64])
        weight_decay = trial.suggest_float("weight_decay", 1e-6, 1e-3, log=True)
        dropout = trial.suggest_float("dropout", 0.2, 0.5)
        huber_delta = trial.suggest_float("huber_delta", 0.8, 2.0) if loss_type == 'huber' else 1.0


        if is_improved:
            train_ds = ImprovedYoYDatasetMTL(mtl_train_data_imp, robust_scaler, selected_indices)
            val_ds = ImprovedYoYDatasetMTL(mtl_val_data_imp, robust_scaler, selected_indices)
            collate = collate_fn_improved_mtl
            model = ImprovedShallowLSTM(len(selected_indices), hidden_size, len(PREDICTION_TARGETS), dropout).to(DEVICE)
        else:
            train_ds = YoYSequenceDatasetMTL(mtl_train_data, max_seq_length, scaler)
            val_ds = YoYSequenceDatasetMTL(mtl_val_data, max_seq_length, scaler)
            collate = None
            model = ShallowLSTMClassifier(len(feature_cols), hidden_size, len(PREDICTION_TARGETS), dropout).to(DEVICE)

        if collate:
            train_loader = DataLoader(train_ds, batch_size=batch_size, shuffle=True, collate_fn=collate)
            val_loader = DataLoader(val_ds, batch_size=batch_size, shuffle=False, collate_fn=collate)
        else:
            train_loader = DataLoader(train_ds, batch_size=batch_size, shuffle=True)
            val_loader = DataLoader(val_ds, batch_size=batch_size, shuffle=False)

        optimizer = torch.optim.Adam(model.parameters(), lr=lr, weight_decay=weight_decay)

        _, best_metric = train_and_eval(
            model, train_loader, val_loader, optimizer,
            is_improved=is_improved, trial=trial, loss_type=loss_type, huber_delta=huber_delta
        )
        return best_metric
    return objective

def evaluate_real_metrics(model, loader, device):
    model.eval()

    all_preds = []
    all_targets = []
    all_masks = []

    with torch.no_grad():

        for batch in loader:

            bx, by, bmask, lengths = batch

            preds = model(
                bx.to(device),
                lengths
            )

            all_preds.append(preds.cpu().numpy())
            all_targets.append(by.numpy())
            all_masks.append(bmask.numpy())

    y_pred = np.vstack(all_preds)
    y_true = np.vstack(all_targets)
    mask = np.vstack(all_masks).astype(bool)

    # back to real scale
    y_pred = np.sign(y_pred) * np.expm1(np.abs(y_pred))
    y_true = np.sign(y_true) * np.expm1(np.abs(y_true))

    errors = np.abs(y_pred - y_true)
    squared_errors = (y_pred - y_true) ** 2

    mae = errors[mask].mean()
    rmse = np.sqrt(squared_errors[mask].mean())

    print(f"Test MAE  (Real Scale): {mae:.4f}")
    print(f"Test RMSE (Real Scale): {rmse:.4f}")

    return float(mae), float(rmse)

# Training

## Baseline MTL

In [ ]:
print("Baseline MTL (Comparing Losses)")
best_mtl_baselines = {}
for l_type in ['l1', 'mse', 'huber']:
    print(f"\nEvaluating Baseline with '{l_type}' Loss...")
    pruner = optuna.pruners.MedianPruner(n_startup_trials=10, n_warmup_steps=15)
    study = optuna.create_study(direction="minimize", study_name=f"mtl_base_{l_type}", pruner=pruner)
    study.optimize(get_hpo_objective(False, loss_type=l_type), n_trials=OPTUNA_TRIALS)
    best_mtl_baselines[l_type] = study.best_trial.params
    print(f"[{l_type.upper()} - MTL Base] Best Avg Val Metric (minimize): {study.best_value:.4f}")
    print(f" Best Params: {study.best_trial.params}")

[I 2026-05-27 23:36:53,208] A new study created in memory with name: mtl_base_l1

Baseline MTL (Comparing Losses)

Evaluating Baseline with 'l1' Loss...

[I 2026-05-27 23:37:21,708] Trial 0 finished with value: 7.708547115325928 and parameters: {'hidden_size': 64, 'lr': 0.0024561830181530947, 'batch_size': 16, 'weight_decay': 4.073563111630223e-05, 'dropout': 0.4552946184128708}. Best is trial 0 with value: 7.708547115325928.
[I 2026-05-27 23:37:41,707] Trial 1 finished with value: 7.718625545501709 and parameters: {'hidden_size': 64, 'lr': 0.0005348168313228728, 'batch_size': 16, 'weight_decay': 4.724536784754057e-05, 'dropout': 0.29887133584388825}. Best is trial 0 with value: 7.708547115325928.
[I 2026-05-27 23:38:23,947] Trial 2 finished with value: 7.726640224456787 and parameters: {'hidden_size': 32, 'lr': 0.0002523990382394761, 'batch_size': 64, 'weight_decay': 4.171485706338313e-06, 'dropout': 0.2109400209257967}. Best is trial 0 with value: 7.708547115325928.
[I 2026-05-27 23:39:06,785] Trial 3 finished with value: 7.716990947723389 and parameters: {'hidden_size': 128, 'lr': 0.00011145998046238179, 'batch_size': 16, 'weight_decay': 0.00040855235223711005, 'dropout': 0.21428312124466772}. Best is trial 0 with value: 7.708547115325928.
[I 2026-05-27 23:39:44,074] Trial 4 finished with value: 7.727769374847412 and parameters: {'hidden_size': 64, 'lr': 0.00022405100354475923, 'batch_size': 16, 'weight_decay': 0.00047525566488452813, 'dropout': 0.39964902606828123}. Best is trial 0 with value: 7.708547115325928.
[I 2026-05-27 23:40:22,480] Trial 5 finished with value: 7.722053050994873 and parameters: {'hidden_size': 32, 'lr': 0.0007722411975262123, 'batch_size': 16, 'weight_decay': 4.763445801059129e-06, 'dropout': 0.27821018984652335}. Best is trial 0 with value: 7.708547115325928.
[I 2026-05-27 23:40:36,633] Trial 6 finished with value: 7.731241226196289 and parameters: {'hidden_size': 32, 'lr': 0.005531536704223713, 'batch_size': 64, 'weight_decay': 1.7842856497035303e-06, 'dropout': 0.2372956770879585}. Best is trial 0 with value: 7.708547115325928.
[I 2026-05-27 23:40:58,935] Trial 7 finished with value: 7.711206912994385 and parameters: {'hidden_size': 64, 'lr': 0.00011610155790122932, 'batch_size': 16, 'weight_decay': 0.0006063209877384561, 'dropout': 0.3677481377997154}. Best is trial 0 with value: 7.708547115325928.
[I 2026-05-27 23:41:20,632] Trial 8 finished with value: 7.72907018661499 and parameters: {'hidden_size': 128, 'lr': 0.000369642720612352, 'batch_size': 16, 'weight_decay': 4.6182818540045036e-05, 'dropout': 0.20639904976859208}. Best is trial 0 with value: 7.708547115325928.
[I 2026-05-27 23:41:42,255] Trial 9 finished with value: 7.731138229370117 and parameters: {'hidden_size': 32, 'lr': 0.0004535013197468557, 'batch_size': 16, 'weight_decay': 0.0006997202560751647, 'dropout': 0.3968966056037534}. Best is trial 0 with value: 7.708547115325928.
[I 2026-05-27 23:42:03,452] Trial 10 finished with value: 7.710582733154297 and parameters: {'hidden_size': 64, 'lr': 0.002322737559009314, 'batch_size': 32, 'weight_decay': 1.7347854599658423e-05, 'dropout': 0.4930424023125973}. Best is trial 0 with value: 7.708547115325928.
[I 2026-05-27 23:42:17,463] Trial 11 finished with value: 7.709232330322266 and parameters: {'hidden_size': 64, 'lr': 0.002618228979456986, 'batch_size': 32, 'weight_decay': 1.4758866032353119e-05, 'dropout': 0.4876960465004609}. Best is trial 0 with value: 7.708547115325928.
[I 2026-05-27 23:42:26,646] Trial 12 finished with value: 7.711756229400635 and parameters: {'hidden_size': 64, 'lr': 0.0021337696317047954, 'batch_size': 32, 'weight_decay': 0.00012215563504425976, 'dropout': 0.494032236977225}. Best is trial 0 with value: 7.708547115325928.
[I 2026-05-27 23:42:41,467] Trial 13 finished with value: 7.717398166656494 and parameters: {'hidden_size': 64, 'lr': 0.008237799468163377, 'batch_size': 32, 'weight_decay': 1.320274019134023e-05, 'dropout': 0.4457716148088274}. Best is trial 0 with value: 7.708547115325928.
[I 2026-05-27 23:43:01,235] Trial 14 finished with value: 7.706974029541016 and parameters: {'hidden_size': 64, 'lr': 0.001829926380027504, 'batch_size': 32, 'weight_decay': 0.00011131291648090386, 'dropout': 0.4484483191758639}. Best is trial 14 with value: 7.706974029541016.
[I 2026-05-27 23:43:12,274] Trial 15 finished with value: 7.724878787994385 and parameters: {'hidden_size': 64, 'lr': 0.0012191604262484143, 'batch_size': 32, 'weight_decay': 0.00014156309862928525, 'dropout': 0.4436763452995186}. Best is trial 14 with value: 7.706974029541016.
[I 2026-05-27 23:43:31,616] Trial 16 finished with value: 7.705895900726318 and parameters: {'hidden_size': 128, 'lr': 0.004295266638103382, 'batch_size': 64, 'weight_decay': 0.00014366360077148617, 'dropout': 0.44147361618463743}. Best is trial 16 with value: 7.705895900726318.
[I 2026-05-27 23:43:45,490] Trial 17 finished with value: 7.714563846588135 and parameters: {'hidden_size': 128, 'lr': 0.004633339960233581, 'batch_size': 64, 'weight_decay': 0.0001703679065660073, 'dropout': 0.3416115855176466}. Best is trial 16 with value: 7.705895900726318.
[I 2026-05-27 23:44:13,158] Trial 18 finished with value: 7.716139316558838 and parameters: {'hidden_size': 128, 'lr': 0.0014180895091158619, 'batch_size': 64, 'weight_decay': 9.408633596423781e-05, 'dropout': 0.4233308185269051}. Best is trial 16 with value: 7.705895900726318.
[I 2026-05-27 23:44:28,388] Trial 19 finished with value: 7.701783657073975 and parameters: {'hidden_size': 128, 'lr': 0.009507296355543367, 'batch_size': 64, 'weight_decay': 0.000263195603834127, 'dropout': 0.3443456797777094}. Best is trial 19 with value: 7.701783657073975.
[I 2026-05-27 23:44:43,609] Trial 20 finished with value: 7.707544326782227 and parameters: {'hidden_size': 128, 'lr': 0.009420077354518752, 'batch_size': 64, 'weight_decay': 0.00029894374781271954, 'dropout': 0.3337147800867232}. Best is trial 19 with value: 7.701783657073975.
[I 2026-05-27 23:44:55,572] Trial 21 finished with value: 7.702744007110596 and parameters: {'hidden_size': 128, 'lr': 0.0043369614450691945, 'batch_size': 64, 'weight_decay': 0.00023348567033950717, 'dropout': 0.3846187899729566}. Best is trial 19 with value: 7.701783657073975.
[I 2026-05-27 23:45:15,522] Trial 22 finished with value: 7.705451965332031 and parameters: {'hidden_size': 128, 'lr': 0.004069320814646867, 'batch_size': 64, 'weight_decay': 0.0002212090166654719, 'dropout': 0.37099079158541504}. Best is trial 19 with value: 7.701783657073975.
[I 2026-05-27 23:45:29,034] Trial 23 finished with value: 7.7005486488342285 and parameters: {'hidden_size': 128, 'lr': 0.00615038974929713, 'batch_size': 64, 'weight_decay': 0.00026291564836725335, 'dropout': 0.3696751799563983}. Best is trial 23 with value: 7.7005486488342285.
[I 2026-05-27 23:45:40,156] Trial 24 finished with value: 7.702320098876953 and parameters: {'hidden_size': 128, 'lr': 0.006906805891172904, 'batch_size': 64, 'weight_decay': 0.0009388646638442986, 'dropout': 0.311441725759773}. Best is trial 23 with value: 7.7005486488342285.
[I 2026-05-27 23:45:59,408] Trial 25 finished with value: 7.702354907989502 and parameters: {'hidden_size': 128, 'lr': 0.006738266540120209, 'batch_size': 64, 'weight_decay': 0.0008703631278865217, 'dropout': 0.31170082086312995}. Best is trial 23 with value: 7.7005486488342285.
[I 2026-05-27 23:46:15,814] Trial 26 finished with value: 7.701982021331787 and parameters: {'hidden_size': 128, 'lr': 0.009279175037352694, 'batch_size': 64, 'weight_decay': 0.0009979413971484268, 'dropout': 0.26938080940225156}. Best is trial 23 with value: 7.7005486488342285.
[I 2026-05-27 23:46:28,653] Trial 27 finished with value: 7.700761318206787 and parameters: {'hidden_size': 128, 'lr': 0.009788643886585676, 'batch_size': 64, 'weight_decay': 6.873763499569377e-05, 'dropout': 0.25455454702619085}. Best is trial 23 with value: 7.7005486488342285.
[I 2026-05-27 23:46:56,136] Trial 28 finished with value: 7.706081867218018 and parameters: {'hidden_size': 128, 'lr': 0.0033261773876800274, 'batch_size': 64, 'weight_decay': 6.480181006681244e-05, 'dropout': 0.24774904459962274}. Best is trial 23 with value: 7.7005486488342285.
[I 2026-05-27 23:47:12,967] Trial 29 finished with value: 7.705053806304932 and parameters: {'hidden_size': 128, 'lr': 0.0059767868814990495, 'batch_size': 64, 'weight_decay': 2.4729326646027684e-05, 'dropout': 0.35741524688346243}. Best is trial 23 with value: 7.7005486488342285.
[I 2026-05-27 23:47:28,924] Trial 30 finished with value: 7.7154717445373535 and parameters: {'hidden_size': 128, 'lr': 0.0032802528528045796, 'batch_size': 64, 'weight_decay': 7.468432627599206e-05, 'dropout': 0.3214991465466358}. Best is trial 23 with value: 7.7005486488342285.
[I 2026-05-27 23:47:48,885] Trial 31 finished with value: 7.705602645874023 and parameters: {'hidden_size': 128, 'lr': 0.009087439955883046, 'batch_size': 64, 'weight_decay': 0.00031586850807685063, 'dropout': 0.24535067108329908}. Best is trial 23 with value: 7.7005486488342285.
[I 2026-05-27 23:48:02,738] Trial 32 finished with value: 7.709714889526367 and parameters: {'hidden_size': 128, 'lr': 0.009168897542788289, 'batch_size': 64, 'weight_decay': 0.00041897580568242, 'dropout': 0.2761818952557674}. Best is trial 23 with value: 7.7005486488342285.
[I 2026-05-27 23:48:14,893] Trial 33 finished with value: 7.708411693572998 and parameters: {'hidden_size': 128, 'lr': 0.006983097528329181, 'batch_size': 64, 'weight_decay': 4.044013187109158e-05, 'dropout': 0.2830763676788171}. Best is trial 23 with value: 7.7005486488342285.
[I 2026-05-27 23:48:28,549] Trial 34 finished with value: 7.706968784332275 and parameters: {'hidden_size': 128, 'lr': 0.005440103825419043, 'batch_size': 64, 'weight_decay': 0.0005459671468526294, 'dropout': 0.26376971086686885}. Best is trial 23 with value: 7.7005486488342285.
[I 2026-05-27 23:48:46,841] Trial 35 finished with value: 7.707822799682617 and parameters: {'hidden_size': 128, 'lr': 0.009830505463552219, 'batch_size': 64, 'weight_decay': 0.00022917680109633292, 'dropout': 0.29897087129185745}. Best is trial 23 with value: 7.7005486488342285.
[I 2026-05-27 23:49:01,203] Trial 36 finished with value: 7.705738067626953 and parameters: {'hidden_size': 32, 'lr': 0.00772274932030666, 'batch_size': 64, 'weight_decay': 0.0003755707731774538, 'dropout': 0.23106200617310368}. Best is trial 23 with value: 7.7005486488342285.
[I 2026-05-27 23:49:15,665] Trial 37 finished with value: 7.706262588500977 and parameters: {'hidden_size': 128, 'lr': 0.003222075739279182, 'batch_size': 64, 'weight_decay': 8.835100744643457e-06, 'dropout': 0.41134553567512244}. Best is trial 23 with value: 7.7005486488342285.
[I 2026-05-27 23:49:32,890] Trial 38 finished with value: 7.710348129272461 and parameters: {'hidden_size': 32, 'lr': 0.0053810192052988395, 'batch_size': 64, 'weight_decay': 7.11702870646203e-05, 'dropout': 0.29336745467794845}. Best is trial 23 with value: 7.7005486488342285.
[I 2026-05-27 23:49:48,683] Trial 39 finished with value: 7.7004075050354 and parameters: {'hidden_size': 128, 'lr': 0.0009181121739550011, 'batch_size': 64, 'weight_decay': 2.790446863010488e-05, 'dropout': 0.2612526057795649}. Best is trial 39 with value: 7.7004075050354.
[I 2026-05-27 23:50:04,759] Trial 40 pruned.
[I 2026-05-27 23:50:45,733] Trial 41 finished with value: 7.709495544433594 and parameters: {'hidden_size': 128, 'lr': 0.0015361944600326182, 'batch_size': 64, 'weight_decay': 1.2541451044894937e-06, 'dropout': 0.2218966469828758}. Best is trial 39 with value: 7.7004075050354.
[I 2026-05-27 23:50:56,016] Trial 42 finished with value: 7.699491024017334 and parameters: {'hidden_size': 128, 'lr': 0.0006468581680199698, 'batch_size': 64, 'weight_decay': 2.291065215013995e-05, 'dropout': 0.261663392567145}. Best is trial 42 with value: 7.699491024017334.
[I 2026-05-27 23:51:10,474] Trial 43 pruned.
[I 2026-05-27 23:51:36,027] Trial 44 finished with value: 7.708841800689697 and parameters: {'hidden_size': 128, 'lr': 0.0007084488486841606, 'batch_size': 64, 'weight_decay': 7.606508526551021e-06, 'dropout': 0.2082079351570612}. Best is trial 42 with value: 7.699491024017334.
[I 2026-05-27 23:51:50,211] Trial 45 pruned.
[I 2026-05-27 23:52:04,012] Trial 46 finished with value: 7.70959997177124 and parameters: {'hidden_size': 128, 'lr': 0.0005633745631881459, 'batch_size': 64, 'weight_decay': 5.415107331878846e-05, 'dropout': 0.2891713812093107}. Best is trial 42 with value: 7.699491024017334.
[I 2026-05-27 23:52:16,780] Trial 47 pruned.
[I 2026-05-27 23:52:48,189] Trial 48 finished with value: 7.7012786865234375 and parameters: {'hidden_size': 128, 'lr': 0.000534952207629619, 'batch_size': 16, 'weight_decay': 1.1704749768713114e-05, 'dropout': 0.3301621795784072}. Best is trial 42 with value: 7.699491024017334.
[I 2026-05-27 23:53:02,118] Trial 49 pruned.
[I 2026-05-27 23:53:18,356] Trial 50 pruned.
[I 2026-05-27 23:53:31,253] Trial 51 finished with value: 7.707622051239014 and parameters: {'hidden_size': 128, 'lr': 0.0011258405194857072, 'batch_size': 16, 'weight_decay': 1.772193010338424e-05, 'dropout': 0.34836276933250204}. Best is trial 42 with value: 7.699491024017334.
[I 2026-05-27 23:53:48,937] Trial 52 pruned.
[I 2026-05-27 23:54:16,301] Trial 53 finished with value: 7.7134528160095215 and parameters: {'hidden_size': 128, 'lr': 0.0006072915509285962, 'batch_size': 32, 'weight_decay': 1.226483282539246e-05, 'dropout': 0.301658721009683}. Best is trial 42 with value: 7.699491024017334.
[I 2026-05-27 23:54:30,777] Trial 54 pruned.
[I 2026-05-27 23:54:56,496] Trial 55 finished with value: 7.711982727050781 and parameters: {'hidden_size': 128, 'lr': 0.00038163133521744794, 'batch_size': 64, 'weight_decay': 1.7633764083334695e-05, 'dropout': 0.243766392392332}. Best is trial 42 with value: 7.699491024017334.
[I 2026-05-27 23:55:12,087] Trial 56 finished with value: 7.712152481079102 and parameters: {'hidden_size': 128, 'lr': 0.0009757643503462575, 'batch_size': 32, 'weight_decay': 0.00017301391658091047, 'dropout': 0.20079468717800603}. Best is trial 42 with value: 7.699491024017334.
[I 2026-05-27 23:55:24,992] Trial 57 finished with value: 7.700785160064697 and parameters: {'hidden_size': 128, 'lr': 0.00128611458924622, 'batch_size': 64, 'weight_decay': 5.4487624888592375e-06, 'dropout': 0.3129183617845837}. Best is trial 42 with value: 7.699491024017334.
[I 2026-05-27 23:55:58,581] Trial 58 finished with value: 7.70993185043335 and parameters: {'hidden_size': 128, 'lr': 0.0006551060438613216, 'batch_size': 16, 'weight_decay': 3.903114322614754e-06, 'dropout': 0.3145476631064363}. Best is trial 42 with value: 7.699491024017334.
[I 2026-05-27 23:56:15,541] Trial 59 finished with value: 7.715766906738281 and parameters: {'hidden_size': 64, 'lr': 0.0018899080934456692, 'batch_size': 64, 'weight_decay': 5.278748961907179e-06, 'dropout': 0.26953213395676756}. Best is trial 42 with value: 7.699491024017334.
[I 2026-05-27 23:56:28,266] Trial 60 finished with value: 7.7038116455078125 and parameters: {'hidden_size': 128, 'lr': 0.0012424954750948419, 'batch_size': 64, 'weight_decay': 3.6819095004283306e-06, 'dropout': 0.2815789061561201}. Best is trial 42 with value: 7.699491024017334.
[I 2026-05-27 23:56:51,028] Trial 61 finished with value: 7.706993103027344 and parameters: {'hidden_size': 128, 'lr': 0.0004637036252557484, 'batch_size': 64, 'weight_decay': 5.1242955295697136e-05, 'dropout': 0.36128251746732476}. Best is trial 42 with value: 7.699491024017334.
[I 2026-05-27 23:57:11,702] Trial 62 finished with value: 7.701924800872803 and parameters: {'hidden_size': 128, 'lr': 0.0008237361022017585, 'batch_size': 64, 'weight_decay': 1.1269475597171288e-05, 'dropout': 0.34586606381488405}. Best is trial 42 with value: 7.699491024017334.
[I 2026-05-27 23:57:21,219] Trial 63 finished with value: 7.70958948135376 and parameters: {'hidden_size': 128, 'lr': 0.007814173846088132, 'batch_size': 64, 'weight_decay': 2.848939762765742e-06, 'dropout': 0.3224905152462638}. Best is trial 42 with value: 7.699491024017334.
[I 2026-05-27 23:57:36,319] Trial 64 finished with value: 7.70331335067749 and parameters: {'hidden_size': 128, 'lr': 0.00031143036936156013, 'batch_size': 64, 'weight_decay': 9.034809095712116e-06, 'dropout': 0.32988177554130393}. Best is trial 42 with value: 7.699491024017334.
[I 2026-05-27 23:57:55,755] Trial 65 finished with value: 7.707350254058838 and parameters: {'hidden_size': 128, 'lr': 0.00271268796864103, 'batch_size': 64, 'weight_decay': 2.1143243460221144e-05, 'dropout': 0.47086504006915386}. Best is trial 42 with value: 7.699491024017334.
[I 2026-05-27 23:58:09,548] Trial 66 pruned.
[I 2026-05-27 23:58:23,305] Trial 67 finished with value: 7.693244457244873 and parameters: {'hidden_size': 128, 'lr': 0.0014436947840858378, 'batch_size': 64, 'weight_decay': 3.876080827850374e-05, 'dropout': 0.39717688152505026}. Best is trial 67 with value: 7.693244457244873.
[I 2026-05-27 23:58:36,047] Trial 68 pruned.
[I 2026-05-27 23:58:47,713] Trial 69 pruned.
[I 2026-05-27 23:58:59,016] Trial 70 pruned.
[I 2026-05-27 23:59:10,870] Trial 71 finished with value: 7.711817264556885 and parameters: {'hidden_size': 128, 'lr': 0.0018416102382480903, 'batch_size': 64, 'weight_decay': 0.0002992148656514589, 'dropout': 0.35447753566099105}. Best is trial 67 with value: 7.693244457244873.
[I 2026-05-27 23:59:24,983] Trial 72 finished with value: 7.699041366577148 and parameters: {'hidden_size': 128, 'lr': 0.006604509584347705, 'batch_size': 64, 'weight_decay': 0.00018562679091158995, 'dropout': 0.3774103033477572}. Best is trial 67 with value: 7.693244457244873.
[I 2026-05-27 23:59:37,848] Trial 73 pruned.
[I 2026-05-28 00:00:01,854] Trial 74 finished with value: 7.7027668952941895 and parameters: {'hidden_size': 128, 'lr': 0.006035875898447346, 'batch_size': 64, 'weight_decay': 0.00018604379004504972, 'dropout': 0.3660201516006721}. Best is trial 67 with value: 7.693244457244873.
[I 2026-05-28 00:00:15,560] Trial 75 finished with value: 7.702880859375 and parameters: {'hidden_size': 128, 'lr': 0.004896575847068557, 'batch_size': 64, 'weight_decay': 0.00012940089080839282, 'dropout': 0.23469141865683954}. Best is trial 67 with value: 7.693244457244873.
[I 2026-05-28 00:00:28,483] Trial 76 pruned.
[I 2026-05-28 00:00:41,319] Trial 77 finished with value: 7.700827121734619 and parameters: {'hidden_size': 128, 'lr': 0.0022526280314642483, 'batch_size': 64, 'weight_decay': 3.831801366996346e-05, 'dropout': 0.4073008007917968}. Best is trial 67 with value: 7.693244457244873.
[I 2026-05-28 00:01:02,033] Trial 78 finished with value: 7.709606170654297 and parameters: {'hidden_size': 128, 'lr': 0.0021330287027687433, 'batch_size': 64, 'weight_decay': 7.991477365636e-05, 'dropout': 0.4290252060030297}. Best is trial 67 with value: 7.693244457244873.
[I 2026-05-28 00:01:19,341] Trial 79 finished with value: 7.698059558868408 and parameters: {'hidden_size': 128, 'lr': 0.002499590483910503, 'batch_size': 64, 'weight_decay': 3.636671333589599e-05, 'dropout': 0.3920659444456358}. Best is trial 67 with value: 7.693244457244873.
[I 2026-05-28 00:01:36,045] Trial 80 finished with value: 7.702645778656006 and parameters: {'hidden_size': 128, 'lr': 0.0027387552326223696, 'batch_size': 64, 'weight_decay': 6.192800603364263e-05, 'dropout': 0.38926595087682886}. Best is trial 67 with value: 7.693244457244873.
[I 2026-05-28 00:01:55,032] Trial 81 finished with value: 7.705883026123047 and parameters: {'hidden_size': 128, 'lr': 0.0015644593150440807, 'batch_size': 64, 'weight_decay': 4.8828721893278534e-05, 'dropout': 0.40458846093024337}. Best is trial 67 with value: 7.693244457244873.
[I 2026-05-28 00:02:15,010] Trial 82 finished with value: 7.713411808013916 and parameters: {'hidden_size': 128, 'lr': 0.0021748714640070885, 'batch_size': 64, 'weight_decay': 3.915239716303816e-05, 'dropout': 0.40224492766513426}. Best is trial 67 with value: 7.693244457244873.

[L1 - MTL Base] Best Avg Val Metric (minimize): 7.6932
 Best Params: {'hidden_size': 128, 'lr': 0.0014436947840858378, 'batch_size': 64, 'weight_decay': 3.876080827850374e-05, 'dropout': 0.39717688152505026}

Evaluating Baseline with 'mse' Loss...

[I 2026-05-28 00:06:30,368] Trial 0 finished with value: 7.724384307861328 and parameters: {'hidden_size': 128, 'lr': 0.0015145330934124405, 'batch_size': 16, 'weight_decay': 3.253113999087654e-05, 'dropout': 0.3269529567088313}. Best is trial 0 with value: 7.724384307861328.
[I 2026-05-28 00:06:38,304] Trial 1 finished with value: 7.764683246612549 and parameters: {'hidden_size': 64, 'lr': 0.004633281831020155, 'batch_size': 64, 'weight_decay': 1.4118533763819458e-06, 'dropout': 0.4763039504945981}. Best is trial 0 with value: 7.724384307861328.
[I 2026-05-28 00:07:26,753] Trial 2 finished with value: 7.72674560546875 and parameters: {'hidden_size': 32, 'lr': 0.0001222175136019422, 'batch_size': 16, 'weight_decay': 4.435005835871002e-06, 'dropout': 0.28090996968121984}. Best is trial 0 with value: 7.724384307861328.
[I 2026-05-28 00:07:41,832] Trial 3 finished with value: 7.844062328338623 and parameters: {'hidden_size': 32, 'lr': 0.0004939079126984807, 'batch_size': 64, 'weight_decay': 1.4541764743630934e-06, 'dropout': 0.36696554115794705}. Best is trial 0 with value: 7.724384307861328.
[I 2026-05-28 00:08:00,504] Trial 4 finished with value: 7.725255489349365 and parameters: {'hidden_size': 128, 'lr': 0.0001006976981795849, 'batch_size': 32, 'weight_decay': 1.044345867423643e-05, 'dropout': 0.40867363072292184}. Best is trial 0 with value: 7.724384307861328.
[I 2026-05-28 00:08:13,592] Trial 5 finished with value: 7.710989475250244 and parameters: {'hidden_size': 128, 'lr': 0.0009807495412532258, 'batch_size': 16, 'weight_decay': 0.0003484115552706893, 'dropout': 0.21082514346538644}. Best is trial 5 with value: 7.710989475250244.
[I 2026-05-28 00:08:31,636] Trial 6 finished with value: 7.703910827636719 and parameters: {'hidden_size': 128, 'lr': 0.0001680900192427753, 'batch_size': 16, 'weight_decay': 1.1856488811076048e-06, 'dropout': 0.20321032597626892}. Best is trial 6 with value: 7.703910827636719.
[I 2026-05-28 00:08:41,300] Trial 7 finished with value: 7.741922855377197 and parameters: {'hidden_size': 128, 'lr': 0.0005943019313706014, 'batch_size': 64, 'weight_decay': 2.5184724657531475e-06, 'dropout': 0.4249119032870048}. Best is trial 6 with value: 7.703910827636719.
[I 2026-05-28 00:08:54,859] Trial 8 finished with value: 7.747486114501953 and parameters: {'hidden_size': 64, 'lr': 0.000153075432052672, 'batch_size': 32, 'weight_decay': 0.0002969608466458304, 'dropout': 0.39937111309704054}. Best is trial 6 with value: 7.703910827636719.
[I 2026-05-28 00:09:04,970] Trial 9 finished with value: 7.731311798095703 and parameters: {'hidden_size': 32, 'lr': 0.0008315883574358678, 'batch_size': 32, 'weight_decay': 0.0004136547606324673, 'dropout': 0.4601209445149437}. Best is trial 6 with value: 7.703910827636719.
[I 2026-05-28 00:09:19,071] Trial 10 finished with value: 7.718669891357422 and parameters: {'hidden_size': 128, 'lr': 0.0003021414757293968, 'batch_size': 16, 'weight_decay': 4.31809878255909e-05, 'dropout': 0.20007335011020086}. Best is trial 6 with value: 7.703910827636719.
[I 2026-05-28 00:09:30,962] Trial 11 finished with value: 7.724404811859131 and parameters: {'hidden_size': 128, 'lr': 0.0020194274000316244, 'batch_size': 16, 'weight_decay': 0.00011457281422406408, 'dropout': 0.20345148588175863}. Best is trial 6 with value: 7.703910827636719.
[I 2026-05-28 00:09:44,936] Trial 12 finished with value: 7.70635461807251 and parameters: {'hidden_size': 128, 'lr': 0.007731312952569907, 'batch_size': 16, 'weight_decay': 9.902475242657157e-06, 'dropout': 0.2613150644523836}. Best is trial 6 with value: 7.703910827636719.
[I 2026-05-28 00:09:59,719] Trial 13 finished with value: 7.723511219024658 and parameters: {'hidden_size': 128, 'lr': 0.008423644449818909, 'batch_size': 16, 'weight_decay': 7.827677987033731e-06, 'dropout': 0.259949511915162}. Best is trial 6 with value: 7.703910827636719.
[I 2026-05-28 00:10:12,423] Trial 14 finished with value: 7.717689514160156 and parameters: {'hidden_size': 128, 'lr': 0.0031431773736411255, 'batch_size': 16, 'weight_decay': 1.4153267752588466e-05, 'dropout': 0.27088003314543085}. Best is trial 6 with value: 7.703910827636719.
[I 2026-05-28 00:10:26,844] Trial 15 pruned.
[I 2026-05-28 00:10:42,091] Trial 16 finished with value: 7.710414886474609 and parameters: {'hidden_size': 128, 'lr': 0.009360277748093974, 'batch_size': 16, 'weight_decay': 1.012245909195434e-06, 'dropout': 0.23122594653577827}. Best is trial 6 with value: 7.703910827636719.
[I 2026-05-28 00:11:04,513] Trial 17 finished with value: 7.70239782333374 and parameters: {'hidden_size': 128, 'lr': 0.004726799588787259, 'batch_size': 16, 'weight_decay': 7.590185516168001e-05, 'dropout': 0.2530750210693299}. Best is trial 17 with value: 7.70239782333374.
[I 2026-05-28 00:11:12,767] Trial 18 finished with value: 7.729200839996338 and parameters: {'hidden_size': 64, 'lr': 0.0019925421914001188, 'batch_size': 64, 'weight_decay': 9.149629130599505e-05, 'dropout': 0.23944205724231504}. Best is trial 17 with value: 7.70239782333374.
[I 2026-05-28 00:11:28,230] Trial 19 finished with value: 7.727380752563477 and parameters: {'hidden_size': 32, 'lr': 0.004774533007269328, 'batch_size': 32, 'weight_decay': 8.666773471122525e-05, 'dropout': 0.3071618120363385}. Best is trial 17 with value: 7.70239782333374.
[I 2026-05-28 00:11:45,602] Trial 20 finished with value: 7.704643726348877 and parameters: {'hidden_size': 128, 'lr': 0.00023654116864450626, 'batch_size': 16, 'weight_decay': 0.000984392831853137, 'dropout': 0.3573954263702056}. Best is trial 17 with value: 7.70239782333374.
[I 2026-05-28 00:12:01,485] Trial 21 finished with value: 7.716977596282959 and parameters: {'hidden_size': 128, 'lr': 0.0002183195524027955, 'batch_size': 16, 'weight_decay': 0.0006842026728176731, 'dropout': 0.3537315619035129}. Best is trial 17 with value: 7.70239782333374.
[I 2026-05-28 00:12:16,359] Trial 22 finished with value: 7.716083526611328 and parameters: {'hidden_size': 128, 'lr': 0.0003982625388749288, 'batch_size': 16, 'weight_decay': 0.00017528840923612798, 'dropout': 0.37209849213539326}. Best is trial 17 with value: 7.70239782333374.
[I 2026-05-28 00:12:33,875] Trial 23 finished with value: 7.704372882843018 and parameters: {'hidden_size': 128, 'lr': 0.00020811366759572504, 'batch_size': 16, 'weight_decay': 0.0008915433238149461, 'dropout': 0.3339410305612386}. Best is trial 17 with value: 7.70239782333374.
[I 2026-05-28 00:12:49,847] Trial 24 finished with value: 7.713710308074951 and parameters: {'hidden_size': 128, 'lr': 0.00014600979012697248, 'batch_size': 16, 'weight_decay': 1.7616928004170442e-05, 'dropout': 0.23495692282213437}. Best is trial 17 with value: 7.70239782333374.
[I 2026-05-28 00:13:06,995] Trial 25 finished with value: 7.723232269287109 and parameters: {'hidden_size': 128, 'lr': 0.0007549972848997625, 'batch_size': 16, 'weight_decay': 4.91133604479948e-05, 'dropout': 0.32246192649150485}. Best is trial 17 with value: 7.70239782333374.
[I 2026-05-28 00:13:19,951] Trial 26 finished with value: 7.70026159286499 and parameters: {'hidden_size': 128, 'lr': 0.0003996336467000021, 'batch_size': 16, 'weight_decay': 0.00018735246703341227, 'dropout': 0.28941099317671176}. Best is trial 26 with value: 7.70026159286499.
[I 2026-05-28 00:13:34,076] Trial 27 finished with value: 7.719095230102539 and parameters: {'hidden_size': 128, 'lr': 0.00035821830980819705, 'batch_size': 16, 'weight_decay': 0.00017079000296550564, 'dropout': 0.2901103114098594}. Best is trial 26 with value: 7.70026159286499.
[I 2026-05-28 00:13:44,662] Trial 28 finished with value: 7.743558406829834 and parameters: {'hidden_size': 64, 'lr': 0.0011944120436576775, 'batch_size': 32, 'weight_decay': 2.1681305117964594e-05, 'dropout': 0.2505576783156147}. Best is trial 26 with value: 7.70026159286499.
[I 2026-05-28 00:13:55,454] Trial 29 finished with value: 7.72509241104126 and parameters: {'hidden_size': 32, 'lr': 0.0016265383426816477, 'batch_size': 64, 'weight_decay': 2.9230131306630418e-05, 'dropout': 0.22364869423914757}. Best is trial 26 with value: 7.70026159286499.
[I 2026-05-28 00:14:15,074] Trial 30 finished with value: 7.714653015136719 and parameters: {'hidden_size': 128, 'lr': 0.0005221513275891458, 'batch_size': 16, 'weight_decay': 5.94182289843591e-05, 'dropout': 0.2928997156643299}. Best is trial 26 with value: 7.70026159286499.
[I 2026-05-28 00:14:32,006] Trial 31 finished with value: 7.706081390380859 and parameters: {'hidden_size': 128, 'lr': 0.00015349255623278948, 'batch_size': 16, 'weight_decay': 0.00022001641502688565, 'dropout': 0.33220044817763755}. Best is trial 26 with value: 7.70026159286499.
[I 2026-05-28 00:14:43,777] Trial 32 finished with value: 7.705821990966797 and parameters: {'hidden_size': 128, 'lr': 0.00017827809073071572, 'batch_size': 16, 'weight_decay': 0.0005864787478661874, 'dropout': 0.3282820967989961}. Best is trial 26 with value: 7.70026159286499.
[I 2026-05-28 00:14:58,640] Trial 33 finished with value: 7.71539831161499 and parameters: {'hidden_size': 128, 'lr': 0.00032292397125555246, 'batch_size': 16, 'weight_decay': 0.0001300867782808861, 'dropout': 0.27247602399112314}. Best is trial 26 with value: 7.70026159286499.
[I 2026-05-28 00:15:20,160] Trial 34 finished with value: 7.715287685394287 and parameters: {'hidden_size': 128, 'lr': 0.00020248000186525144, 'batch_size': 16, 'weight_decay': 7.201774659905318e-05, 'dropout': 0.24807317979500126}. Best is trial 26 with value: 7.70026159286499.
[I 2026-05-28 00:15:32,853] Trial 35 pruned.
[I 2026-05-28 00:15:46,744] Trial 36 pruned.
[I 2026-05-28 00:16:02,616] Trial 37 pruned.
[I 2026-05-28 00:16:11,982] Trial 38 finished with value: 7.741044521331787 and parameters: {'hidden_size': 64, 'lr': 0.0002972603159290876, 'batch_size': 64, 'weight_decay': 5.812574180969306e-06, 'dropout': 0.3405388691768645}. Best is trial 26 with value: 7.70026159286499.
[I 2026-05-28 00:16:27,303] Trial 39 finished with value: 7.710395812988281 and parameters: {'hidden_size': 128, 'lr': 0.00011506466076560008, 'batch_size': 32, 'weight_decay': 0.00046844507715745724, 'dropout': 0.49080909360835856}. Best is trial 26 with value: 7.70026159286499.
[I 2026-05-28 00:16:38,667] Trial 40 finished with value: 7.730443477630615 and parameters: {'hidden_size': 32, 'lr': 0.0006125714331965367, 'batch_size': 16, 'weight_decay': 2.2069712606527127e-06, 'dropout': 0.21342579502936082}. Best is trial 26 with value: 7.70026159286499.
[I 2026-05-28 00:16:55,171] Trial 41 pruned.
[I 2026-05-28 00:17:13,232] Trial 42 finished with value: 7.71520471572876 and parameters: {'hidden_size': 128, 'lr': 0.00019035438326389434, 'batch_size': 16, 'weight_decay': 0.00059551176015511, 'dropout': 0.4327053521130295}. Best is trial 26 with value: 7.70026159286499.
[I 2026-05-28 00:17:30,029] Trial 43 finished with value: 7.718077182769775 and parameters: {'hidden_size': 128, 'lr': 0.00013629667840773786, 'batch_size': 16, 'weight_decay': 0.0003065259736444658, 'dropout': 0.285567012921117}. Best is trial 26 with value: 7.70026159286499.
[I 2026-05-28 00:17:44,342] Trial 44 finished with value: 7.70775032043457 and parameters: {'hidden_size': 128, 'lr': 0.00027090180617432244, 'batch_size': 16, 'weight_decay': 0.0006536390974955275, 'dropout': 0.31465490634319104}. Best is trial 26 with value: 7.70026159286499.
[I 2026-05-28 00:17:57,476] Trial 45 finished with value: 7.71200704574585 and parameters: {'hidden_size': 128, 'lr': 0.00043113043803337026, 'batch_size': 16, 'weight_decay': 0.0003710444168236041, 'dropout': 0.3772947134611749}. Best is trial 26 with value: 7.70026159286499.
[I 2026-05-28 00:18:13,534] Trial 46 finished with value: 7.704769134521484 and parameters: {'hidden_size': 128, 'lr': 0.006428492048996626, 'batch_size': 16, 'weight_decay': 3.8786908347934567e-05, 'dropout': 0.34142125178896593}. Best is trial 26 with value: 7.70026159286499.
[I 2026-05-28 00:18:27,105] Trial 47 pruned.
[I 2026-05-28 00:18:37,873] Trial 48 finished with value: 7.7035675048828125 and parameters: {'hidden_size': 64, 'lr': 0.0011015282548762927, 'batch_size': 16, 'weight_decay': 0.0002517430994616287, 'dropout': 0.41196158560558965}. Best is trial 26 with value: 7.70026159286499.
[I 2026-05-28 00:19:04,793] Trial 49 finished with value: 7.709129333496094 and parameters: {'hidden_size': 64, 'lr': 0.003010488634258794, 'batch_size': 16, 'weight_decay': 0.0002428631089183188, 'dropout': 0.4505321933395171}. Best is trial 26 with value: 7.70026159286499.
[I 2026-05-28 00:19:16,375] Trial 50 pruned.
[I 2026-05-28 00:19:28,821] Trial 51 finished with value: 7.713108062744141 and parameters: {'hidden_size': 64, 'lr': 0.0006685381086941792, 'batch_size': 16, 'weight_decay': 0.0005172054633869769, 'dropout': 0.2700235889482656}. Best is trial 26 with value: 7.70026159286499.
[I 2026-05-28 00:19:43,128] Trial 52 pruned.
[I 2026-05-28 00:19:59,323] Trial 53 finished with value: 7.703155040740967 and parameters: {'hidden_size': 64, 'lr': 0.004446142745442302, 'batch_size': 16, 'weight_decay': 0.0009146295407855255, 'dropout': 0.40548518725918065}. Best is trial 26 with value: 7.70026159286499.
[I 2026-05-28 00:20:10,654] Trial 54 finished with value: 7.702816009521484 and parameters: {'hidden_size': 64, 'lr': 0.0047061570367792184, 'batch_size': 16, 'weight_decay': 0.0007490251331919324, 'dropout': 0.4059532193603907}. Best is trial 26 with value: 7.70026159286499.
[I 2026-05-28 00:20:22,217] Trial 55 finished with value: 7.710362911224365 and parameters: {'hidden_size': 64, 'lr': 0.004961353176214485, 'batch_size': 16, 'weight_decay': 0.0004215185172945798, 'dropout': 0.4001827488052548}. Best is trial 26 with value: 7.70026159286499.
[I 2026-05-28 00:20:36,657] Trial 56 pruned.
[I 2026-05-28 00:20:55,313] Trial 57 finished with value: 7.701049327850342 and parameters: {'hidden_size': 64, 'lr': 0.006522443147098052, 'batch_size': 16, 'weight_decay': 0.00018972978128907564, 'dropout': 0.4654254888653735}. Best is trial 26 with value: 7.70026159286499.
[I 2026-05-28 00:21:17,570] Trial 58 finished with value: 7.704522609710693 and parameters: {'hidden_size': 64, 'lr': 0.006326488869353024, 'batch_size': 16, 'weight_decay': 0.00019809582362385387, 'dropout': 0.4775367154755349}. Best is trial 26 with value: 7.70026159286499.
[I 2026-05-28 00:21:27,129] Trial 59 finished with value: 7.72066068649292 and parameters: {'hidden_size': 64, 'lr': 0.0038944232258496096, 'batch_size': 32, 'weight_decay': 0.0002836262433281895, 'dropout': 0.41359437677636185}. Best is trial 26 with value: 7.70026159286499.
[I 2026-05-28 00:21:41,858] Trial 60 finished with value: 7.706117630004883 and parameters: {'hidden_size': 64, 'lr': 0.006574170853571393, 'batch_size': 16, 'weight_decay': 0.00014852985531393478, 'dropout': 0.44161908041378417}. Best is trial 26 with value: 7.70026159286499.
[I 2026-05-28 00:21:59,818] Trial 61 finished with value: 7.702150344848633 and parameters: {'hidden_size': 64, 'lr': 0.002203196054789826, 'batch_size': 16, 'weight_decay': 0.0007806072607169203, 'dropout': 0.42221332531264877}. Best is trial 26 with value: 7.70026159286499.
[I 2026-05-28 00:22:15,104] Trial 62 finished with value: 7.723150730133057 and parameters: {'hidden_size': 64, 'lr': 0.0026892874026000504, 'batch_size': 16, 'weight_decay': 0.0007045453285457777, 'dropout': 0.42328054149151556}. Best is trial 26 with value: 7.70026159286499.
[I 2026-05-28 00:22:35,596] Trial 63 finished with value: 7.704041957855225 and parameters: {'hidden_size': 64, 'lr': 0.0021669029795077575, 'batch_size': 16, 'weight_decay': 0.0007779826492429528, 'dropout': 0.4729467950472425}. Best is trial 26 with value: 7.70026159286499.
[I 2026-05-28 00:22:49,923] Trial 64 finished with value: 7.711317539215088 and parameters: {'hidden_size': 64, 'lr': 0.0015008045104287337, 'batch_size': 16, 'weight_decay': 0.0004510676027326964, 'dropout': 0.39821293899324867}. Best is trial 26 with value: 7.70026159286499.
[I 2026-05-28 00:23:14,848] Trial 65 finished with value: 7.706783294677734 and parameters: {'hidden_size': 64, 'lr': 0.00549852479019266, 'batch_size': 16, 'weight_decay': 0.00027683672849656996, 'dropout': 0.44283084215588703}. Best is trial 26 with value: 7.70026159286499.
[I 2026-05-28 00:23:28,304] Trial 66 finished with value: 7.702786922454834 and parameters: {'hidden_size': 64, 'lr': 0.007719194590690242, 'batch_size': 16, 'weight_decay': 0.00011762497317230374, 'dropout': 0.4700664336128838}. Best is trial 26 with value: 7.70026159286499.
[I 2026-05-28 00:23:41,001] Trial 67 finished with value: 7.705458164215088 and parameters: {'hidden_size': 64, 'lr': 0.009384519141002754, 'batch_size': 16, 'weight_decay': 8.632592454923304e-05, 'dropout': 0.4685854796740024}. Best is trial 26 with value: 7.70026159286499.
[I 2026-05-28 00:23:58,698] Trial 68 finished with value: 7.715518951416016 and parameters: {'hidden_size': 64, 'lr': 0.008201393424402934, 'batch_size': 16, 'weight_decay': 0.00012022945837639994, 'dropout': 0.49282526121058506}. Best is trial 26 with value: 7.70026159286499.
[I 2026-05-28 00:24:06,957] Trial 69 finished with value: 7.763286113739014 and parameters: {'hidden_size': 64, 'lr': 0.003950501810128887, 'batch_size': 64, 'weight_decay': 0.00016783502732879135, 'dropout': 0.46685905702409436}. Best is trial 26 with value: 7.70026159286499.
[I 2026-05-28 00:24:22,864] Trial 70 finished with value: 7.718092441558838 and parameters: {'hidden_size': 64, 'lr': 0.007603860195027731, 'batch_size': 16, 'weight_decay': 5.9786070421865096e-05, 'dropout': 0.48159760680187885}. Best is trial 26 with value: 7.70026159286499.
[I 2026-05-28 00:24:39,422] Trial 71 finished with value: 7.707540988922119 and parameters: {'hidden_size': 64, 'lr': 0.00553256447113228, 'batch_size': 16, 'weight_decay': 0.0007801732019936677, 'dropout': 0.417726742946966}. Best is trial 26 with value: 7.70026159286499.
[I 2026-05-28 00:25:00,494] Trial 72 finished with value: 7.713572025299072 and parameters: {'hidden_size': 64, 'lr': 0.003527212753923335, 'batch_size': 16, 'weight_decay': 0.0005455775797163655, 'dropout': 0.4019282511987211}. Best is trial 26 with value: 7.70026159286499.
[I 2026-05-28 00:25:12,007] Trial 73 finished with value: 7.7246317863464355 and parameters: {'hidden_size': 64, 'lr': 0.0024812953328257237, 'batch_size': 16, 'weight_decay': 0.00010570211768472523, 'dropout': 0.382979382675279}. Best is trial 26 with value: 7.70026159286499.
[I 2026-05-28 00:25:27,006] Trial 74 finished with value: 7.7162041664123535 and parameters: {'hidden_size': 64, 'lr': 0.0012988320600489688, 'batch_size': 16, 'weight_decay': 0.0003514247506284397, 'dropout': 0.4324957426838839}. Best is trial 26 with value: 7.70026159286499.
[I 2026-05-28 00:25:40,285] Trial 75 finished with value: 7.713207244873047 and parameters: {'hidden_size': 32, 'lr': 0.004570848597371047, 'batch_size': 16, 'weight_decay': 0.0002018104690694873, 'dropout': 0.4468715454507477}. Best is trial 26 with value: 7.70026159286499.
[I 2026-05-28 00:26:01,221] Trial 76 finished with value: 7.706578731536865 and parameters: {'hidden_size': 64, 'lr': 0.0072272021833273345, 'batch_size': 16, 'weight_decay': 0.00016736173655854675, 'dropout': 0.3690572989513903}. Best is trial 26 with value: 7.70026159286499.
[I 2026-05-28 00:26:13,006] Trial 77 finished with value: 7.733408451080322 and parameters: {'hidden_size': 64, 'lr': 0.001790093920816192, 'batch_size': 32, 'weight_decay': 7.558606334833749e-05, 'dropout': 0.45728802365736954}. Best is trial 26 with value: 7.70026159286499.
[I 2026-05-28 00:26:26,471] Trial 78 finished with value: 7.700925350189209 and parameters: {'hidden_size': 64, 'lr': 0.004449887063785159, 'batch_size': 16, 'weight_decay': 0.0007936424640142776, 'dropout': 0.4986942351325009}. Best is trial 26 with value: 7.70026159286499.

[MSE - MTL Base] Best Avg Val Metric (minimize): 7.6997
 Best Params: {'hidden_size': 64, 'lr': 0.005358904243667092, 'batch_size': 16, 'weight_decay': 0.0007934779438993115, 'dropout': 0.46860618654311137}

Evaluating Baseline with 'huber' Loss...

[I 2026-05-28 00:31:50,971] Trial 0 finished with value: 7.700599670410156 and parameters: {'hidden_size': 32, 'lr': 0.008519254385214498, 'batch_size': 32, 'weight_decay': 5.473570001987502e-05, 'dropout': 0.43932997420898057, 'huber_delta': 1.7527364200689597}. Best is trial 0 with value: 7.700599670410156.
[I 2026-05-28 00:32:02,606] Trial 1 finished with value: 7.717978000640869 and parameters: {'hidden_size': 32, 'lr': 0.0024189438816534024, 'batch_size': 32, 'weight_decay': 1.776158101357255e-06, 'dropout': 0.46728196361073787, 'huber_delta': 1.5287744090532973}. Best is trial 0 with value: 7.700599670410156.
[I 2026-05-28 00:32:14,647] Trial 2 finished with value: 7.722008228302002 and parameters: {'hidden_size': 32, 'lr': 0.0011005108223455413, 'batch_size': 64, 'weight_decay': 0.0006224052693756531, 'dropout': 0.34777809003451254, 'huber_delta': 1.3008192146298994}. Best is trial 0 with value: 7.700599670410156.
[I 2026-05-28 00:32:27,533] Trial 3 finished with value: 7.7026047706604 and parameters: {'hidden_size': 64, 'lr': 0.0006758167270896931, 'batch_size': 64, 'weight_decay': 5.0129747218438715e-05, 'dropout': 0.4984873997301323, 'huber_delta': 1.9761137212745608}. Best is trial 0 with value: 7.700599670410156.
[I 2026-05-28 00:32:36,910] Trial 4 finished with value: 7.699800968170166 and parameters: {'hidden_size': 128, 'lr': 0.00183842072491874, 'batch_size': 64, 'weight_decay': 6.542695518647331e-05, 'dropout': 0.33152841654587695, 'huber_delta': 1.841915033656218}. Best is trial 4 with value: 7.699800968170166.
[I 2026-05-28 00:32:51,832] Trial 5 finished with value: 7.706944942474365 and parameters: {'hidden_size': 64, 'lr': 0.003967608894345303, 'batch_size': 16, 'weight_decay': 2.1877318595756845e-06, 'dropout': 0.3264295179000475, 'huber_delta': 1.10589701704804}. Best is trial 4 with value: 7.699800968170166.
[I 2026-05-28 00:33:10,034] Trial 6 finished with value: 7.708465576171875 and parameters: {'hidden_size': 32, 'lr': 0.0004466762478068638, 'batch_size': 16, 'weight_decay': 0.00020770861806201376, 'dropout': 0.46018742675028274, 'huber_delta': 0.8668966560274818}. Best is trial 4 with value: 7.699800968170166.
[I 2026-05-28 00:33:45,059] Trial 7 finished with value: 7.726546764373779 and parameters: {'hidden_size': 128, 'lr': 0.0002803725330109342, 'batch_size': 16, 'weight_decay': 0.00041956675031678154, 'dropout': 0.33294346970171673, 'huber_delta': 0.914726745145782}. Best is trial 4 with value: 7.699800968170166.
[I 2026-05-28 00:33:55,578] Trial 8 finished with value: 7.699171543121338 and parameters: {'hidden_size': 64, 'lr': 0.004949374046932596, 'batch_size': 64, 'weight_decay': 2.908977622293796e-06, 'dropout': 0.25281138307490564, 'huber_delta': 1.3214867542388182}. Best is trial 8 with value: 7.699171543121338.
[I 2026-05-28 00:34:14,657] Trial 9 finished with value: 7.709657669067383 and parameters: {'hidden_size': 32, 'lr': 0.005099999755847931, 'batch_size': 64, 'weight_decay': 2.1466910365814955e-06, 'dropout': 0.39932738534666834, 'huber_delta': 1.6854027056554814}. Best is trial 8 with value: 7.699171543121338.
[I 2026-05-28 00:34:26,952] Trial 10 finished with value: 7.70055627822876 and parameters: {'hidden_size': 64, 'lr': 0.00994511230161214, 'batch_size': 64, 'weight_decay': 8.396889363527943e-06, 'dropout': 0.21745610857899933, 'huber_delta': 1.2904216469620742}. Best is trial 8 with value: 7.699171543121338.
[I 2026-05-28 00:34:37,413] Trial 11 finished with value: 7.706906795501709 and parameters: {'hidden_size': 128, 'lr': 0.0015748363459449615, 'batch_size': 64, 'weight_decay': 1.3466859044500734e-05, 'dropout': 0.2469662399273317, 'huber_delta': 1.96480741694613}. Best is trial 8 with value: 7.699171543121338.
[I 2026-05-28 00:34:50,153] Trial 12 pruned.
[I 2026-05-28 00:35:03,613] Trial 13 finished with value: 7.706724643707275 and parameters: {'hidden_size': 128, 'lr': 0.0026780560943409967, 'batch_size': 64, 'weight_decay': 1.1365914739434864e-05, 'dropout': 0.2858597886831047, 'huber_delta': 1.1355436389327909}. Best is trial 8 with value: 7.699171543121338.
[I 2026-05-28 00:35:18,559] Trial 14 finished with value: 7.701619625091553 and parameters: {'hidden_size': 64, 'lr': 0.0017091998441561035, 'batch_size': 64, 'weight_decay': 5.325757893488533e-06, 'dropout': 0.38641928963895944, 'huber_delta': 1.7039766616883671}. Best is trial 8 with value: 7.699171543121338.
[I 2026-05-28 00:35:28,553] Trial 15 finished with value: 7.698991298675537 and parameters: {'hidden_size': 128, 'lr': 0.004556702320992104, 'batch_size': 32, 'weight_decay': 2.373648741967889e-05, 'dropout': 0.20827476379256465, 'huber_delta': 1.5556235165766894}. Best is trial 15 with value: 7.698991298675537.
[I 2026-05-28 00:35:39,997] Trial 16 finished with value: 7.707477569580078 and parameters: {'hidden_size': 64, 'lr': 0.005079754206693234, 'batch_size': 32, 'weight_decay': 1.9272699740315757e-05, 'dropout': 0.21091202844158574, 'huber_delta': 1.55059625461809}. Best is trial 15 with value: 7.698991298675537.
[I 2026-05-28 00:35:57,257] Trial 17 finished with value: 7.711181640625 and parameters: {'hidden_size': 64, 'lr': 0.004143174832532317, 'batch_size': 32, 'weight_decay': 4.069166914115953e-06, 'dropout': 0.2565263316711241, 'huber_delta': 1.3683514211436956}. Best is trial 15 with value: 7.698991298675537.
[I 2026-05-28 00:36:16,428] Trial 18 finished with value: 7.7092413902282715 and parameters: {'hidden_size': 128, 'lr': 0.007578402961497814, 'batch_size': 32, 'weight_decay': 2.3910317336069978e-05, 'dropout': 0.29744386414256807, 'huber_delta': 1.1976831288983039}. Best is trial 15 with value: 7.698991298675537.
[I 2026-05-28 00:36:28,812] Trial 19 pruned.
[I 2026-05-28 00:36:45,019] Trial 20 finished with value: 7.704099178314209 and parameters: {'hidden_size': 128, 'lr': 0.003017628883033033, 'batch_size': 32, 'weight_decay': 4.949113516613038e-06, 'dropout': 0.23912813419976045, 'huber_delta': 1.5928585506243427}. Best is trial 15 with value: 7.698991298675537.
[I 2026-05-28 00:36:55,129] Trial 21 finished with value: 7.696168422698975 and parameters: {'hidden_size': 128, 'lr': 0.0017742055565057413, 'batch_size': 64, 'weight_decay': 8.693217014449475e-05, 'dropout': 0.30723948204507334, 'huber_delta': 1.8132648804424298}. Best is trial 21 with value: 7.696168422698975.
[I 2026-05-28 00:37:03,849] Trial 22 finished with value: 7.698124408721924 and parameters: {'hidden_size': 128, 'lr': 0.006022416756995893, 'batch_size': 64, 'weight_decay': 0.00013051812333750697, 'dropout': 0.2936458092269838, 'huber_delta': 1.3913078924032216}. Best is trial 21 with value: 7.696168422698975.
[I 2026-05-28 00:37:23,105] Trial 23 finished with value: 7.699404239654541 and parameters: {'hidden_size': 128, 'lr': 0.006501184821651436, 'batch_size': 16, 'weight_decay': 0.0001228485719513142, 'dropout': 0.30529068414227517, 'huber_delta': 1.8274078535967835}. Best is trial 21 with value: 7.696168422698975.
[I 2026-05-28 00:37:43,524] Trial 24 finished with value: 7.709285736083984 and parameters: {'hidden_size': 128, 'lr': 0.003172005173466601, 'batch_size': 64, 'weight_decay': 0.00022932008850219546, 'dropout': 0.3769117505691279, 'huber_delta': 1.441458500914547}. Best is trial 21 with value: 7.696168422698975.
[I 2026-05-28 00:37:58,205] Trial 25 finished with value: 7.707330703735352 and parameters: {'hidden_size': 128, 'lr': 0.00128897503021555, 'batch_size': 32, 'weight_decay': 3.793437035821641e-05, 'dropout': 0.2720335510019694, 'huber_delta': 1.6219173849020618}. Best is trial 21 with value: 7.696168422698975.
[I 2026-05-28 00:38:19,039] Trial 26 finished with value: 7.7100677490234375 and parameters: {'hidden_size': 128, 'lr': 0.001941844201489425, 'batch_size': 64, 'weight_decay': 8.782672275858086e-05, 'dropout': 0.30556757342573915, 'huber_delta': 1.8207993566596754}. Best is trial 21 with value: 7.696168422698975.
[I 2026-05-28 00:38:33,823] Trial 27 finished with value: 7.704077243804932 and parameters: {'hidden_size': 128, 'lr': 0.006788452118845559, 'batch_size': 64, 'weight_decay': 0.000272755416639121, 'dropout': 0.3644432893728913, 'huber_delta': 1.4598952215875673}. Best is trial 21 with value: 7.696168422698975.
[I 2026-05-28 00:39:15,391] Trial 28 finished with value: 7.7070488929748535 and parameters: {'hidden_size': 128, 'lr': 0.0005238708629548672, 'batch_size': 16, 'weight_decay': 0.0009666080365834436, 'dropout': 0.22909284966582227, 'huber_delta': 1.8900259944652533}. Best is trial 21 with value: 7.696168422698975.
[I 2026-05-28 00:39:35,438] Trial 29 finished with value: 7.701948642730713 and parameters: {'hidden_size': 128, 'lr': 0.003367583573025126, 'batch_size': 32, 'weight_decay': 3.9952213207586724e-05, 'dropout': 0.41080166802644025, 'huber_delta': 1.7237583268517935}. Best is trial 21 with value: 7.696168422698975.
[I 2026-05-28 00:39:53,692] Trial 30 finished with value: 7.702194690704346 and parameters: {'hidden_size': 128, 'lr': 0.0022986041810690878, 'batch_size': 32, 'weight_decay': 8.823326894468994e-05, 'dropout': 0.3185205125489165, 'huber_delta': 1.6611946113839957}. Best is trial 21 with value: 7.696168422698975.
[I 2026-05-28 00:40:17,519] Trial 31 finished with value: 7.702396392822266 and parameters: {'hidden_size': 64, 'lr': 0.005188987608815209, 'batch_size': 64, 'weight_decay': 0.0001459450704774261, 'dropout': 0.2619478847315494, 'huber_delta': 1.337053390611094}. Best is trial 21 with value: 7.696168422698975.
[I 2026-05-28 00:40:30,296] Trial 32 finished with value: 7.7048659324646 and parameters: {'hidden_size': 32, 'lr': 0.009594069854985588, 'batch_size': 64, 'weight_decay': 2.464445537850126e-05, 'dropout': 0.23119634542774645, 'huber_delta': 1.2341358169284835}. Best is trial 21 with value: 7.696168422698975.
[I 2026-05-28 00:40:39,811] Trial 33 finished with value: 7.697011947631836 and parameters: {'hidden_size': 128, 'lr': 0.005809582608838003, 'batch_size': 64, 'weight_decay': 0.0002969470246217394, 'dropout': 0.2898630160323348, 'huber_delta': 1.5074958247802188}. Best is trial 21 with value: 7.696168422698975.
[I 2026-05-28 00:40:48,584] Trial 34 finished with value: 7.696758270263672 and parameters: {'hidden_size': 128, 'lr': 0.006812040033068851, 'batch_size': 64, 'weight_decay': 0.0004097536620897876, 'dropout': 0.35135496839941327, 'huber_delta': 1.5462478113494444}. Best is trial 21 with value: 7.696168422698975.
[I 2026-05-28 00:41:00,449] Trial 35 finished with value: 7.703784465789795 and parameters: {'hidden_size': 128, 'lr': 0.006829570051845327, 'batch_size': 64, 'weight_decay': 0.00035520747399606973, 'dropout': 0.35269157423276826, 'huber_delta': 1.4052147847197476}. Best is trial 21 with value: 7.696168422698975.
[I 2026-05-28 00:41:10,648] Trial 36 finished with value: 7.699123382568359 and parameters: {'hidden_size': 128, 'lr': 0.0012091459612201564, 'batch_size': 64, 'weight_decay': 0.0005825826301119685, 'dropout': 0.3469571967053927, 'huber_delta': 1.51655169053109}. Best is trial 21 with value: 7.696168422698975.
[I 2026-05-28 00:41:21,905] Trial 37 pruned.
[I 2026-05-28 00:41:36,177] Trial 38 finished with value: 7.706385135650635 and parameters: {'hidden_size': 128, 'lr': 0.008212365317992697, 'batch_size': 64, 'weight_decay': 6.325234928440854e-05, 'dropout': 0.4231780387626444, 'huber_delta': 1.6116816856677523}. Best is trial 21 with value: 7.696168422698975.
[I 2026-05-28 00:41:48,048] Trial 39 finished with value: 7.696974277496338 and parameters: {'hidden_size': 128, 'lr': 0.002345457649516462, 'batch_size': 64, 'weight_decay': 0.0004962223521313837, 'dropout': 0.3161708249266759, 'huber_delta': 1.751243667712696}. Best is trial 21 with value: 7.696168422698975.
[I 2026-05-28 00:41:58,747] Trial 40 finished with value: 7.749372959136963 and parameters: {'hidden_size': 32, 'lr': 0.0008839104697808364, 'batch_size': 64, 'weight_decay': 0.0005271651827276721, 'dropout': 0.31423636678836014, 'huber_delta': 1.7731899155572903}. Best is trial 21 with value: 7.696168422698975.
[I 2026-05-28 00:42:12,259] Trial 41 finished with value: 7.702091693878174 and parameters: {'hidden_size': 128, 'lr': 0.0022613378987477602, 'batch_size': 64, 'weight_decay': 0.00032335770368161127, 'dropout': 0.3388526054324311, 'huber_delta': 1.5217715845439668}. Best is trial 21 with value: 7.696168422698975.
[I 2026-05-28 00:42:24,251] Trial 42 finished with value: 7.698450088500977 and parameters: {'hidden_size': 128, 'lr': 0.003750563872948288, 'batch_size': 64, 'weight_decay': 0.0001809813043630123, 'dropout': 0.32419781042733303, 'huber_delta': 1.88920882293891}. Best is trial 21 with value: 7.696168422698975.
[I 2026-05-28 00:42:37,076] Trial 43 finished with value: 7.698940277099609 and parameters: {'hidden_size': 128, 'lr': 0.005591433582385244, 'batch_size': 64, 'weight_decay': 0.00047990595545461363, 'dropout': 0.2966439303226854, 'huber_delta': 1.9116225050577074}. Best is trial 21 with value: 7.696168422698975.
[I 2026-05-28 00:42:49,782] Trial 44 pruned.
[I 2026-05-28 00:43:11,726] Trial 45 finished with value: 7.700403690338135 and parameters: {'hidden_size': 128, 'lr': 0.0026463001758355712, 'batch_size': 16, 'weight_decay': 0.0007192544138776884, 'dropout': 0.33542537964400027, 'huber_delta': 1.9985480294347453}. Best is trial 21 with value: 7.696168422698975.
[I 2026-05-28 00:43:31,105] Trial 46 finished with value: 7.701974868774414 and parameters: {'hidden_size': 128, 'lr': 0.006014252128010119, 'batch_size': 64, 'weight_decay': 0.00021307130804713975, 'dropout': 0.2808849644401995, 'huber_delta': 1.675693525940635}. Best is trial 21 with value: 7.696168422698975.
[I 2026-05-28 00:43:50,435] Trial 47 finished with value: 7.707258701324463 and parameters: {'hidden_size': 128, 'lr': 0.003823562488546553, 'batch_size': 64, 'weight_decay': 0.0003109519572638402, 'dropout': 0.31614591707569567, 'huber_delta': 1.250780741562961}. Best is trial 21 with value: 7.696168422698975.
[I 2026-05-28 00:44:07,289] Trial 48 finished with value: 7.701521396636963 and parameters: {'hidden_size': 128, 'lr': 0.001997777777311908, 'batch_size': 64, 'weight_decay': 0.00016051102786022794, 'dropout': 0.48968871163077976, 'huber_delta': 1.3832109067641647}. Best is trial 21 with value: 7.696168422698975.
[I 2026-05-28 00:44:25,126] Trial 49 finished with value: 7.704888820648193 and parameters: {'hidden_size': 32, 'lr': 0.008415289470193618, 'batch_size': 64, 'weight_decay': 0.0004288905832798934, 'dropout': 0.26449197317666157, 'huber_delta': 1.4921414330270635}. Best is trial 21 with value: 7.696168422698975.
[I 2026-05-28 00:44:41,970] Trial 50 finished with value: 7.703843593597412 and parameters: {'hidden_size': 128, 'lr': 0.004206888740105317, 'batch_size': 64, 'weight_decay': 0.0006944711238172826, 'dropout': 0.2925865803974816, 'huber_delta': 1.5818312700620474}. Best is trial 21 with value: 7.696168422698975.
[I 2026-05-28 00:44:58,159] Trial 51 finished with value: 7.7009758949279785 and parameters: {'hidden_size': 128, 'lr': 0.0035254078448917073, 'batch_size': 64, 'weight_decay': 0.0001749865498874614, 'dropout': 0.32600528309744153, 'huber_delta': 1.8893851421199805}. Best is trial 21 with value: 7.696168422698975.
[I 2026-05-28 00:45:09,480] Trial 52 finished with value: 7.707258701324463 and parameters: {'hidden_size': 128, 'lr': 0.0026732589026745826, 'batch_size': 64, 'weight_decay': 0.0002547184267107443, 'dropout': 0.3073958939102629, 'huber_delta': 1.8579016765154155}. Best is trial 21 with value: 7.696168422698975.
[I 2026-05-28 00:45:19,808] Trial 53 finished with value: 7.699977874755859 and parameters: {'hidden_size': 128, 'lr': 0.004804451113795154, 'batch_size': 64, 'weight_decay': 0.000119434356728793, 'dropout': 0.327289756019637, 'huber_delta': 1.940402114189588}. Best is trial 21 with value: 7.696168422698975.
[I 2026-05-28 00:45:40,730] Trial 54 finished with value: 7.704673767089844 and parameters: {'hidden_size': 128, 'lr': 0.0037702279075534978, 'batch_size': 64, 'weight_decay': 5.165141946926804e-05, 'dropout': 0.3469345465363365, 'huber_delta': 1.6457858235227134}. Best is trial 21 with value: 7.696168422698975.
[I 2026-05-28 00:46:10,486] Trial 55 finished with value: 7.702897548675537 and parameters: {'hidden_size': 128, 'lr': 0.005852062188450254, 'batch_size': 16, 'weight_decay': 0.00035519094791265995, 'dropout': 0.2724552588841976, 'huber_delta': 1.7780799909256944}. Best is trial 21 with value: 7.696168422698975.
[I 2026-05-28 00:46:27,282] Trial 56 finished with value: 7.697971343994141 and parameters: {'hidden_size': 128, 'lr': 0.0030205944912056197, 'batch_size': 64, 'weight_decay': 0.0001849310698344003, 'dropout': 0.37157990676868735, 'huber_delta': 1.9430629917605664}. Best is trial 21 with value: 7.696168422698975.
[I 2026-05-28 00:46:40,354] Trial 57 pruned.
[I 2026-05-28 00:46:50,740] Trial 58 finished with value: 7.7133355140686035 and parameters: {'hidden_size': 128, 'lr': 0.0010482632751555477, 'batch_size': 64, 'weight_decay': 0.00020487741563920817, 'dropout': 0.3971620596361368, 'huber_delta': 1.4193174157361197}. Best is trial 21 with value: 7.696168422698975.
[I 2026-05-28 00:47:04,656] Trial 59 finished with value: 7.707405090332031 and parameters: {'hidden_size': 64, 'lr': 0.0016807924065835823, 'batch_size': 64, 'weight_decay': 7.543856839477098e-05, 'dropout': 0.38548814139894044, 'huber_delta': 1.341031695927555}. Best is trial 21 with value: 7.696168422698975.
[I 2026-05-28 00:47:15,926] Trial 60 finished with value: 7.701639175415039 and parameters: {'hidden_size': 128, 'lr': 0.0030169220551685455, 'batch_size': 64, 'weight_decay': 0.0003858550907125997, 'dropout': 0.3614083012297783, 'huber_delta': 1.7100832278028135}. Best is trial 21 with value: 7.696168422698975.
[I 2026-05-28 00:47:30,693] Trial 61 finished with value: 7.700950622558594 and parameters: {'hidden_size': 128, 'lr': 0.007480518487870702, 'batch_size': 64, 'weight_decay': 0.00016952822261906205, 'dropout': 0.3392577066281709, 'huber_delta': 1.8596439284852582}. Best is trial 21 with value: 7.696168422698975.
[I 2026-05-28 00:47:40,178] Trial 62 finished with value: 7.699272632598877 and parameters: {'hidden_size': 128, 'lr': 0.004471401306936276, 'batch_size': 64, 'weight_decay': 0.00019228045215453955, 'dropout': 0.3227056132529559, 'huber_delta': 1.922078241002706}. Best is trial 21 with value: 7.696168422698975.
[I 2026-05-28 00:47:54,653] Trial 63 finished with value: 7.701374053955078 and parameters: {'hidden_size': 128, 'lr': 0.0020994572224133498, 'batch_size': 64, 'weight_decay': 0.00024247582534473337, 'dropout': 0.3008382755804997, 'huber_delta': 1.8244005415932099}. Best is trial 21 with value: 7.696168422698975.
[I 2026-05-28 00:48:05,890] Trial 64 finished with value: 7.703131198883057 and parameters: {'hidden_size': 128, 'lr': 0.003041655129342104, 'batch_size': 64, 'weight_decay': 0.00013636880037580547, 'dropout': 0.35138981617920706, 'huber_delta': 1.9796564021423435}. Best is trial 21 with value: 7.696168422698975.
[I 2026-05-28 00:48:51,683] Trial 65 finished with value: 7.7033257484436035 and parameters: {'hidden_size': 128, 'lr': 0.009818488585481474, 'batch_size': 16, 'weight_decay': 0.0002841148768207908, 'dropout': 0.31183271791202744, 'huber_delta': 1.8829145738366704}. Best is trial 21 with value: 7.696168422698975.
[I 2026-05-28 00:49:04,750] Trial 66 finished with value: 7.704492092132568 and parameters: {'hidden_size': 128, 'lr': 0.002651244900874697, 'batch_size': 64, 'weight_decay': 0.0007682294842895161, 'dropout': 0.37127084504482644, 'huber_delta': 1.2858286039371662}. Best is trial 21 with value: 7.696168422698975.
[I 2026-05-28 00:49:19,887] Trial 67 finished with value: 7.705769062042236 and parameters: {'hidden_size': 32, 'lr': 0.004793745243317287, 'batch_size': 64, 'weight_decay': 7.006163444892634e-05, 'dropout': 0.334694855557071, 'huber_delta': 1.5552902740354169}. Best is trial 21 with value: 7.696168422698975.

[HUBER - MTL Base] Best Avg Val Metric (minimize): 7.6960
 Best Params: {'hidden_size': 128, 'lr': 0.003673569654223351, 'batch_size': 16, 'weight_decay': 0.00021943085674158504, 'dropout': 0.3440568739399561, 'huber_delta': 1.4380843861038661}

## Improved MTL

In [ ]:
print("Improved MTL (Comparing Losses)")
best_mtl_imp = {}
for l_type in ['l1', 'mse', 'huber']:
    print(f"\nEvaluating Improved with '{l_type}' Loss...")
    pruner = optuna.pruners.MedianPruner(n_startup_trials=10, n_warmup_steps=15)
    study = optuna.create_study(direction="minimize", study_name=f"mtl_imp_{l_type}", pruner=pruner)
    study.optimize(get_hpo_objective(True, loss_type=l_type), n_trials=OPTUNA_TRIALS)
    best_mtl_imp[l_type] = study.best_trial.params
    print(f"[{l_type.upper()} - MTL Imp] Best Avg Val Metric (minimize): {study.best_value:.4f}")
    print(f" Best Params: {study.best_trial.params}")

[I 2026-05-28 00:57:20,876] A new study created in memory with name: mtl_imp_l1

Improved MTL (Comparing Losses)

Evaluating Improved with 'l1' Loss...

[I 2026-05-28 00:57:58,362] Trial 0 finished with value: 7.71516752243042 and parameters: {'hidden_size': 32, 'lr': 0.004511643533921293, 'batch_size': 16, 'weight_decay': 8.6585951257992e-06, 'dropout': 0.22385233887278816}. Best is trial 0 with value: 7.71516752243042.
[I 2026-05-28 00:58:51,539] Trial 1 finished with value: 7.7181243896484375 and parameters: {'hidden_size': 64, 'lr': 0.00017536326793130677, 'batch_size': 64, 'weight_decay': 2.0939538402178845e-05, 'dropout': 0.4171503485702226}. Best is trial 0 with value: 7.71516752243042.
[I 2026-05-28 00:59:29,181] Trial 2 finished with value: 7.717634677886963 and parameters: {'hidden_size': 128, 'lr': 0.00017921994721543407, 'batch_size': 64, 'weight_decay': 0.0001801048113560405, 'dropout': 0.2889659728898096}. Best is trial 0 with value: 7.71516752243042.
[I 2026-05-28 00:59:54,687] Trial 3 finished with value: 7.701570987701416 and parameters: {'hidden_size': 64, 'lr': 0.001681667100098799, 'batch_size': 32, 'weight_decay': 1.990583798037526e-06, 'dropout': 0.3779728780159408}. Best is trial 3 with value: 7.701570987701416.
[I 2026-05-28 01:00:29,328] Trial 4 finished with value: 7.705780029296875 and parameters: {'hidden_size': 64, 'lr': 0.0005555643858380332, 'batch_size': 16, 'weight_decay': 8.141398044952285e-06, 'dropout': 0.2124480577023377}. Best is trial 3 with value: 7.701570987701416.
[I 2026-05-28 01:01:20,077] Trial 5 finished with value: 7.736819744110107 and parameters: {'hidden_size': 128, 'lr': 0.0001276200343018892, 'batch_size': 32, 'weight_decay': 0.0005603859059387943, 'dropout': 0.43888154341125274}. Best is trial 3 with value: 7.701570987701416.
[I 2026-05-28 01:01:45,972] Trial 6 finished with value: 7.702585697174072 and parameters: {'hidden_size': 128, 'lr': 0.0009390016344655724, 'batch_size': 32, 'weight_decay': 3.1954222534111384e-05, 'dropout': 0.33449292241600304}. Best is trial 3 with value: 7.701570987701416.
[I 2026-05-28 01:02:34,604] Trial 7 finished with value: 7.726785182952881 and parameters: {'hidden_size': 32, 'lr': 0.00030225555028111714, 'batch_size': 16, 'weight_decay': 1.692766071559884e-05, 'dropout': 0.32937275200378413}. Best is trial 3 with value: 7.701570987701416.
[I 2026-05-28 01:03:31,135] Trial 8 finished with value: 7.735440731048584 and parameters: {'hidden_size': 64, 'lr': 0.00015359188171337035, 'batch_size': 32, 'weight_decay': 1.0866901105775376e-05, 'dropout': 0.4200727436287335}. Best is trial 3 with value: 7.701570987701416.
[I 2026-05-28 01:03:46,352] Trial 9 finished with value: 7.715157985687256 and parameters: {'hidden_size': 64, 'lr': 0.005457506454003968, 'batch_size': 64, 'weight_decay': 3.322850376674847e-05, 'dropout': 0.255764376122656}. Best is trial 3 with value: 7.701570987701416.
[I 2026-05-28 01:04:12,051] Trial 10 finished with value: 7.7097344398498535 and parameters: {'hidden_size': 64, 'lr': 0.0023544698393793717, 'batch_size': 32, 'weight_decay': 1.622027733483053e-06, 'dropout': 0.48331836105883685}. Best is trial 3 with value: 7.701570987701416.
[I 2026-05-28 01:04:34,288] Trial 11 finished with value: 7.70529317855835 and parameters: {'hidden_size': 128, 'lr': 0.0013272756449708527, 'batch_size': 32, 'weight_decay': 1.367771633659127e-06, 'dropout': 0.36656209686890145}. Best is trial 3 with value: 7.701570987701416.
[I 2026-05-28 01:04:51,728] Trial 12 finished with value: 7.718957424163818 and parameters: {'hidden_size': 128, 'lr': 0.00098986122572417, 'batch_size': 32, 'weight_decay': 8.347912697415061e-05, 'dropout': 0.35203013855057336}. Best is trial 3 with value: 7.701570987701416.
[I 2026-05-28 01:05:11,616] Trial 13 finished with value: 7.696796894073486 and parameters: {'hidden_size': 128, 'lr': 0.002364324434947831, 'batch_size': 32, 'weight_decay': 2.9616029030610044e-06, 'dropout': 0.3080521493220461}. Best is trial 13 with value: 7.696796894073486.
[I 2026-05-28 01:05:26,347] Trial 14 finished with value: 7.709837436676025 and parameters: {'hidden_size': 32, 'lr': 0.009062345293954544, 'batch_size': 32, 'weight_decay': 3.2372438691916974e-06, 'dropout': 0.2851667888852565}. Best is trial 13 with value: 7.696796894073486.
[I 2026-05-28 01:05:52,386] Trial 15 finished with value: 7.700850009918213 and parameters: {'hidden_size': 64, 'lr': 0.002297417078149162, 'batch_size': 32, 'weight_decay': 3.4968871767518214e-06, 'dropout': 0.38378201758878316}. Best is trial 13 with value: 7.696796894073486.
[I 2026-05-28 01:06:12,180] Trial 16 finished with value: 7.6990814208984375 and parameters: {'hidden_size': 128, 'lr': 0.0029613375893711084, 'batch_size': 32, 'weight_decay': 4.186821161888354e-06, 'dropout': 0.3181158635435298}. Best is trial 13 with value: 7.696796894073486.
[I 2026-05-28 01:06:38,046] Trial 17 finished with value: 7.70167875289917 and parameters: {'hidden_size': 128, 'lr': 0.005619820865632057, 'batch_size': 32, 'weight_decay': 4.672371792608963e-06, 'dropout': 0.300520109596949}. Best is trial 13 with value: 7.696796894073486.
[I 2026-05-28 01:07:12,605] Trial 18 finished with value: 7.706195831298828 and parameters: {'hidden_size': 128, 'lr': 0.0031484689526000754, 'batch_size': 16, 'weight_decay': 1.1398570551227375e-06, 'dropout': 0.25097957616077693}. Best is trial 13 with value: 7.696796894073486.
[I 2026-05-28 01:07:29,615] Trial 19 finished with value: 7.709104061126709 and parameters: {'hidden_size': 128, 'lr': 0.0006091566902176226, 'batch_size': 64, 'weight_decay': 5.529919665206214e-06, 'dropout': 0.3136649386199454}. Best is trial 13 with value: 7.696796894073486.
[I 2026-05-28 01:07:54,723] Trial 20 finished with value: 7.701904296875 and parameters: {'hidden_size': 128, 'lr': 0.003392878044176448, 'batch_size': 32, 'weight_decay': 6.101864955608011e-05, 'dropout': 0.26227831906386345}. Best is trial 13 with value: 7.696796894073486.
[I 2026-05-28 01:08:20,954] Trial 21 finished with value: 7.706654071807861 and parameters: {'hidden_size': 128, 'lr': 0.001968795504303094, 'batch_size': 32, 'weight_decay': 2.9846331756909683e-06, 'dropout': 0.3832297090332875}. Best is trial 13 with value: 7.696796894073486.
[I 2026-05-28 01:08:37,862] Trial 22 pruned.
[I 2026-05-28 01:08:54,193] Trial 23 pruned.
[I 2026-05-28 01:09:09,973] Trial 24 finished with value: 7.703559875488281 and parameters: {'hidden_size': 128, 'lr': 0.00696289084959049, 'batch_size': 32, 'weight_decay': 5.267725233690074e-06, 'dropout': 0.31750997713832985}. Best is trial 13 with value: 7.696796894073486.
[I 2026-05-28 01:09:30,169] Trial 25 finished with value: 7.707723140716553 and parameters: {'hidden_size': 64, 'lr': 0.00414753283632246, 'batch_size': 32, 'weight_decay': 2.855793672588508e-06, 'dropout': 0.46013509078312154}. Best is trial 13 with value: 7.696796894073486.
[I 2026-05-28 01:09:59,438] Trial 26 finished with value: 7.707337856292725 and parameters: {'hidden_size': 128, 'lr': 0.0006611087513900806, 'batch_size': 32, 'weight_decay': 5.626088752370244e-06, 'dropout': 0.2787378701512806}. Best is trial 13 with value: 7.696796894073486.
[I 2026-05-28 01:10:22,028] Trial 27 finished with value: 7.701467990875244 and parameters: {'hidden_size': 128, 'lr': 0.0016274106432441818, 'batch_size': 32, 'weight_decay': 1.1930826076974312e-06, 'dropout': 0.4024497499873435}. Best is trial 13 with value: 7.696796894073486.
[I 2026-05-28 01:10:35,578] Trial 28 pruned.
[I 2026-05-28 01:10:57,579] Trial 29 pruned.
[I 2026-05-28 01:11:42,489] Trial 30 finished with value: 7.694759368896484 and parameters: {'hidden_size': 32, 'lr': 0.008881312247570829, 'batch_size': 16, 'weight_decay': 1.5757304353191384e-05, 'dropout': 0.3099353981957689}. Best is trial 30 with value: 7.694759368896484.
[I 2026-05-28 01:12:03,604] Trial 31 finished with value: 7.70483922958374 and parameters: {'hidden_size': 32, 'lr': 0.009361491885949034, 'batch_size': 16, 'weight_decay': 1.7291316191533864e-05, 'dropout': 0.3093234966976933}. Best is trial 30 with value: 7.694759368896484.
[I 2026-05-28 01:12:23,737] Trial 32 finished with value: 7.705001354217529 and parameters: {'hidden_size': 32, 'lr': 0.0068717525134017726, 'batch_size': 16, 'weight_decay': 4.571322012700943e-06, 'dropout': 0.3303573817611917}. Best is trial 30 with value: 7.694759368896484.
[I 2026-05-28 01:12:45,392] Trial 33 finished with value: 7.694281101226807 and parameters: {'hidden_size': 32, 'lr': 0.003401507766189891, 'batch_size': 16, 'weight_decay': 7.839968960863435e-06, 'dropout': 0.2723634682240227}. Best is trial 33 with value: 7.694281101226807.
[I 2026-05-28 01:13:35,454] Trial 34 finished with value: 7.703632354736328 and parameters: {'hidden_size': 32, 'lr': 0.0036357096550347703, 'batch_size': 16, 'weight_decay': 2.26162111551239e-05, 'dropout': 0.2737837542111002}. Best is trial 33 with value: 7.694281101226807.
[I 2026-05-28 01:13:52,444] Trial 35 finished with value: 7.708101749420166 and parameters: {'hidden_size': 32, 'lr': 0.00535697431336252, 'batch_size': 16, 'weight_decay': 1.0060975939226577e-05, 'dropout': 0.2378501264486363}. Best is trial 33 with value: 7.694281101226807.
[I 2026-05-28 01:14:22,956] Trial 36 finished with value: 7.706657409667969 and parameters: {'hidden_size': 32, 'lr': 0.007004647637714933, 'batch_size': 16, 'weight_decay': 5.051404135480458e-05, 'dropout': 0.2917254567831008}. Best is trial 33 with value: 7.694281101226807.
[I 2026-05-28 01:14:44,078] Trial 37 pruned.
[I 2026-05-28 01:15:05,472] Trial 38 pruned.
[I 2026-05-28 01:15:19,026] Trial 39 pruned.
[I 2026-05-28 01:15:37,163] Trial 40 finished with value: 7.694700717926025 and parameters: {'hidden_size': 128, 'lr': 0.00447375725732741, 'batch_size': 16, 'weight_decay': 1.381319462517176e-05, 'dropout': 0.2718172192656729}. Best is trial 33 with value: 7.694281101226807.
[I 2026-05-28 01:15:53,612] Trial 41 finished with value: 7.694283962249756 and parameters: {'hidden_size': 128, 'lr': 0.005258229039479628, 'batch_size': 16, 'weight_decay': 1.4772631628577024e-05, 'dropout': 0.27149737530356904}. Best is trial 33 with value: 7.694281101226807.
[I 2026-05-28 01:16:27,987] Trial 42 finished with value: 7.702503204345703 and parameters: {'hidden_size': 128, 'lr': 0.004906194260447628, 'batch_size': 16, 'weight_decay': 2.3348999445726782e-05, 'dropout': 0.2671299355193759}. Best is trial 33 with value: 7.694281101226807.
[I 2026-05-28 01:16:49,680] Trial 43 pruned.
[I 2026-05-28 01:17:17,264] Trial 44 finished with value: 7.701438903808594 and parameters: {'hidden_size': 128, 'lr': 0.004140749286040369, 'batch_size': 16, 'weight_decay': 3.00268218076727e-05, 'dropout': 0.250017866241194}. Best is trial 33 with value: 7.694281101226807.
[I 2026-05-28 01:17:44,366] Trial 45 finished with value: 7.7065911293029785 and parameters: {'hidden_size': 128, 'lr': 0.009739332532766149, 'batch_size': 16, 'weight_decay': 8.270495502179842e-06, 'dropout': 0.23684979652971677}. Best is trial 33 with value: 7.694281101226807.
[I 2026-05-28 01:18:05,891] Trial 46 pruned.
[I 2026-05-28 01:18:26,972] Trial 47 finished with value: 7.695065975189209 and parameters: {'hidden_size': 128, 'lr': 0.004883183736191188, 'batch_size': 16, 'weight_decay': 4.666699206226756e-05, 'dropout': 0.3023893753554627}. Best is trial 33 with value: 7.694281101226807.
[I 2026-05-28 01:18:49,723] Trial 48 finished with value: 7.697898864746094 and parameters: {'hidden_size': 128, 'lr': 0.008434990165589488, 'batch_size': 16, 'weight_decay': 3.8896003332460245e-05, 'dropout': 0.33968024971667893}. Best is trial 33 with value: 7.694281101226807.
[I 2026-05-28 01:19:11,577] Trial 49 pruned.
[I 2026-05-28 01:19:30,693] Trial 50 finished with value: 7.695703983306885 and parameters: {'hidden_size': 128, 'lr': 0.006145307415278822, 'batch_size': 16, 'weight_decay': 0.00011480479409507546, 'dropout': 0.2678738358793645}. Best is trial 33 with value: 7.694281101226807.
[I 2026-05-28 01:19:59,687] Trial 51 finished with value: 7.696542263031006 and parameters: {'hidden_size': 128, 'lr': 0.0057874665313900715, 'batch_size': 16, 'weight_decay': 8.615257485191993e-05, 'dropout': 0.266754349057326}. Best is trial 33 with value: 7.694281101226807.
[I 2026-05-28 01:20:26,503] Trial 52 finished with value: 7.706002712249756 and parameters: {'hidden_size': 128, 'lr': 0.0038283252233491903, 'batch_size': 16, 'weight_decay': 0.00029677994340420735, 'dropout': 0.249793407762248}. Best is trial 33 with value: 7.694281101226807.
[I 2026-05-28 01:21:00,859] Trial 53 finished with value: 7.70325231552124 and parameters: {'hidden_size': 128, 'lr': 0.00765762234582153, 'batch_size': 16, 'weight_decay': 0.0001153332601885453, 'dropout': 0.30230174787764874}. Best is trial 33 with value: 7.694281101226807.
[I 2026-05-28 01:21:21,930] Trial 54 finished with value: 7.704901218414307 and parameters: {'hidden_size': 128, 'lr': 0.004797471515844187, 'batch_size': 16, 'weight_decay': 4.500961045570884e-05, 'dropout': 0.2834865999859923}. Best is trial 33 with value: 7.694281101226807.
[I 2026-05-28 01:21:41,785] Trial 55 finished with value: 7.697503566741943 and parameters: {'hidden_size': 128, 'lr': 0.006169196829108707, 'batch_size': 16, 'weight_decay': 2.70924344210765e-05, 'dropout': 0.2605307508396024}. Best is trial 33 with value: 7.694281101226807.
[I 2026-05-28 01:22:10,235] Trial 56 finished with value: 7.706034183502197 and parameters: {'hidden_size': 128, 'lr': 0.008406784564672547, 'batch_size': 16, 'weight_decay': 0.00033422328716746995, 'dropout': 0.22015865414382094}. Best is trial 33 with value: 7.694281101226807.
[I 2026-05-28 01:22:41,848] Trial 57 finished with value: 7.699846267700195 and parameters: {'hidden_size': 128, 'lr': 0.000789015500001952, 'batch_size': 16, 'weight_decay': 1.93722129093965e-05, 'dropout': 0.3655639039565529}. Best is trial 33 with value: 7.694281101226807.
[I 2026-05-28 01:22:55,480] Trial 58 pruned.
[I 2026-05-28 01:23:14,658] Trial 59 finished with value: 7.701999664306641 and parameters: {'hidden_size': 128, 'lr': 0.00348382909076319, 'batch_size': 16, 'weight_decay': 1.216948283082778e-05, 'dropout': 0.24628253360119834}. Best is trial 33 with value: 7.694281101226807.
[I 2026-05-28 01:23:49,396] Trial 60 finished with value: 7.697157382965088 and parameters: {'hidden_size': 64, 'lr': 0.005261466273330231, 'batch_size': 16, 'weight_decay': 3.8763444465991255e-05, 'dropout': 0.2920902493067171}. Best is trial 33 with value: 7.694281101226807.
[I 2026-05-28 01:24:17,654] Trial 61 finished with value: 7.698362350463867 and parameters: {'hidden_size': 128, 'lr': 0.0061849543526518325, 'batch_size': 16, 'weight_decay': 0.00012606728269074643, 'dropout': 0.26873475843886585}. Best is trial 33 with value: 7.694281101226807.
[I 2026-05-28 01:24:43,309] Trial 62 finished with value: 7.698866367340088 and parameters: {'hidden_size': 128, 'lr': 0.005676846863107619, 'batch_size': 16, 'weight_decay': 9.183007351698295e-05, 'dropout': 0.2595502759811904}. Best is trial 33 with value: 7.694281101226807.
[I 2026-05-28 01:25:13,858] Trial 63 finished with value: 7.698829174041748 and parameters: {'hidden_size': 128, 'lr': 0.0025911453286032067, 'batch_size': 16, 'weight_decay': 7.962114009701562e-05, 'dropout': 0.28353181164588515}. Best is trial 33 with value: 7.694281101226807.
[I 2026-05-28 01:25:39,393] Trial 64 finished with value: 7.697835445404053 and parameters: {'hidden_size': 128, 'lr': 0.0019512997130645483, 'batch_size': 16, 'weight_decay': 6.443901612610989e-06, 'dropout': 0.2288405286656836}. Best is trial 33 with value: 7.694281101226807.
[I 2026-05-28 01:26:00,347] Trial 65 finished with value: 7.69889497756958 and parameters: {'hidden_size': 128, 'lr': 0.004439095040518387, 'batch_size': 16, 'weight_decay': 0.0002649750306198318, 'dropout': 0.30534621392804845}. Best is trial 33 with value: 7.694281101226807.
[I 2026-05-28 01:26:22,714] Trial 66 finished with value: 7.705179214477539 and parameters: {'hidden_size': 128, 'lr': 0.00996864466047116, 'batch_size': 16, 'weight_decay': 5.739345441694439e-05, 'dropout': 0.26721817038118645}. Best is trial 33 with value: 7.694281101226807.
[I 2026-05-28 01:26:41,292] Trial 67 finished with value: 7.703788757324219 and parameters: {'hidden_size': 128, 'lr': 0.003219229952365215, 'batch_size': 64, 'weight_decay': 0.00010871666044290419, 'dropout': 0.32653223632808903}. Best is trial 33 with value: 7.694281101226807.
[I 2026-05-28 01:27:08,119] Trial 68 finished with value: 7.705530643463135 and parameters: {'hidden_size': 32, 'lr': 0.007600542891744708, 'batch_size': 16, 'weight_decay': 0.00023360935417203284, 'dropout': 0.24464104868479322}. Best is trial 33 with value: 7.694281101226807.
[I 2026-05-28 01:27:32,006] Trial 69 finished with value: 7.7067389488220215 and parameters: {'hidden_size': 128, 'lr': 0.006087138264155169, 'batch_size': 16, 'weight_decay': 1.0424674498494027e-05, 'dropout': 0.29816212849749024}. Best is trial 33 with value: 7.694281101226807.
[I 2026-05-28 01:27:53,598] Trial 70 finished with value: 7.703300476074219 and parameters: {'hidden_size': 64, 'lr': 0.003761805478737487, 'batch_size': 16, 'weight_decay': 1.4395449485296379e-05, 'dropout': 0.31341631014701804}. Best is trial 33 with value: 7.694281101226807.
[I 2026-05-28 01:28:18,497] Trial 71 finished with value: 7.7065887451171875 and parameters: {'hidden_size': 128, 'lr': 0.005025034177806589, 'batch_size': 32, 'weight_decay': 1.760175694062872e-06, 'dropout': 0.276218753266318}. Best is trial 33 with value: 7.694281101226807.
[I 2026-05-28 01:28:40,200] Trial 72 pruned.
[I 2026-05-28 01:29:01,451] Trial 73 finished with value: 7.705850124359131 and parameters: {'hidden_size': 128, 'lr': 0.003106030913525974, 'batch_size': 16, 'weight_decay': 3.878769371117568e-06, 'dropout': 0.28743911973520625}. Best is trial 33 with value: 7.694281101226807.
[I 2026-05-28 01:29:30,099] Trial 74 finished with value: 7.7086710929870605 and parameters: {'hidden_size': 32, 'lr': 0.0021092517496826, 'batch_size': 16, 'weight_decay': 2.3487217178693575e-05, 'dropout': 0.31077684382684484}. Best is trial 33 with value: 7.694281101226807.
[I 2026-05-28 01:29:49,592] Trial 75 finished with value: 7.698756694793701 and parameters: {'hidden_size': 128, 'lr': 0.004380446212870471, 'batch_size': 32, 'weight_decay': 7.326513115822794e-06, 'dropout': 0.33458038054189393}. Best is trial 33 with value: 7.694281101226807.
[I 2026-05-28 01:30:05,757] Trial 76 finished with value: 7.69447135925293 and parameters: {'hidden_size': 128, 'lr': 0.008195096539939172, 'batch_size': 64, 'weight_decay': 1.840318294573847e-05, 'dropout': 0.32182914251560213}. Best is trial 33 with value: 7.694281101226807.
[I 2026-05-28 01:30:25,374] Trial 77 finished with value: 7.705908298492432 and parameters: {'hidden_size': 128, 'lr': 0.008638128414994839, 'batch_size': 64, 'weight_decay': 1.853273310033906e-05, 'dropout': 0.2973671649517848}. Best is trial 33 with value: 7.694281101226807.
[I 2026-05-28 01:30:38,872] Trial 78 pruned.
[I 2026-05-28 01:31:02,841] Trial 79 finished with value: 7.698622226715088 and parameters: {'hidden_size': 128, 'lr': 0.005726030774755481, 'batch_size': 64, 'weight_decay': 1.1939942668632842e-05, 'dropout': 0.3167505560961947}. Best is trial 33 with value: 7.694281101226807.
[I 2026-05-28 01:31:16,492] Trial 80 pruned.
[I 2026-05-28 01:31:34,555] Trial 81 finished with value: 7.707517623901367 and parameters: {'hidden_size': 128, 'lr': 0.006904190805401117, 'batch_size': 64, 'weight_decay': 6.362802007814738e-05, 'dropout': 0.3455512598681794}. Best is trial 33 with value: 7.694281101226807.
[I 2026-05-28 01:32:08,687] Trial 82 finished with value: 7.702325344085693 and parameters: {'hidden_size': 128, 'lr': 0.0011324025350244993, 'batch_size': 16, 'weight_decay': 2.6664259305209565e-05, 'dropout': 0.3064378889367861}. Best is trial 33 with value: 7.694281101226807.

[L1 - MTL Imp] Best Avg Val Metric (minimize): 7.6943
 Best Params: {'hidden_size': 32, 'lr': 0.003401507766189891, 'batch_size': 16, 'weight_decay': 7.839968960863435e-06, 'dropout': 0.2723634682240227}

Evaluating Improved with 'mse' Loss...

[I 2026-05-28 01:39:49,247] Trial 0 finished with value: 7.732018947601318 and parameters: {'hidden_size': 32, 'lr': 0.005352079410973245, 'batch_size': 32, 'weight_decay': 2.6071846106065405e-06, 'dropout': 0.27946559844786134}. Best is trial 0 with value: 7.732018947601318.
[I 2026-05-28 01:40:04,485] Trial 1 finished with value: 7.706556797027588 and parameters: {'hidden_size': 128, 'lr': 0.001219385767745531, 'batch_size': 64, 'weight_decay': 0.00016489777912956463, 'dropout': 0.2954822446600905}. Best is trial 1 with value: 7.706556797027588.
[I 2026-05-28 01:40:26,558] Trial 2 finished with value: 7.736567974090576 and parameters: {'hidden_size': 32, 'lr': 0.004193703789948248, 'batch_size': 32, 'weight_decay': 2.448344319703648e-05, 'dropout': 0.2794239544549575}. Best is trial 1 with value: 7.706556797027588.
[I 2026-05-28 01:41:53,507] Trial 3 finished with value: 7.817846775054932 and parameters: {'hidden_size': 32, 'lr': 0.00012715774086285704, 'batch_size': 64, 'weight_decay': 1.318856458921674e-05, 'dropout': 0.31278099589812425}. Best is trial 1 with value: 7.706556797027588.
[I 2026-05-28 01:42:11,949] Trial 4 finished with value: 7.708409786224365 and parameters: {'hidden_size': 32, 'lr': 0.0011919667011385164, 'batch_size': 64, 'weight_decay': 2.695018380540317e-06, 'dropout': 0.4658341511834965}. Best is trial 1 with value: 7.706556797027588.
[I 2026-05-28 01:42:33,841] Trial 5 finished with value: 7.704813480377197 and parameters: {'hidden_size': 128, 'lr': 0.0026108784885632706, 'batch_size': 16, 'weight_decay': 9.92328531440174e-05, 'dropout': 0.33113576673568973}. Best is trial 5 with value: 7.704813480377197.
[I 2026-05-28 01:43:09,784] Trial 6 finished with value: 7.712629795074463 and parameters: {'hidden_size': 128, 'lr': 0.00011558103011727757, 'batch_size': 16, 'weight_decay': 2.483260839016609e-06, 'dropout': 0.3891882205068411}. Best is trial 5 with value: 7.704813480377197.
[I 2026-05-28 01:43:31,966] Trial 7 finished with value: 7.715993881225586 and parameters: {'hidden_size': 128, 'lr': 0.0005496566362781084, 'batch_size': 16, 'weight_decay': 0.0005862297529927411, 'dropout': 0.33302008711474945}. Best is trial 5 with value: 7.704813480377197.
[I 2026-05-28 01:43:52,313] Trial 8 finished with value: 7.720552921295166 and parameters: {'hidden_size': 128, 'lr': 0.0006201561960995522, 'batch_size': 16, 'weight_decay': 3.5679736078071205e-05, 'dropout': 0.24803205671679013}. Best is trial 5 with value: 7.704813480377197.
[I 2026-05-28 01:44:05,190] Trial 9 finished with value: 7.7315826416015625 and parameters: {'hidden_size': 32, 'lr': 0.004701366487969038, 'batch_size': 64, 'weight_decay': 1.646519153569063e-06, 'dropout': 0.2013892273156939}. Best is trial 5 with value: 7.704813480377197.
[I 2026-05-28 01:44:29,513] Trial 10 finished with value: 7.707590579986572 and parameters: {'hidden_size': 64, 'lr': 0.002683248717613276, 'batch_size': 16, 'weight_decay': 0.00013391104543874395, 'dropout': 0.4082401145026921}. Best is trial 5 with value: 7.704813480377197.
[I 2026-05-28 01:44:43,208] Trial 11 finished with value: 7.715086460113525 and parameters: {'hidden_size': 128, 'lr': 0.0015109381108487007, 'batch_size': 64, 'weight_decay': 0.0002674877212066431, 'dropout': 0.3731010252984986}. Best is trial 5 with value: 7.704813480377197.
[I 2026-05-28 01:45:12,765] Trial 12 finished with value: 7.703485488891602 and parameters: {'hidden_size': 128, 'lr': 0.0019792647894836648, 'batch_size': 16, 'weight_decay': 9.279874793695262e-05, 'dropout': 0.3329388318855199}. Best is trial 12 with value: 7.703485488891602.
[I 2026-05-28 01:45:47,426] Trial 13 finished with value: 7.699268341064453 and parameters: {'hidden_size': 64, 'lr': 0.00889668961934547, 'batch_size': 16, 'weight_decay': 7.182815239686522e-05, 'dropout': 0.4306898793050573}. Best is trial 13 with value: 7.699268341064453.
[I 2026-05-28 01:46:15,979] Trial 14 finished with value: 7.700279235839844 and parameters: {'hidden_size': 64, 'lr': 0.008167216231415106, 'batch_size': 16, 'weight_decay': 4.711222700926407e-05, 'dropout': 0.450881385028571}. Best is trial 13 with value: 7.699268341064453.
[I 2026-05-28 01:46:37,615] Trial 15 finished with value: 7.707810878753662 and parameters: {'hidden_size': 64, 'lr': 0.007090981552507069, 'batch_size': 16, 'weight_decay': 1.2104680766285101e-05, 'dropout': 0.4970522313732555}. Best is trial 13 with value: 7.699268341064453.
[I 2026-05-28 01:47:01,244] Trial 16 finished with value: 7.698031902313232 and parameters: {'hidden_size': 64, 'lr': 0.008651399868251022, 'batch_size': 32, 'weight_decay': 3.833781121839795e-05, 'dropout': 0.43726097580387757}. Best is trial 16 with value: 7.698031902313232.
[I 2026-05-28 01:47:18,880] Trial 17 finished with value: 7.695680141448975 and parameters: {'hidden_size': 64, 'lr': 0.009207915461483952, 'batch_size': 32, 'weight_decay': 1.0733679495225507e-05, 'dropout': 0.427154825800615}. Best is trial 17 with value: 7.695680141448975.
[I 2026-05-28 01:47:35,399] Trial 18 pruned.
[I 2026-05-28 01:47:52,524] Trial 19 finished with value: 7.701181888580322 and parameters: {'hidden_size': 64, 'lr': 0.003528070320520143, 'batch_size': 32, 'weight_decay': 6.4716878036307525e-06, 'dropout': 0.42028155463538636}. Best is trial 17 with value: 7.695680141448975.
[I 2026-05-28 01:48:15,291] Trial 20 finished with value: 7.712509632110596 and parameters: {'hidden_size': 64, 'lr': 0.009015809126586729, 'batch_size': 32, 'weight_decay': 1.718667055509203e-05, 'dropout': 0.3700678590161228}. Best is trial 17 with value: 7.695680141448975.
[I 2026-05-28 01:48:30,655] Trial 21 finished with value: 7.710151672363281 and parameters: {'hidden_size': 64, 'lr': 0.009267810696824386, 'batch_size': 32, 'weight_decay': 5.151597779085579e-05, 'dropout': 0.4431431249169201}. Best is trial 17 with value: 7.695680141448975.
[I 2026-05-28 01:48:47,081] Trial 22 finished with value: 7.707785129547119 and parameters: {'hidden_size': 64, 'lr': 0.005762323155641034, 'batch_size': 32, 'weight_decay': 6.848154651391183e-05, 'dropout': 0.42150514023788377}. Best is trial 17 with value: 7.695680141448975.
[I 2026-05-28 01:49:12,662] Trial 23 finished with value: 7.699283599853516 and parameters: {'hidden_size': 64, 'lr': 0.009908342900611898, 'batch_size': 32, 'weight_decay': 7.3152188359159845e-06, 'dropout': 0.4698194795310082}. Best is trial 17 with value: 7.695680141448975.
[I 2026-05-28 01:49:29,634] Trial 24 pruned.
[I 2026-05-28 01:49:44,000] Trial 25 finished with value: 7.704387664794922 and parameters: {'hidden_size': 64, 'lr': 0.005916933094842027, 'batch_size': 32, 'weight_decay': 3.116452288275134e-05, 'dropout': 0.3986440156933013}. Best is trial 17 with value: 7.695680141448975.
[I 2026-05-28 01:49:56,211] Trial 26 finished with value: 7.699456691741943 and parameters: {'hidden_size': 64, 'lr': 0.006814128124056339, 'batch_size': 32, 'weight_decay': 2.3162475590267383e-05, 'dropout': 0.3672077150621913}. Best is trial 17 with value: 7.695680141448975.
[I 2026-05-28 01:50:21,661] Trial 27 finished with value: 7.706594944000244 and parameters: {'hidden_size': 64, 'lr': 0.0007176869451680243, 'batch_size': 32, 'weight_decay': 0.0007382274462650191, 'dropout': 0.47391924710230393}. Best is trial 17 with value: 7.695680141448975.
[I 2026-05-28 01:50:42,337] Trial 28 finished with value: 7.710281848907471 and parameters: {'hidden_size': 64, 'lr': 0.0018962150853719885, 'batch_size': 32, 'weight_decay': 4.49386666188277e-06, 'dropout': 0.4306238439161633}. Best is trial 17 with value: 7.695680141448975.
[I 2026-05-28 01:51:11,380] Trial 29 finished with value: 7.704427242279053 and parameters: {'hidden_size': 64, 'lr': 0.004606703679285023, 'batch_size': 16, 'weight_decay': 1.659733700952926e-05, 'dropout': 0.39420033808501187}. Best is trial 17 with value: 7.695680141448975.
[I 2026-05-28 01:51:36,647] Trial 30 finished with value: 7.706301212310791 and parameters: {'hidden_size': 64, 'lr': 0.005893584705783239, 'batch_size': 32, 'weight_decay': 0.00022142974307560304, 'dropout': 0.4557876808692573}. Best is trial 17 with value: 7.695680141448975.
[I 2026-05-28 01:51:52,071] Trial 31 finished with value: 7.708089351654053 and parameters: {'hidden_size': 64, 'lr': 0.009789330878365069, 'batch_size': 32, 'weight_decay': 7.853288271715837e-06, 'dropout': 0.47871411035960765}. Best is trial 17 with value: 7.695680141448975.
[I 2026-05-28 01:52:15,740] Trial 32 finished with value: 7.704326629638672 and parameters: {'hidden_size': 64, 'lr': 0.007441359798580541, 'batch_size': 32, 'weight_decay': 4.326852865362638e-06, 'dropout': 0.4772596384943163}. Best is trial 17 with value: 7.695680141448975.
[I 2026-05-28 01:52:34,342] Trial 33 finished with value: 7.7088775634765625 and parameters: {'hidden_size': 64, 'lr': 0.009809948268350455, 'batch_size': 32, 'weight_decay': 1.2637526600689559e-05, 'dropout': 0.41158420413784563}. Best is trial 17 with value: 7.695680141448975.
[I 2026-05-28 01:52:51,412] Trial 34 finished with value: 7.707772731781006 and parameters: {'hidden_size': 32, 'lr': 0.003937829016061196, 'batch_size': 32, 'weight_decay': 9.109836937426625e-06, 'dropout': 0.4512847235608247}. Best is trial 17 with value: 7.695680141448975.
[I 2026-05-28 01:53:04,613] Trial 35 finished with value: 7.696020603179932 and parameters: {'hidden_size': 64, 'lr': 0.00510481729998387, 'batch_size': 64, 'weight_decay': 2.2578736198861906e-05, 'dropout': 0.4311399123282917}. Best is trial 17 with value: 7.695680141448975.
[I 2026-05-28 01:53:17,354] Trial 36 finished with value: 7.715404510498047 and parameters: {'hidden_size': 32, 'lr': 0.00514273967789949, 'batch_size': 64, 'weight_decay': 2.2753909557019956e-05, 'dropout': 0.43079836723512765}. Best is trial 17 with value: 7.695680141448975.
[I 2026-05-28 01:53:33,288] Trial 37 finished with value: 7.699748992919922 and parameters: {'hidden_size': 64, 'lr': 0.0073636119334053235, 'batch_size': 64, 'weight_decay': 5.6299238051996956e-05, 'dropout': 0.3817137759386174}. Best is trial 17 with value: 7.695680141448975.
[I 2026-05-28 01:53:54,323] Trial 38 finished with value: 7.714232921600342 and parameters: {'hidden_size': 64, 'lr': 0.002945749351661832, 'batch_size': 64, 'weight_decay': 3.557423539127808e-05, 'dropout': 0.40195377470083693}. Best is trial 17 with value: 7.695680141448975.
[I 2026-05-28 01:54:07,949] Trial 39 pruned.
[I 2026-05-28 01:54:21,186] Trial 40 finished with value: 7.713794231414795 and parameters: {'hidden_size': 64, 'lr': 0.0022029230808373788, 'batch_size': 64, 'weight_decay': 8.553014533692444e-05, 'dropout': 0.28895504442907416}. Best is trial 17 with value: 7.695680141448975.
[I 2026-05-28 01:54:46,680] Trial 41 finished with value: 7.703012943267822 and parameters: {'hidden_size': 64, 'lr': 0.006426800965472364, 'batch_size': 16, 'weight_decay': 2.0010582685507435e-05, 'dropout': 0.45603552741186226}. Best is trial 17 with value: 7.695680141448975.
[I 2026-05-28 01:54:59,897] Trial 42 finished with value: 7.702805995941162 and parameters: {'hidden_size': 64, 'lr': 0.004199406773843678, 'batch_size': 64, 'weight_decay': 4.341798285976453e-06, 'dropout': 0.47004434078230745}. Best is trial 17 with value: 7.695680141448975.
[I 2026-05-28 01:55:16,374] Trial 43 finished with value: 7.702515125274658 and parameters: {'hidden_size': 64, 'lr': 0.009873736677455145, 'batch_size': 32, 'weight_decay': 1.0569677504834224e-06, 'dropout': 0.48746577981377465}. Best is trial 17 with value: 7.695680141448975.
[I 2026-05-28 01:55:47,912] Trial 44 finished with value: 7.701961517333984 and parameters: {'hidden_size': 128, 'lr': 0.0076022340052278176, 'batch_size': 16, 'weight_decay': 2.8439372431076423e-05, 'dropout': 0.4622020325828372}. Best is trial 17 with value: 7.695680141448975.
[I 2026-05-28 01:56:04,347] Trial 45 finished with value: 7.707727432250977 and parameters: {'hidden_size': 64, 'lr': 0.004853294256599505, 'batch_size': 64, 'weight_decay': 1.0570145248412695e-05, 'dropout': 0.4190885353234954}. Best is trial 17 with value: 7.695680141448975.
[I 2026-05-28 01:56:37,196] Trial 46 finished with value: 7.703744411468506 and parameters: {'hidden_size': 64, 'lr': 0.008115037286573654, 'batch_size': 16, 'weight_decay': 4.5502735786914875e-05, 'dropout': 0.4341867053463174}. Best is trial 17 with value: 7.695680141448975.
[I 2026-05-28 01:56:59,139] Trial 47 finished with value: 7.701108932495117 and parameters: {'hidden_size': 128, 'lr': 0.005409777463989654, 'batch_size': 32, 'weight_decay': 3.124713720216919e-06, 'dropout': 0.35285588676079727}. Best is trial 17 with value: 7.695680141448975.
[I 2026-05-28 01:57:29,277] Trial 48 finished with value: 7.707773685455322 and parameters: {'hidden_size': 32, 'lr': 0.0010283244228606176, 'batch_size': 16, 'weight_decay': 1.5824408079657363e-05, 'dropout': 0.26545053494613036}. Best is trial 17 with value: 7.695680141448975.
[I 2026-05-28 01:57:44,598] Trial 49 finished with value: 7.701313018798828 and parameters: {'hidden_size': 64, 'lr': 0.004129598394918255, 'batch_size': 32, 'weight_decay': 5.607071966027964e-06, 'dropout': 0.3149119278644127}. Best is trial 17 with value: 7.695680141448975.
[I 2026-05-28 01:57:59,010] Trial 50 pruned.
[I 2026-05-28 01:58:15,153] Trial 51 finished with value: 7.6990180015563965 and parameters: {'hidden_size': 64, 'lr': 0.006694624192707907, 'batch_size': 32, 'weight_decay': 2.4196594427986248e-05, 'dropout': 0.3755035056202361}. Best is trial 17 with value: 7.695680141448975.
[I 2026-05-28 01:58:32,714] Trial 52 finished with value: 7.7024407386779785 and parameters: {'hidden_size': 64, 'lr': 0.008127166993189845, 'batch_size': 32, 'weight_decay': 2.9054544890681387e-05, 'dropout': 0.4134084493160765}. Best is trial 17 with value: 7.695680141448975.
[I 2026-05-28 01:58:50,661] Trial 53 finished with value: 7.69994592666626 and parameters: {'hidden_size': 64, 'lr': 0.006564681630004332, 'batch_size': 32, 'weight_decay': 4.252688111372204e-05, 'dropout': 0.4253327537910979}. Best is trial 17 with value: 7.695680141448975.
[I 2026-05-28 01:59:06,393] Trial 54 finished with value: 7.701484680175781 and parameters: {'hidden_size': 64, 'lr': 0.008211679255992728, 'batch_size': 32, 'weight_decay': 1.3728325777075416e-05, 'dropout': 0.37769058321897253}. Best is trial 17 with value: 7.695680141448975.
[I 2026-05-28 01:59:22,879] Trial 55 pruned.
[I 2026-05-28 01:59:51,327] Trial 56 finished with value: 7.709381103515625 and parameters: {'hidden_size': 128, 'lr': 0.0050451344905977835, 'batch_size': 16, 'weight_decay': 8.010459999321037e-05, 'dropout': 0.38887712045189926}. Best is trial 17 with value: 7.695680141448975.
[I 2026-05-28 02:00:17,183] Trial 57 finished with value: 7.702770233154297 and parameters: {'hidden_size': 64, 'lr': 0.006143155753407023, 'batch_size': 32, 'weight_decay': 0.00011556043614782793, 'dropout': 0.4428243557348369}. Best is trial 17 with value: 7.695680141448975.
[I 2026-05-28 02:00:35,116] Trial 58 finished with value: 7.700080871582031 and parameters: {'hidden_size': 64, 'lr': 0.008894923869788938, 'batch_size': 32, 'weight_decay': 1.9844895421323705e-05, 'dropout': 0.40519999659719486}. Best is trial 17 with value: 7.695680141448975.
[I 2026-05-28 02:00:52,705] Trial 59 finished with value: 7.696746349334717 and parameters: {'hidden_size': 64, 'lr': 0.006556373553168313, 'batch_size': 32, 'weight_decay': 0.0004388811886893708, 'dropout': 0.3580699258018538}. Best is trial 17 with value: 7.695680141448975.
[I 2026-05-28 02:01:41,597] Trial 60 finished with value: 7.709427356719971 and parameters: {'hidden_size': 64, 'lr': 0.00014212495868278825, 'batch_size': 16, 'weight_decay': 0.0005015728625911092, 'dropout': 0.3552633388587548}. Best is trial 17 with value: 7.695680141448975.
[I 2026-05-28 02:01:57,920] Trial 61 finished with value: 7.703268527984619 and parameters: {'hidden_size': 64, 'lr': 0.006757929058256099, 'batch_size': 32, 'weight_decay': 0.000329936741604691, 'dropout': 0.31738112168306676}. Best is trial 17 with value: 7.695680141448975.
[I 2026-05-28 02:02:20,116] Trial 62 finished with value: 7.703813076019287 and parameters: {'hidden_size': 64, 'lr': 0.008322213856064974, 'batch_size': 32, 'weight_decay': 3.8243299945310756e-05, 'dropout': 0.3636933997566735}. Best is trial 17 with value: 7.695680141448975.
[I 2026-05-28 02:02:43,257] Trial 63 finished with value: 7.706529140472412 and parameters: {'hidden_size': 64, 'lr': 0.005510455912966874, 'batch_size': 32, 'weight_decay': 0.00019060993129613147, 'dropout': 0.4648301865304416}. Best is trial 17 with value: 7.695680141448975.
[I 2026-05-28 02:03:07,381] Trial 64 finished with value: 7.70490026473999 and parameters: {'hidden_size': 64, 'lr': 0.009944897140059536, 'batch_size': 32, 'weight_decay': 2.6292292618027656e-05, 'dropout': 0.4851840532863393}. Best is trial 17 with value: 7.695680141448975.
[I 2026-05-28 02:03:24,239] Trial 65 pruned.
[I 2026-05-28 02:03:39,124] Trial 66 finished with value: 7.6949334144592285 and parameters: {'hidden_size': 64, 'lr': 0.006946547027813772, 'batch_size': 32, 'weight_decay': 7.932989470094922e-06, 'dropout': 0.38733988206702374}. Best is trial 66 with value: 7.6949334144592285.
[I 2026-05-28 02:04:00,031] Trial 67 finished with value: 7.705461025238037 and parameters: {'hidden_size': 32, 'lr': 0.004298201354281439, 'batch_size': 32, 'weight_decay': 1.5189476251699415e-05, 'dropout': 0.3883259053322675}. Best is trial 66 with value: 7.6949334144592285.
[I 2026-05-28 02:04:12,685] Trial 68 finished with value: 7.723642826080322 and parameters: {'hidden_size': 64, 'lr': 0.002528471812095161, 'batch_size': 64, 'weight_decay': 1.1708211047104194e-05, 'dropout': 0.3426829362874144}. Best is trial 66 with value: 7.6949334144592285.
[I 2026-05-28 02:04:28,369] Trial 69 finished with value: 7.696104526519775 and parameters: {'hidden_size': 128, 'lr': 0.006886585584700074, 'batch_size': 32, 'weight_decay': 8.425469741939389e-06, 'dropout': 0.36213881142800425}. Best is trial 66 with value: 7.6949334144592285.
[I 2026-05-28 02:04:49,625] Trial 70 finished with value: 7.703772068023682 and parameters: {'hidden_size': 128, 'lr': 0.006847757703546707, 'batch_size': 32, 'weight_decay': 2.097125716181251e-06, 'dropout': 0.36028941956250066}. Best is trial 66 with value: 7.6949334144592285.
[I 2026-05-28 02:05:03,692] Trial 71 finished with value: 7.705171585083008 and parameters: {'hidden_size': 128, 'lr': 0.005728872585695085, 'batch_size': 32, 'weight_decay': 5.7975933842391105e-06, 'dropout': 0.32490275485748904}. Best is trial 66 with value: 7.6949334144592285.
[I 2026-05-28 02:05:20,038] Trial 72 finished with value: 7.698417663574219 and parameters: {'hidden_size': 128, 'lr': 0.007837854365791782, 'batch_size': 32, 'weight_decay': 0.0009675182970735373, 'dropout': 0.37156220418568287}. Best is trial 66 with value: 7.6949334144592285.
[I 2026-05-28 02:05:38,023] Trial 73 finished with value: 7.702062129974365 and parameters: {'hidden_size': 128, 'lr': 0.007428326398681876, 'batch_size': 32, 'weight_decay': 0.0007665085601524039, 'dropout': 0.37666853902004116}. Best is trial 66 with value: 7.6949334144592285.
[I 2026-05-28 02:06:03,529] Trial 74 finished with value: 7.699958324432373 and parameters: {'hidden_size': 128, 'lr': 0.006260661493636545, 'batch_size': 32, 'weight_decay': 0.0006657477722722066, 'dropout': 0.39535113593742527}. Best is trial 66 with value: 7.6949334144592285.
[I 2026-05-28 02:06:18,985] Trial 75 finished with value: 7.699155807495117 and parameters: {'hidden_size': 128, 'lr': 0.004657697254198294, 'batch_size': 32, 'weight_decay': 7.64952161871715e-06, 'dropout': 0.38463823753952897}. Best is trial 66 with value: 7.6949334144592285.

[MSE - MTL Imp] Best Avg Val Metric (minimize): 7.6911
 Best Params: {'hidden_size': 128, 'lr': 0.00873193948799961, 'batch_size': 32, 'weight_decay': 0.000431472809664785, 'dropout': 0.4108777207863841}

Evaluating Improved with 'huber' Loss...

[I 2026-05-28 02:13:06,920] Trial 0 finished with value: 7.733912944793701 and parameters: {'hidden_size': 64, 'lr': 0.0007050345327095489, 'batch_size': 64, 'weight_decay': 9.420521364236271e-05, 'dropout': 0.4651764901679453, 'huber_delta': 0.9518220664728315}. Best is trial 0 with value: 7.733912944793701.
[I 2026-05-28 02:13:29,563] Trial 1 finished with value: 7.701531887054443 and parameters: {'hidden_size': 32, 'lr': 0.009649876940648899, 'batch_size': 32, 'weight_decay': 0.00047195056727470785, 'dropout': 0.2887697959253624, 'huber_delta': 1.6075713926931687}. Best is trial 1 with value: 7.701531887054443.
[I 2026-05-28 02:13:41,125] Trial 2 finished with value: 7.70311164855957 and parameters: {'hidden_size': 64, 'lr': 0.006256921721550774, 'batch_size': 64, 'weight_decay': 1.0383536946577804e-05, 'dropout': 0.3649447577492552, 'huber_delta': 1.5578675126668808}. Best is trial 1 with value: 7.701531887054443.
[I 2026-05-28 02:14:14,254] Trial 3 finished with value: 7.745927333831787 and parameters: {'hidden_size': 128, 'lr': 0.00019109764296379046, 'batch_size': 64, 'weight_decay': 0.00018204902293536933, 'dropout': 0.3372377712035034, 'huber_delta': 1.915098390405853}. Best is trial 1 with value: 7.701531887054443.
[I 2026-05-28 02:14:38,237] Trial 4 finished with value: 7.700300216674805 and parameters: {'hidden_size': 64, 'lr': 0.0008902568369828719, 'batch_size': 16, 'weight_decay': 0.00023268947048200192, 'dropout': 0.31527422863430293, 'huber_delta': 1.5531715000239004}. Best is trial 4 with value: 7.700300216674805.
[I 2026-05-28 02:15:08,928] Trial 5 finished with value: 7.714441776275635 and parameters: {'hidden_size': 64, 'lr': 0.001869231016993769, 'batch_size': 64, 'weight_decay': 0.00024155011242985011, 'dropout': 0.28428390899461614, 'huber_delta': 1.0695296649636237}. Best is trial 4 with value: 7.700300216674805.
[I 2026-05-28 02:15:30,849] Trial 6 finished with value: 7.704057216644287 and parameters: {'hidden_size': 128, 'lr': 0.00023321145273754145, 'batch_size': 32, 'weight_decay': 0.0004415070625760105, 'dropout': 0.24243549635226208, 'huber_delta': 1.8556737778344687}. Best is trial 4 with value: 7.700300216674805.
[I 2026-05-28 02:17:06,575] Trial 7 finished with value: 7.709261417388916 and parameters: {'hidden_size': 64, 'lr': 0.00011863106458020147, 'batch_size': 64, 'weight_decay': 9.210841774866036e-05, 'dropout': 0.349871144830202, 'huber_delta': 1.7442022508180344}. Best is trial 4 with value: 7.700300216674805.
[I 2026-05-28 02:17:44,031] Trial 8 finished with value: 7.717529773712158 and parameters: {'hidden_size': 64, 'lr': 0.00032734876960072607, 'batch_size': 16, 'weight_decay': 6.031705033463654e-06, 'dropout': 0.49283198822106883, 'huber_delta': 1.8899186114894975}. Best is trial 4 with value: 7.700300216674805.
[I 2026-05-28 02:18:41,870] Trial 9 finished with value: 7.714664459228516 and parameters: {'hidden_size': 32, 'lr': 0.00016129286985361218, 'batch_size': 16, 'weight_decay': 2.3649583426673625e-06, 'dropout': 0.4317363419209613, 'huber_delta': 1.7030566172652584}. Best is trial 4 with value: 7.700300216674805.
[I 2026-05-28 02:19:15,482] Trial 10 finished with value: 7.718084335327148 and parameters: {'hidden_size': 32, 'lr': 0.0015059217423000035, 'batch_size': 16, 'weight_decay': 2.8334053909996916e-05, 'dropout': 0.20171029965826953, 'huber_delta': 1.3043266721033762}. Best is trial 4 with value: 7.700300216674805.
[I 2026-05-28 02:19:35,076] Trial 11 finished with value: 7.697579860687256 and parameters: {'hidden_size': 32, 'lr': 0.009773976233539873, 'batch_size': 32, 'weight_decay': 0.000832287726173748, 'dropout': 0.28842915578217193, 'huber_delta': 1.357843440410081}. Best is trial 11 with value: 7.697579860687256.
[I 2026-05-28 02:19:51,131] Trial 12 finished with value: 7.707868576049805 and parameters: {'hidden_size': 32, 'lr': 0.003395521201204448, 'batch_size': 32, 'weight_decay': 0.0007344722649320058, 'dropout': 0.30173505985768334, 'huber_delta': 1.2843301095110913}. Best is trial 11 with value: 7.697579860687256.
[I 2026-05-28 02:20:12,196] Trial 13 pruned.
[I 2026-05-28 02:20:29,523] Trial 14 finished with value: 7.698903560638428 and parameters: {'hidden_size': 128, 'lr': 0.002785969002584983, 'batch_size': 32, 'weight_decay': 0.000979937149163995, 'dropout': 0.30708438414601485, 'huber_delta': 1.1434676138820947}. Best is trial 11 with value: 7.697579860687256.
[I 2026-05-28 02:20:45,133] Trial 15 finished with value: 7.694484710693359 and parameters: {'hidden_size': 128, 'lr': 0.003630039688821443, 'batch_size': 32, 'weight_decay': 0.0009358967363208182, 'dropout': 0.24936789854806946, 'huber_delta': 1.1239691920853145}. Best is trial 15 with value: 7.694484710693359.
[I 2026-05-28 02:20:59,770] Trial 16 finished with value: 7.6991753578186035 and parameters: {'hidden_size': 128, 'lr': 0.004827155164763926, 'batch_size': 32, 'weight_decay': 1.9637374617201167e-05, 'dropout': 0.2481730098179465, 'huber_delta': 0.884728208395321}. Best is trial 15 with value: 7.694484710693359.
[I 2026-05-28 02:21:21,283] Trial 17 finished with value: 7.700125217437744 and parameters: {'hidden_size': 128, 'lr': 0.009920616002878432, 'batch_size': 32, 'weight_decay': 1.1804470283293585e-06, 'dropout': 0.22104043896141556, 'huber_delta': 1.1598993557371502}. Best is trial 15 with value: 7.694484710693359.
[I 2026-05-28 02:21:35,667] Trial 18 finished with value: 7.6968841552734375 and parameters: {'hidden_size': 128, 'lr': 0.0049430001412791936, 'batch_size': 32, 'weight_decay': 0.0004615376712069632, 'dropout': 0.25522857579062785, 'huber_delta': 0.8112841985841714}. Best is trial 15 with value: 7.694484710693359.
[I 2026-05-28 02:21:56,167] Trial 19 finished with value: 7.707286834716797 and parameters: {'hidden_size': 128, 'lr': 0.001626894694366213, 'batch_size': 32, 'weight_decay': 0.00011181576602192727, 'dropout': 0.24878028687775014, 'huber_delta': 0.8400584829885585}. Best is trial 15 with value: 7.694484710693359.
[I 2026-05-28 02:22:13,990] Trial 20 finished with value: 7.700992584228516 and parameters: {'hidden_size': 128, 'lr': 0.003115590445144883, 'batch_size': 32, 'weight_decay': 0.00040395847575083754, 'dropout': 0.25479090350990335, 'huber_delta': 1.0115880230458585}. Best is trial 15 with value: 7.694484710693359.
[I 2026-05-28 02:22:45,231] Trial 21 finished with value: 7.693477630615234 and parameters: {'hidden_size': 128, 'lr': 0.006675681111865245, 'batch_size': 32, 'weight_decay': 0.0009618196271738151, 'dropout': 0.2743350088606128, 'huber_delta': 1.3037752351193186}. Best is trial 21 with value: 7.693477630615234.
[I 2026-05-28 02:23:08,861] Trial 22 finished with value: 7.70046854019165 and parameters: {'hidden_size': 128, 'lr': 0.005346604060894293, 'batch_size': 32, 'weight_decay': 0.0004666962390526424, 'dropout': 0.2700542442862782, 'huber_delta': 1.221583991162405}. Best is trial 21 with value: 7.693477630615234.
[I 2026-05-28 02:23:28,594] Trial 23 finished with value: 7.6936259269714355 and parameters: {'hidden_size': 128, 'lr': 0.0039230679057906176, 'batch_size': 32, 'weight_decay': 0.0009692532189410886, 'dropout': 0.21570737699079962, 'huber_delta': 1.07840731097114}. Best is trial 21 with value: 7.693477630615234.
[I 2026-05-28 02:23:53,999] Trial 24 finished with value: 7.6981635093688965 and parameters: {'hidden_size': 128, 'lr': 0.0023783770233118434, 'batch_size': 32, 'weight_decay': 0.0009999475960889472, 'dropout': 0.20548742946427473, 'huber_delta': 1.0793651117682785}. Best is trial 21 with value: 7.693477630615234.
[I 2026-05-28 02:24:08,817] Trial 25 finished with value: 7.694295883178711 and parameters: {'hidden_size': 128, 'lr': 0.006707224925001629, 'batch_size': 32, 'weight_decay': 0.00018548091973235217, 'dropout': 0.23079285453290044, 'huber_delta': 1.4264087126515077}. Best is trial 21 with value: 7.693477630615234.
[I 2026-05-28 02:24:38,793] Trial 26 finished with value: 7.700472354888916 and parameters: {'hidden_size': 128, 'lr': 0.006850186395850086, 'batch_size': 32, 'weight_decay': 0.00020889447440714085, 'dropout': 0.22094748449700968, 'huber_delta': 1.4292114794731967}. Best is trial 21 with value: 7.693477630615234.
[I 2026-05-28 02:24:56,490] Trial 27 finished with value: 7.695888042449951 and parameters: {'hidden_size': 128, 'lr': 0.007236696266728089, 'batch_size': 32, 'weight_decay': 5.127667603934715e-05, 'dropout': 0.22492725283407122, 'huber_delta': 1.4883235150709702}. Best is trial 21 with value: 7.693477630615234.
[I 2026-05-28 02:25:20,374] Trial 28 finished with value: 7.695093631744385 and parameters: {'hidden_size': 128, 'lr': 0.0039892061742160066, 'batch_size': 32, 'weight_decay': 0.0001416664972953078, 'dropout': 0.33326690148588484, 'huber_delta': 1.261929445443311}. Best is trial 21 with value: 7.693477630615234.
[I 2026-05-28 02:25:47,671] Trial 29 finished with value: 7.709903717041016 and parameters: {'hidden_size': 128, 'lr': 0.0010527728410710618, 'batch_size': 32, 'weight_decay': 7.485139914734162e-05, 'dropout': 0.39260269028536743, 'huber_delta': 0.9458529950860215}. Best is trial 21 with value: 7.693477630615234.
[I 2026-05-28 02:26:01,243] Trial 30 finished with value: 7.698400974273682 and parameters: {'hidden_size': 128, 'lr': 0.0022228819942257208, 'batch_size': 64, 'weight_decay': 0.0002939653171678093, 'dropout': 0.22735038103819277, 'huber_delta': 1.3624959718373464}. Best is trial 21 with value: 7.693477630615234.
[I 2026-05-28 02:26:27,321] Trial 31 finished with value: 7.699909210205078 and parameters: {'hidden_size': 128, 'lr': 0.003999305610921726, 'batch_size': 32, 'weight_decay': 0.0005958265618380931, 'dropout': 0.2698851333400834, 'huber_delta': 1.1847591582402937}. Best is trial 21 with value: 7.693477630615234.
[I 2026-05-28 02:26:49,081] Trial 32 finished with value: 7.698825836181641 and parameters: {'hidden_size': 128, 'lr': 0.006972877814477728, 'batch_size': 32, 'weight_decay': 0.00031192204415117416, 'dropout': 0.2010120713803625, 'huber_delta': 1.1020536371145429}. Best is trial 21 with value: 7.693477630615234.
[I 2026-05-28 02:27:07,631] Trial 33 finished with value: 7.691525936126709 and parameters: {'hidden_size': 128, 'lr': 0.007542139863596335, 'batch_size': 32, 'weight_decay': 0.0005993082382666456, 'dropout': 0.2750860751193764, 'huber_delta': 0.985876308290558}. Best is trial 33 with value: 7.691525936126709.
[I 2026-05-28 02:27:23,194] Trial 34 finished with value: 7.69719934463501 and parameters: {'hidden_size': 128, 'lr': 0.007683931406074189, 'batch_size': 32, 'weight_decay': 0.0005975733007858687, 'dropout': 0.2712360296516306, 'huber_delta': 0.9687212355479353}. Best is trial 33 with value: 7.691525936126709.
[I 2026-05-28 02:27:38,965] Trial 35 finished with value: 7.701890468597412 and parameters: {'hidden_size': 128, 'lr': 0.005478283982136284, 'batch_size': 32, 'weight_decay': 0.000326068240669511, 'dropout': 0.31806174373465157, 'huber_delta': 1.0262744024510944}. Best is trial 33 with value: 7.691525936126709.
[I 2026-05-28 02:27:56,465] Trial 36 finished with value: 7.6994171142578125 and parameters: {'hidden_size': 64, 'lr': 0.007887520351220801, 'batch_size': 64, 'weight_decay': 0.00015904797108900822, 'dropout': 0.27483945440016616, 'huber_delta': 1.6337689821300478}. Best is trial 33 with value: 7.691525936126709.
[I 2026-05-28 02:28:14,566] Trial 37 finished with value: 7.699214935302734 and parameters: {'hidden_size': 128, 'lr': 0.004896852147078825, 'batch_size': 32, 'weight_decay': 0.0006797222542695796, 'dropout': 0.23446252202050313, 'huber_delta': 1.507966695719152}. Best is trial 33 with value: 7.691525936126709.
[I 2026-05-28 02:28:37,324] Trial 38 finished with value: 7.706181049346924 and parameters: {'hidden_size': 128, 'lr': 0.0004999733016883131, 'batch_size': 64, 'weight_decay': 0.0005781678478350347, 'dropout': 0.2989240144380265, 'huber_delta': 0.9022703340846552}. Best is trial 33 with value: 7.691525936126709.
[I 2026-05-28 02:28:52,815] Trial 39 finished with value: 7.699147701263428 and parameters: {'hidden_size': 64, 'lr': 0.006086412638523023, 'batch_size': 32, 'weight_decay': 0.00025909449000414086, 'dropout': 0.3751506292374406, 'huber_delta': 1.3327779496538923}. Best is trial 33 with value: 7.691525936126709.
[I 2026-05-28 02:29:18,092] Trial 40 finished with value: 7.694324016571045 and parameters: {'hidden_size': 128, 'lr': 0.008621954769924967, 'batch_size': 16, 'weight_decay': 1.3422289216742558e-05, 'dropout': 0.3347718018151093, 'huber_delta': 1.225273505369747}. Best is trial 33 with value: 7.691525936126709.
[I 2026-05-28 02:29:48,255] Trial 41 finished with value: 7.695021152496338 and parameters: {'hidden_size': 128, 'lr': 0.008267867513790965, 'batch_size': 16, 'weight_decay': 9.656733878320475e-06, 'dropout': 0.32387292847145843, 'huber_delta': 1.234700840017012}. Best is trial 33 with value: 7.691525936126709.
[I 2026-05-28 02:30:24,140] Trial 42 finished with value: 7.69945764541626 and parameters: {'hidden_size': 128, 'lr': 0.009951282702625198, 'batch_size': 16, 'weight_decay': 5.886458450575031e-06, 'dropout': 0.34804427879122557, 'huber_delta': 1.034980050296537}. Best is trial 33 with value: 7.691525936126709.
[I 2026-05-28 02:30:47,696] Trial 43 finished with value: 7.699426651000977 and parameters: {'hidden_size': 128, 'lr': 0.00436412968022016, 'batch_size': 16, 'weight_decay': 2.688358674559969e-05, 'dropout': 0.2914973506362788, 'huber_delta': 1.1934514702460617}. Best is trial 33 with value: 7.691525936126709.
[I 2026-05-28 02:31:15,282] Trial 44 finished with value: 7.696600437164307 and parameters: {'hidden_size': 128, 'lr': 0.005915311896158546, 'batch_size': 16, 'weight_decay': 1.863954144293887e-05, 'dropout': 0.21656340548235553, 'huber_delta': 1.9678742953655415}. Best is trial 33 with value: 7.691525936126709.
[I 2026-05-28 02:31:38,065] Trial 45 finished with value: 7.702503204345703 and parameters: {'hidden_size': 64, 'lr': 0.002649284836713928, 'batch_size': 16, 'weight_decay': 5.988421996987377e-06, 'dropout': 0.4352449918579926, 'huber_delta': 1.3912016031451289}. Best is trial 33 with value: 7.691525936126709.
[I 2026-05-28 02:31:59,796] Trial 46 finished with value: 7.703407287597656 and parameters: {'hidden_size': 32, 'lr': 0.008162315471607628, 'batch_size': 16, 'weight_decay': 9.02385501448955e-06, 'dropout': 0.3656870283389396, 'huber_delta': 1.5787703802722126}. Best is trial 33 with value: 7.691525936126709.
[I 2026-05-28 02:32:13,283] Trial 47 finished with value: 7.709476470947266 and parameters: {'hidden_size': 128, 'lr': 0.0012773784298468628, 'batch_size': 64, 'weight_decay': 1.4042239081993417e-05, 'dropout': 0.239930767517377, 'huber_delta': 1.3035268801979594}. Best is trial 33 with value: 7.691525936126709.
[I 2026-05-28 02:32:31,262] Trial 48 finished with value: 7.703360080718994 and parameters: {'hidden_size': 32, 'lr': 0.0033142841653732024, 'batch_size': 32, 'weight_decay': 4.509923168249974e-05, 'dropout': 0.2824028623065561, 'huber_delta': 0.983256840866768}. Best is trial 33 with value: 7.691525936126709.
[I 2026-05-28 02:32:56,707] Trial 49 finished with value: 7.700645923614502 and parameters: {'hidden_size': 128, 'lr': 0.006281796449521846, 'batch_size': 16, 'weight_decay': 4.041037090716126e-06, 'dropout': 0.33607117580634394, 'huber_delta': 1.4882925086131935}. Best is trial 33 with value: 7.691525936126709.
[I 2026-05-28 02:33:25,460] Trial 50 finished with value: 7.695765018463135 and parameters: {'hidden_size': 64, 'lr': 0.008749914909059284, 'batch_size': 32, 'weight_decay': 0.0007817520659567945, 'dropout': 0.21294415575227468, 'huber_delta': 1.0716063908834408}. Best is trial 33 with value: 7.691525936126709.
[I 2026-05-28 02:33:54,860] Trial 51 finished with value: 7.693666934967041 and parameters: {'hidden_size': 128, 'lr': 0.003650349449606132, 'batch_size': 32, 'weight_decay': 0.0009977482463137523, 'dropout': 0.26133593117635734, 'huber_delta': 1.1314767429185721}. Best is trial 33 with value: 7.691525936126709.
[I 2026-05-28 02:34:10,780] Trial 52 finished with value: 7.697275638580322 and parameters: {'hidden_size': 128, 'lr': 0.004488817289801365, 'batch_size': 32, 'weight_decay': 0.0004003721300801897, 'dropout': 0.2623167942959554, 'huber_delta': 1.1186211387052758}. Best is trial 33 with value: 7.691525936126709.
[I 2026-05-28 02:34:38,920] Trial 53 finished with value: 7.692776203155518 and parameters: {'hidden_size': 128, 'lr': 0.006208297451603599, 'batch_size': 32, 'weight_decay': 0.0007533276305196902, 'dropout': 0.2323151155922674, 'huber_delta': 1.2196444875333239}. Best is trial 33 with value: 7.691525936126709.
[I 2026-05-28 02:34:56,792] Trial 54 finished with value: 7.695139408111572 and parameters: {'hidden_size': 128, 'lr': 0.0037603632209395887, 'batch_size': 32, 'weight_decay': 0.0007733204919849869, 'dropout': 0.23245467415666654, 'huber_delta': 1.28927225595575}. Best is trial 33 with value: 7.691525936126709.
[I 2026-05-28 02:35:22,877] Trial 55 finished with value: 7.696722507476807 and parameters: {'hidden_size': 128, 'lr': 0.0029530223541553062, 'batch_size': 32, 'weight_decay': 0.0005499740963929901, 'dropout': 0.24174681987301727, 'huber_delta': 1.1553863704046667}. Best is trial 33 with value: 7.691525936126709.
[I 2026-05-28 02:35:45,301] Trial 56 finished with value: 7.693129062652588 and parameters: {'hidden_size': 128, 'lr': 0.005624246193041258, 'batch_size': 32, 'weight_decay': 0.00038000522740618, 'dropout': 0.257634930300632, 'huber_delta': 0.9269911633285615}. Best is trial 33 with value: 7.691525936126709.
[I 2026-05-28 02:36:02,247] Trial 57 pruned.
[I 2026-05-28 02:36:18,995] Trial 58 finished with value: 7.68813943862915 and parameters: {'hidden_size': 128, 'lr': 0.005559384700410929, 'batch_size': 32, 'weight_decay': 0.000994493139509451, 'dropout': 0.30855438256245166, 'huber_delta': 0.8493557973953794}. Best is trial 58 with value: 7.68813943862915.
[I 2026-05-28 02:36:38,303] Trial 59 finished with value: 7.700719356536865 and parameters: {'hidden_size': 128, 'lr': 0.005295354204225647, 'batch_size': 32, 'weight_decay': 0.0007914483494742755, 'dropout': 0.30786022438277283, 'huber_delta': 0.83613895651583}. Best is trial 58 with value: 7.68813943862915.
[I 2026-05-28 02:37:03,102] Trial 60 finished with value: 7.696940898895264 and parameters: {'hidden_size': 128, 'lr': 0.004518844692212261, 'batch_size': 32, 'weight_decay': 0.0005040069164096392, 'dropout': 0.28449082329569414, 'huber_delta': 0.8927246268829719}. Best is trial 58 with value: 7.68813943862915.
[I 2026-05-28 02:37:33,404] Trial 61 finished with value: 7.693373203277588 and parameters: {'hidden_size': 128, 'lr': 0.006315543969269941, 'batch_size': 32, 'weight_decay': 0.0009738738184075683, 'dropout': 0.25960521328787234, 'huber_delta': 0.8547303843155549}. Best is trial 58 with value: 7.68813943862915.
[I 2026-05-28 02:37:52,729] Trial 62 finished with value: 7.691819667816162 and parameters: {'hidden_size': 128, 'lr': 0.006146397917463652, 'batch_size': 32, 'weight_decay': 0.0006782462344868731, 'dropout': 0.292674646153422, 'huber_delta': 0.8533944293789302}. Best is trial 58 with value: 7.68813943862915.
[I 2026-05-28 02:38:27,073] Trial 63 finished with value: 7.698832035064697 and parameters: {'hidden_size': 128, 'lr': 0.005794930125911104, 'batch_size': 32, 'weight_decay': 0.0006436764922010933, 'dropout': 0.29460457503545623, 'huber_delta': 0.8600923483246152}. Best is trial 58 with value: 7.68813943862915.
[I 2026-05-28 02:38:44,341] Trial 64 pruned.
[I 2026-05-28 02:39:01,228] Trial 65 pruned.
[I 2026-05-28 02:39:18,001] Trial 66 finished with value: 7.702147006988525 and parameters: {'hidden_size': 128, 'lr': 0.0052051091501627905, 'batch_size': 32, 'weight_decay': 0.0007062889691973409, 'dropout': 0.25312494762233406, 'huber_delta': 0.8686809570963377}. Best is trial 58 with value: 7.68813943862915.

[HUBER - MTL Imp] Best Avg Val Metric (minimize): 7.6881
 Best Params: {'hidden_size': 128, 'lr': 0.005559384700410929, 'batch_size': 32, 'weight_decay': 0.000994493139509451, 'dropout': 0.30855438256245166, 'huber_delta': 0.8493557973953794}

In [ ]:
print("\n--- Baseline MTL Best Params ---")
for l_type, params in best_mtl_baselines.items():
    print(f"[Baseline - {l_type.upper()}] \n {params}\n")

print("\n--- Improved MTL Best Params ---")
for l_type, params in best_mtl_imp.items():
    print(f"[Improved - {l_type.upper()}] \n {params}\n")

--- Baseline MTL Best Params ---
[Baseline - L1]
 {'hidden_size': 128, 'lr': 0.0014436947840858378, 'batch_size': 64, 'weight_decay': 3.876080827850374e-05, 'dropout': 0.39717688152505026}

[Baseline - MSE]
 {'hidden_size': 64, 'lr': 0.005358904243667092, 'batch_size': 16, 'weight_decay': 0.0007934779438993115, 'dropout': 0.46860618654311137}

[Baseline - HUBER]
 {'hidden_size': 128, 'lr': 0.003673569654223351, 'batch_size': 16, 'weight_decay': 0.00021943085674158504, 'dropout': 0.3440568739399561, 'huber_delta': 1.4380843861038661}


--- Improved MTL Best Params ---
[Improved - L1]
 {'hidden_size': 32, 'lr': 0.003401507766189891, 'batch_size': 16, 'weight_decay': 7.839968960863435e-06, 'dropout': 0.2723634682240227}

[Improved - MSE]
 {'hidden_size': 128, 'lr': 0.00873193948799961, 'batch_size': 32, 'weight_decay': 0.000431472809664785, 'dropout': 0.4108777207863841}

[Improved - HUBER]
 {'hidden_size': 128, 'lr': 0.005559384700410929, 'batch_size': 32, 'weight_decay': 0.000994493139509451, 'dropout': 0.30855438256245166, 'huber_delta': 0.8493557973953794}

In [ ]:
def build_loaders_and_model(is_improved, params):
    dropout_val = params.get("dropout", 0.2)
    if is_improved:
        train_ds = ImprovedYoYDatasetMTL(mtl_train_data_imp, robust_scaler, selected_indices)
        val_ds = ImprovedYoYDatasetMTL(mtl_val_data_imp, robust_scaler, selected_indices)
        test_ds = ImprovedYoYDatasetMTL(mtl_test_data_imp, robust_scaler, selected_indices)
        collate = collate_fn_improved_mtl
        model = ImprovedShallowLSTM(len(selected_indices), params["hidden_size"], len(PREDICTION_TARGETS), dropout_val).to(DEVICE)
    else:
        train_ds = YoYSequenceDatasetMTL(mtl_train_data, max_seq_length, scaler)
        val_ds = YoYSequenceDatasetMTL(mtl_val_data, max_seq_length, scaler)
        test_ds = YoYSequenceDatasetMTL(mtl_test_data, max_seq_length, scaler)
        collate = None
        model = ShallowLSTMClassifier(len(feature_cols), params["hidden_size"], len(PREDICTION_TARGETS), dropout_val).to(DEVICE)

    if collate:
        train_loader = DataLoader(train_ds, batch_size=params["batch_size"], shuffle=True, collate_fn=collate)
        val_loader = DataLoader(val_ds, batch_size=params["batch_size"], shuffle=False, collate_fn=collate)
        test_loader = DataLoader(test_ds, batch_size=params["batch_size"], shuffle=False, collate_fn=collate)
    else:
        train_loader = DataLoader(train_ds, batch_size=params["batch_size"], shuffle=True)
        val_loader = DataLoader(val_ds, batch_size=params["batch_size"], shuffle=False)
        test_loader = DataLoader(test_ds, batch_size=params["batch_size"], shuffle=False)

    return model, train_loader, val_loader, test_loader


def evaluate_loader(model, loader, is_improved):
    model.eval()
    all_preds, all_targets, all_masks = [], [], []
    with torch.no_grad():
        for batch in loader:
            if is_improved:
                bx, by, bmask, lengths = batch
                logits = model(bx.to(DEVICE), lengths)
                all_masks.append(bmask.numpy())
            else:
                bx, by, bmask = batch
                logits = model(bx.to(DEVICE))
                all_masks.append(bmask.numpy())

            all_preds.append(logits.cpu().numpy())
            all_targets.append(by.numpy())

    if not all_preds:
        return None

    y_pred = np.vstack(all_preds)
    y_true = np.vstack(all_targets)

    if is_improved:
        y_pred = np.sign(y_pred) * np.expm1(np.abs(y_pred))
        y_true = np.sign(y_true) * np.expm1(np.abs(y_true))

    mask = np.vstack(all_masks)
    res = {}
    for i, t in enumerate(PREDICTION_TARGETS):
        m = mask[:, i]
        if m.sum() == 0:
            continue
        res[t] = np.mean(np.abs(y_pred[m, i] - y_true[m, i]))
    return res


def final_train_and_test(is_improved, params, loss_type='l1'):
    model, train_loader, val_loader, test_loader = build_loaders_and_model(
        is_improved, params
    )

    optimizer = torch.optim.Adam(model.parameters(), lr=params["lr"], weight_decay=params["weight_decay"])
    huber_delta = params.get("huber_delta", 1.0)

    model, _ = train_and_eval(
        model, train_loader, val_loader, optimizer,
        is_improved=is_improved, loss_type=loss_type, huber_delta=huber_delta
    )

    return evaluate_loader(model, test_loader, is_improved=is_improved)

def set_seed(seed):
    np.random.seed(seed)
    torch.manual_seed(seed)

N_RUNS = 20
print(f"Computing Final Test Metrics using Test Sets across {N_RUNS} runs...")
final_results = []

def run_multiple_times(pipeline_name, is_improved, best_params_dict):
    for l_type, params in best_params_dict.items():
        print(f"Running {pipeline_name} with {l_type.upper()} loss...")
        target_results = {t: [] for t in PREDICTION_TARGETS}
        for run_idx in range(N_RUNS):
            set_seed(SEED + run_idx)
            res = final_train_and_test(is_improved, params, loss_type=l_type)
            for target, val in res.items():
                target_results[target].append(val)

        for target in PREDICTION_TARGETS:
            avg_mae = np.mean(target_results[target])
            std_mae = np.std(target_results[target])
            final_results.append({
                "Pipeline": pipeline_name,
                "Loss": l_type.upper(),
                "Target": target,
                "Test MAE (Mean)": avg_mae,
                "Deviation": std_mae
            })

Computing Final Test Metrics using Test Sets across 20 runs...

In [ ]:
final_results = []
run_multiple_times("Baseline", False, best_mtl_baselines)
run_multiple_times("Improved", True, best_mtl_imp)

df_final = pd.DataFrame(final_results)

# Create a pivot table for easy comparison
pivot_df = df_final.pivot_table(
    index=["Target", "Loss"],
    columns=["Pipeline"],
    values=["Test MAE (Mean)", "Deviation"]
)
display(pivot_df)

Running Baseline with L1 loss...
Running Baseline with MSE loss...
Running Baseline with HUBER loss...
Running Improved with L1 loss...
Running Improved with MSE loss...
Running Improved with HUBER loss...

                 Deviation           Test MAE (Mean)
Pipeline          Baseline  Improved        Baseline  Improved
Target     Loss
EBITDA     HUBER  0.040016  0.009347        1.537412  1.501781
           L1     0.018248  0.008191        1.497533  1.492321
           MSE    0.104793  0.036764        1.669935  1.533402
Net_Income HUBER  0.022528  0.008445        1.564425  1.553314
           L1     0.008348  0.008066        1.555753  1.561342
           MSE    0.038836  0.007787        1.594874  1.555342
ROA        HUBER  0.027862  0.012895        1.596761  1.587349
           L1     0.010313  0.012361        1.583823  1.587322
           MSE    0.060500  0.010091        1.647139  1.583727

## Segmented Performance Analysis

In [ ]:
def evaluate_group_pipeline(is_improved, best_params_dict):
    group_results = []

    for l_type, params in best_params_dict.items():
        # Store individual run MAEs here to compute standard deviation
        group_run_maes = {grp: {t: [] for t in PREDICTION_TARGETS} for grp in ticker_groups.keys()}

        for run_idx in range(N_RUNS):
            set_seed(SEED + run_idx)
            # Re-train model for this run
            model, train_loader, val_loader, _ = build_loaders_and_model(is_improved, params)
            optimizer = torch.optim.Adam(model.parameters(), lr=params["lr"], weight_decay=params["weight_decay"])
            huber_delta = params.get("huber_delta", 1.0)
            model, _ = train_and_eval(model, train_loader, val_loader, optimizer, is_improved=is_improved, loss_type=l_type, huber_delta=huber_delta)

            for group_name, tickers in ticker_groups.items():
                if is_improved:
                    group_df = mtl_test_data_imp[mtl_test_data_imp['company'].isin(tickers)]
                    if group_df.empty: continue
                    group_ds = ImprovedYoYDatasetMTL(group_df, robust_scaler, selected_indices)
                    collate = collate_fn_improved_mtl
                else:
                    group_df = mtl_test_data[mtl_test_data['company'].isin(tickers)]
                    if group_df.empty: continue
                    group_ds = YoYSequenceDatasetMTL(group_df, max_seq_length, scaler)
                    collate = None

                loader = DataLoader(group_ds, batch_size=params["batch_size"], shuffle=False, collate_fn=collate)
                metrics = evaluate_loader(model, loader, is_improved=is_improved)

                if metrics:
                    for target, val in metrics.items():
                        group_run_maes[group_name][target].append(val)

        # Compute mean and std
        for group_name in ticker_groups.keys():
            for target in PREDICTION_TARGETS:
                if len(group_run_maes[group_name][target]) > 0:
                    maes = group_run_maes[group_name][target]
                    group_results.append({
                        "Loss": l_type.upper(),
                        "Group": group_name,
                        "Target": target,
                        "MAE (Mean)": np.mean(maes),
                        "Deviation": np.std(maes)
                    })

    return group_results

print("Evaluating Improved MTL across losses and groups...")
imp_group_stats = evaluate_group_pipeline(True, best_mtl_imp)

print("\nEvaluating Baseline MTL across losses and groups...")
base_group_stats = evaluate_group_pipeline(False, best_mtl_baselines)

df_imp_group = pd.DataFrame(imp_group_stats)
df_base_group = pd.DataFrame(base_group_stats)

print("\n--- Grouped MAE: Improved MTL ---")
if not df_imp_group.empty:
    display(df_imp_group.pivot_table(index=['Target', 'Loss'], columns='Group', values=['MAE (Mean)', 'Deviation']))

print("\n--- Grouped MAE: Baseline MTL ---")
if not df_base_group.empty:
    display(df_base_group.pivot_table(index=['Target', 'Loss'], columns='Group', values=['MAE (Mean)', 'Deviation']))

Evaluating Improved MTL across losses and groups...

Evaluating Baseline MTL across losses and groups...

--- Grouped MAE: Improved MTL ---

                 Deviation                     MAE (Mean)
Group                  MIB   Mid-cap Small-cap        MIB   Mid-cap Small-cap
Target     Loss
EBITDA     HUBER  0.013345  0.012285  0.011936   1.882129  0.432301  2.077805
           L1     0.007175  0.010151  0.011694   1.872868  0.423073  2.068846
           MSE    0.016179  0.029560  0.056993   1.879454  0.456574  2.127214
Net_Income HUBER  0.019447  0.015695  0.004571   0.727523  1.660671  1.794760
           L1     0.018631  0.018250  0.014093   0.728950  1.658343  1.811956
           MSE    0.020231  0.017087  0.003697   0.728444  1.674364  1.789339
ROA        HUBER  0.022916  0.024162  0.004770   0.724385  1.634140  1.882975
           L1     0.018667  0.024420  0.013050   0.722308  1.619287  1.893402
           MSE    0.018359  0.019872  0.005220   0.722233  1.631258  1.877700

--- Grouped MAE: Baseline MTL ---

                 Deviation                     MAE (Mean)
Group                  MIB   Mid-cap Small-cap        MIB   Mid-cap Small-cap
Target     Loss
EBITDA     HUBER  0.032670  0.048373  0.037989   1.897592  0.477673  2.114572
           L1     0.018431  0.021678  0.020876   1.868880  0.431836  2.074885
           MSE    0.089618  0.128185  0.095976   2.017731  0.637593  2.234647
Net_Income HUBER  0.041453  0.044896  0.011992   0.733051  1.674605  1.806381
           L1     0.022736  0.014829  0.010894   0.722157  1.649563  1.809530
           MSE    0.070602  0.070106  0.020684   0.782812  1.724882  1.816690
ROA        HUBER  0.046131  0.051967  0.015194   0.734569  1.644067  1.891570
           L1     0.021650  0.019594  0.012843   0.719380  1.612774  1.892010
           MSE    0.093082  0.097450  0.028914   0.814015  1.724964  1.910691

### Directional Accuracy

In [ ]:
def calculate_directional_accuracy(model, loader, is_improved):
    model.eval()
    all_preds, all_targets, all_masks = [], [], []
    with torch.no_grad():
        for batch in loader:
            if is_improved:
                bx, by, bmask, lengths = batch
                logits = model(bx.to(DEVICE), lengths)
                all_masks.append(bmask.numpy())
            else:
                bx, by, bmask = batch
                logits = model(bx.to(DEVICE))
                all_masks.append(bmask.numpy())
            all_preds.append(logits.cpu().numpy())
            all_targets.append(by.numpy())

    y_pred = np.vstack(all_preds)
    y_true = np.vstack(all_targets)
    mask = np.vstack(all_masks)

    accuracy_res = {}
    for i, t in enumerate(PREDICTION_TARGETS):
        m = mask[:, i]
        if m.sum() == 0: continue
        # Directional agreement: both positive or both negative
        correct_dir = (np.sign(y_pred[m, i]) == np.sign(y_true[m, i])).sum()
        accuracy_res[t] = correct_dir / m.sum()
    return accuracy_res

print("--- Directional Accuracy (Improved Pipeline) ---")
for l_type, params in best_mtl_imp.items():
    model_imp, _, _, test_loader_imp = build_loaders_and_model(True, params)
    dir_acc = calculate_directional_accuracy(model_imp, test_loader_imp, True)
    print(f"[{l_type.upper()}] Directional Accuracy:", dir_acc)

--- Directional Accuracy (Improved Pipeline) ---
[L1] Directional Accuracy: {'EBITDA': np.float64(0.4315352697095436), 'Net_Income': np.float64(0.5318275154004107), 'ROA': np.float64(0.4948665297741273)}
[MSE] Directional Accuracy: {'EBITDA': np.float64(0.6307053941908713), 'Net_Income': np.float64(0.4722792607802875), 'ROA': np.float64(0.5297741273100616)}
[HUBER] Directional Accuracy: {'EBITDA': np.float64(0.37136929460580914), 'Net_Income': np.float64(0.5503080082135524), 'ROA': np.float64(0.5174537987679672)}

### Specialized Models by Market Cap

In [ ]:
def run_dedicated_pipeline(group_name, tickers, loss_type='l1'):
    print(f"--- Dedicated Pipeline: {group_name} ({loss_type.upper()}) ---")
    group_df = improved_data_df[improved_data_df['company'].isin(tickers)].copy()
    if group_df.empty:
        print(f"No data for {group_name}")
        return

    g_train, g_val, g_test = split_by_year(group_df, TRAIN_YEAR_CUTOFF, VALID_YEAR_CUTOFF)

    # Scoping scaler to group
    g_scaler = RobustScaler()
    g_train_windows = np.vstack([row[:, selected_indices] for row in g_train["window_data"]])
    g_scaler.fit(g_train_windows)

    g_mtl_train = extract_mtl_df(g_train)
    g_mtl_val = extract_mtl_df(g_val)
    g_mtl_test = extract_mtl_df(g_test)

    def group_objective(trial):
        hidden_size = trial.suggest_categorical("hidden_size", [32, 64, 128])
        lr = trial.suggest_float("lr", 1e-4, 1e-2, log=True)
        batch_size = trial.suggest_categorical("batch_size", [16, 32, 64])
        weight_decay = trial.suggest_float("weight_decay", 1e-6, 1e-3, log=True)
        dropout = trial.suggest_float("dropout", 0.1, 0.5)

        train_ds = ImprovedYoYDatasetMTL(g_mtl_train, g_scaler, selected_indices)
        val_ds = ImprovedYoYDatasetMTL(g_mtl_val, g_scaler, selected_indices)

        train_loader = DataLoader(train_ds, batch_size=batch_size, shuffle=True, collate_fn=collate_fn_improved_mtl)
        val_loader = DataLoader(val_ds, batch_size=batch_size, shuffle=False, collate_fn=collate_fn_improved_mtl)

        model = ImprovedShallowLSTM(len(selected_indices), hidden_size, len(PREDICTION_TARGETS), dropout).to(DEVICE)
        optimizer = torch.optim.Adam(model.parameters(), lr=lr, weight_decay=weight_decay)

        _, best_metric = train_and_eval(model, train_loader, val_loader, optimizer, True, trial, loss_type=loss_type)
        return best_metric

    pruner = optuna.pruners.MedianPruner(n_startup_trials=10, n_warmup_steps=15)
    study = optuna.create_study(direction="minimize", study_name=f"mtl_imp_{group_name}", pruner=pruner)
    study.optimize(group_objective, n_trials=OPTUNA_TRIALS)

    best_params = study.best_trial.params
    print(f"Best Params for {group_name}: {best_params}\n")

    # Final evaluation multiple runs
    target_results = {t: [] for t in PREDICTION_TARGETS}

    for run_idx in range(N_RUNS):
        set_seed(SEED + run_idx)
        train_ds = ImprovedYoYDatasetMTL(g_mtl_train, g_scaler, selected_indices)
        val_ds = ImprovedYoYDatasetMTL(g_mtl_val, g_scaler, selected_indices)
        test_ds = ImprovedYoYDatasetMTL(g_mtl_test, g_scaler, selected_indices)

        train_loader = DataLoader(train_ds, batch_size=best_params["batch_size"], shuffle=True, collate_fn=collate_fn_improved_mtl)
        val_loader = DataLoader(val_ds, batch_size=best_params["batch_size"], shuffle=False, collate_fn=collate_fn_improved_mtl)
        test_loader = DataLoader(test_ds, batch_size=best_params["batch_size"], shuffle=False, collate_fn=collate_fn_improved_mtl)

        dropout_val = best_params.get("dropout", 0.2)
        model = ImprovedShallowLSTM(len(selected_indices), best_params["hidden_size"], len(PREDICTION_TARGETS), dropout_val).to(DEVICE)
        optimizer = torch.optim.Adam(model.parameters(), lr=best_params["lr"], weight_decay=best_params["weight_decay"])

        model, _ = train_and_eval(model, train_loader, val_loader, optimizer, True, None, loss_type=loss_type)
        res = evaluate_loader(model, test_loader, True)

        if res:
            for target, val in res.items():
                target_results[target].append(val)

        group_stats = []

    # MAE per target
    for target in PREDICTION_TARGETS:
        avg_mae = np.mean(target_results[target])
        std_mae = np.std(target_results[target])

        group_stats.append({
            "Group": group_name,
            "Target": target,
            "Dedicated Test MAE": avg_mae,
            "Dedicated Deviation": std_mae
        })

    total_mae = np.mean([
        np.mean(target_results[target])
        for target in PREDICTION_TARGETS
    ])

    total_std = np.std([
        np.mean(target_results[target])
        for target in PREDICTION_TARGETS
    ])

    print(f"{group_name} - Total Test MAE: {total_mae:.4f} ± {total_std:.4f}")

    group_stats.append({
        "Group": group_name,
        "Target": "TOTAL",
        "Dedicated Test MAE": total_mae,
        "Dedicated Deviation": total_std
    })

    return group_stats

dedicated_all_stats = []
for group_name, tickers in ticker_groups.items():
    stats = run_dedicated_pipeline(group_name, tickers, loss_type='l1') # Defaulting to L1 as champion
    if stats:
        dedicated_all_stats.extend(stats)

df_dedicated = pd.DataFrame(dedicated_all_stats)
display(df_dedicated.pivot(index='Target', columns='Group', values='Dedicated Test MAE'))

--- Dedicated Pipeline: MIB (L1) ---

[I 2026-06-09 13:36:37,825] A new study created in memory with name: mtl_imp_MIB
[I 2026-06-09 13:37:01,540] Trial 0 finished with value: 3.2393970489501953 and parameters: {'hidden_size': 64, 'lr': 0.00033394693981808214, 'batch_size': 16, 'weight_decay': 5.520454939337981e-06, 'dropout': 0.1597438568222771}. Best is trial 0 with value: 3.2393970489501953.
[I 2026-06-09 13:37:10,768] Trial 1 finished with value: 3.2112629413604736 and parameters: {'hidden_size': 32, 'lr': 0.0034624333747282606, 'batch_size': 32, 'weight_decay': 0.00069538361166545, 'dropout': 0.31359549926897357}. Best is trial 1 with value: 3.2112629413604736.
[I 2026-06-09 13:37:15,528] Trial 2 finished with value: 3.2050540447235107 and parameters: {'hidden_size': 128, 'lr': 0.001090209309503447, 'batch_size': 16, 'weight_decay': 3.0235842334655288e-05, 'dropout': 0.11609442500888463}. Best is trial 2 with value: 3.2050540447235107.
[I 2026-06-09 13:37:24,722] Trial 3 finished with value: 3.1962947845458984 and parameters: {'hidden_size': 128, 'lr': 0.006264294511119878, 'batch_size': 16, 'weight_decay': 0.0008915768999733689, 'dropout': 0.4490322895238731}. Best is trial 3 with value: 3.1962947845458984.
[I 2026-06-09 13:37:28,065] Trial 4 finished with value: 3.197815179824829 and parameters: {'hidden_size': 128, 'lr': 0.006439269061195092, 'batch_size': 32, 'weight_decay': 3.6384048809089867e-06, 'dropout': 0.21401280937387127}. Best is trial 3 with value: 3.1962947845458984.
[I 2026-06-09 13:37:38,087] Trial 5 finished with value: 3.2229373455047607 and parameters: {'hidden_size': 64, 'lr': 0.00022770087988650722, 'batch_size': 16, 'weight_decay': 0.00024068931286179077, 'dropout': 0.16404763950915008}. Best is trial 3 with value: 3.1962947845458984.
[I 2026-06-09 13:37:43,043] Trial 6 finished with value: 3.2745721340179443 and parameters: {'hidden_size': 64, 'lr': 0.00018551916442122827, 'batch_size': 64, 'weight_decay': 1.3351491933552963e-05, 'dropout': 0.2860705952294449}. Best is trial 3 with value: 3.1962947845458984.
[I 2026-06-09 13:37:50,532] Trial 7 finished with value: 3.190805196762085 and parameters: {'hidden_size': 32, 'lr': 0.001570410125682601, 'batch_size': 16, 'weight_decay': 6.566588551542508e-05, 'dropout': 0.4390545638910722}. Best is trial 7 with value: 3.190805196762085.
[I 2026-06-09 13:37:59,215] Trial 8 finished with value: 3.1936137676239014 and parameters: {'hidden_size': 32, 'lr': 0.0007802928320540845, 'batch_size': 16, 'weight_decay': 0.000263134846939179, 'dropout': 0.23186392636881936}. Best is trial 7 with value: 3.190805196762085.
[I 2026-06-09 13:38:09,684] Trial 9 finished with value: 3.18871808052063 and parameters: {'hidden_size': 32, 'lr': 0.0015548467889591102, 'batch_size': 64, 'weight_decay': 1.693608768944303e-06, 'dropout': 0.341091939716518}. Best is trial 9 with value: 3.18871808052063.
[I 2026-06-09 13:38:12,334] Trial 10 pruned.
[I 2026-06-09 13:38:14,948] Trial 11 pruned.
[I 2026-06-09 13:38:17,414] Trial 12 finished with value: 3.2009830474853516 and parameters: {'hidden_size': 32, 'lr': 0.0017515978215061527, 'batch_size': 64, 'weight_decay': 1.01044249285608e-06, 'dropout': 0.3925035880377129}. Best is trial 9 with value: 3.18871808052063.
[I 2026-06-09 13:38:20,666] Trial 13 pruned.
[I 2026-06-09 13:38:23,972] Trial 14 pruned.
[I 2026-06-09 13:38:29,388] Trial 15 finished with value: 3.1955254077911377 and parameters: {'hidden_size': 32, 'lr': 0.002902340078676707, 'batch_size': 16, 'weight_decay': 0.00012581244834178099, 'dropout': 0.46154414881515693}. Best is trial 9 with value: 3.18871808052063.
[I 2026-06-09 13:38:33,948] Trial 16 pruned.
[I 2026-06-09 13:38:39,585] Trial 17 finished with value: 3.1944494247436523 and parameters: {'hidden_size': 32, 'lr': 0.004488346292165083, 'batch_size': 64, 'weight_decay': 4.16687159332207e-06, 'dropout': 0.35099399354958843}. Best is trial 9 with value: 3.18871808052063.
[I 2026-06-09 13:38:44,198] Trial 18 pruned.
[I 2026-06-09 13:38:47,930] Trial 19 finished with value: 3.2038021087646484 and parameters: {'hidden_size': 128, 'lr': 0.009687402280972273, 'batch_size': 32, 'weight_decay': 2.172133660169819e-06, 'dropout': 0.4154368914793479}. Best is trial 9 with value: 3.18871808052063.
[I 2026-06-09 13:38:50,520] Trial 20 pruned.
[I 2026-06-09 13:38:54,679] Trial 21 pruned.
[I 2026-06-09 13:38:59,322] Trial 22 pruned.
[I 2026-06-09 13:39:03,318] Trial 23 pruned.
[I 2026-06-09 13:39:07,439] Trial 24 pruned.
[I 2026-06-09 13:39:11,988] Trial 25 pruned.
[I 2026-06-09 13:39:20,900] Trial 26 finished with value: 3.1924331188201904 and parameters: {'hidden_size': 32, 'lr': 0.002659341124996666, 'batch_size': 16, 'weight_decay': 0.0004226200960140802, 'dropout': 0.17390317862237237}. Best is trial 9 with value: 3.18871808052063.
[I 2026-06-09 13:39:25,264] Trial 27 pruned.
[I 2026-06-09 13:39:28,146] Trial 28 pruned.
[I 2026-06-09 13:39:35,442] Trial 29 finished with value: 3.183743715286255 and parameters: {'hidden_size': 64, 'lr': 0.0047639846588888755, 'batch_size': 32, 'weight_decay': 0.0004627785003174142, 'dropout': 0.137398162298415}. Best is trial 29 with value: 3.183743715286255.
[I 2026-06-09 13:39:39,021] Trial 30 finished with value: 3.205381155014038 and parameters: {'hidden_size': 64, 'lr': 0.004641932158373863, 'batch_size': 32, 'weight_decay': 1.0844013463499635e-06, 'dropout': 0.4605578191736961}. Best is trial 29 with value: 3.183743715286255.
[I 2026-06-09 13:39:43,732] Trial 31 finished with value: 3.1931540966033936 and parameters: {'hidden_size': 64, 'lr': 0.004112181304521836, 'batch_size': 32, 'weight_decay': 0.0004708259262033211, 'dropout': 0.13788438173308887}. Best is trial 29 with value: 3.183743715286255.
[I 2026-06-09 13:39:48,813] Trial 32 finished with value: 3.1954917907714844 and parameters: {'hidden_size': 64, 'lr': 0.006246904273531176, 'batch_size': 32, 'weight_decay': 0.00018008144210477758, 'dropout': 0.18149801083168743}. Best is trial 29 with value: 3.183743715286255.
[I 2026-06-09 13:39:56,017] Trial 33 finished with value: 3.194345235824585 and parameters: {'hidden_size': 64, 'lr': 0.0015676622166320266, 'batch_size': 32, 'weight_decay': 0.000565005595904115, 'dropout': 0.13958128849152576}. Best is trial 29 with value: 3.183743715286255.
[I 2026-06-09 13:39:59,959] Trial 34 pruned.
[I 2026-06-09 13:40:03,972] Trial 35 finished with value: 3.2098751068115234 and parameters: {'hidden_size': 128, 'lr': 0.009505368899600648, 'batch_size': 16, 'weight_decay': 0.00038217259129400477, 'dropout': 0.1178478854208743}. Best is trial 29 with value: 3.183743715286255.
[I 2026-06-09 13:40:12,936] Trial 36 finished with value: 3.195540189743042 and parameters: {'hidden_size': 64, 'lr': 0.002421015962689911, 'batch_size': 16, 'weight_decay': 0.0007583139802164452, 'dropout': 0.1843587921460571}. Best is trial 29 with value: 3.183743715286255.
[I 2026-06-09 13:40:18,729] Trial 37 finished with value: 3.1847169399261475 and parameters: {'hidden_size': 32, 'lr': 0.006413677184482696, 'batch_size': 32, 'weight_decay': 5.550706873568326e-06, 'dropout': 0.28207525116189525}. Best is trial 29 with value: 3.183743715286255.
[I 2026-06-09 13:40:22,973] Trial 38 finished with value: 3.200672149658203 and parameters: {'hidden_size': 128, 'lr': 0.00704272842886344, 'batch_size': 32, 'weight_decay': 2.417533107789274e-06, 'dropout': 0.29513259857594587}. Best is trial 29 with value: 3.183743715286255.
[I 2026-06-09 13:40:27,224] Trial 39 pruned.
[I 2026-06-09 13:40:30,381] Trial 40 pruned.
[I 2026-06-09 13:40:37,449] Trial 41 finished with value: 3.1962385177612305 and parameters: {'hidden_size': 32, 'lr': 0.0037837032242149, 'batch_size': 32, 'weight_decay': 0.0001781863347371173, 'dropout': 0.30250409534177186}. Best is trial 29 with value: 3.183743715286255.
[I 2026-06-09 13:40:40,960] Trial 42 finished with value: 3.2023284435272217 and parameters: {'hidden_size': 32, 'lr': 0.0056747247869546776, 'batch_size': 32, 'weight_decay': 1.4928620619414355e-06, 'dropout': 0.20445108090113473}. Best is trial 29 with value: 3.183743715286255.
[I 2026-06-09 13:40:43,560] Trial 43 pruned.
[I 2026-06-09 13:40:48,372] Trial 44 pruned.
[I 2026-06-09 13:40:51,187] Trial 45 pruned.
[I 2026-06-09 13:40:55,391] Trial 46 pruned.
[I 2026-06-09 13:40:58,671] Trial 47 pruned.
[I 2026-06-09 13:41:01,939] Trial 48 pruned.
[I 2026-06-09 13:41:05,566] Trial 49 finished with value: 3.25163197517395 and parameters: {'hidden_size': 64, 'lr': 0.00028146582782474463, 'batch_size': 16, 'weight_decay': 0.000662005309322505, 'dropout': 0.15993236012493528}. Best is trial 29 with value: 3.183743715286255.
[I 2026-06-09 13:41:09,421] Trial 50 pruned.
[I 2026-06-09 13:41:13,922] Trial 51 pruned.
[I 2026-06-09 13:41:17,382] Trial 52 pruned.
[I 2026-06-09 13:41:20,982] Trial 53 finished with value: 3.1908397674560547 and parameters: {'hidden_size': 64, 'lr': 0.0025138109501879773, 'batch_size': 32, 'weight_decay': 0.0004705453497658635, 'dropout': 0.17487408094806872}. Best is trial 29 with value: 3.183743715286255.
[I 2026-06-09 13:41:24,352] Trial 54 finished with value: 3.2233970165252686 and parameters: {'hidden_size': 64, 'lr': 0.0026017017348937328, 'batch_size': 32, 'weight_decay': 0.00023399676339605662, 'dropout': 0.20709460342408714}. Best is trial 29 with value: 3.183743715286255.
[I 2026-06-09 13:41:27,461] Trial 55 pruned.
[I 2026-06-09 13:41:31,650] Trial 56 pruned.
[I 2026-06-09 13:41:34,659] Trial 57 finished with value: 3.2375175952911377 and parameters: {'hidden_size': 32, 'lr': 0.0031739189723683048, 'batch_size': 32, 'weight_decay': 2.7531362865840116e-05, 'dropout': 0.22206946037279998}. Best is trial 29 with value: 3.183743715286255.
[I 2026-06-09 13:41:37,704] Trial 58 pruned.
[I 2026-06-09 13:41:42,030] Trial 59 pruned.
[I 2026-06-09 13:41:45,442] Trial 60 pruned.
[I 2026-06-09 13:41:49,765] Trial 61 finished with value: 3.1852920055389404 and parameters: {'hidden_size': 64, 'lr': 0.004208469038326672, 'batch_size': 32, 'weight_decay': 0.00047757283426622116, 'dropout': 0.14422467405780526}. Best is trial 29 with value: 3.183743715286255.
[I 2026-06-09 13:41:53,371] Trial 62 pruned.
[I 2026-06-09 13:41:57,265] Trial 63 pruned.
[I 2026-06-09 13:42:00,374] Trial 64 finished with value: 3.18798565864563 and parameters: {'hidden_size': 64, 'lr': 0.007670799415335552, 'batch_size': 32, 'weight_decay': 4.905571706084195e-06, 'dropout': 0.157346502317815}. Best is trial 29 with value: 3.183743715286255.
[I 2026-06-09 13:42:04,001] Trial 65 finished with value: 3.2069404125213623 and parameters: {'hidden_size': 64, 'lr': 0.007223363444417512, 'batch_size': 32, 'weight_decay': 4.4254283350771935e-06, 'dropout': 0.1567130374172093}. Best is trial 29 with value: 3.183743715286255.
[I 2026-06-09 13:42:07,308] Trial 66 pruned.
[I 2026-06-09 13:42:11,589] Trial 67 finished with value: 3.188819169998169 and parameters: {'hidden_size': 64, 'lr': 0.005844795142730831, 'batch_size': 32, 'weight_decay': 2.7991333065010606e-06, 'dropout': 0.4171760439320697}. Best is trial 29 with value: 3.183743715286255.
[I 2026-06-09 13:42:15,980] Trial 68 finished with value: 3.202716827392578 and parameters: {'hidden_size': 64, 'lr': 0.005982850979875133, 'batch_size': 32, 'weight_decay': 2.28512260498207e-06, 'dropout': 0.4060998418239201}. Best is trial 29 with value: 3.183743715286255.
[I 2026-06-09 13:42:20,195] Trial 69 pruned.
[I 2026-06-09 13:42:23,851] Trial 70 finished with value: 3.1962881088256836 and parameters: {'hidden_size': 64, 'lr': 0.008280896499924457, 'batch_size': 32, 'weight_decay': 1.480468632279785e-06, 'dropout': 0.4805325165356772}. Best is trial 29 with value: 3.183743715286255.
[I 2026-06-09 13:42:28,589] Trial 71 pruned.
[I 2026-06-09 13:42:31,980] Trial 72 pruned.
[I 2026-06-09 13:42:35,301] Trial 73 pruned.
[I 2026-06-09 13:42:38,841] Trial 74 pruned.
[I 2026-06-09 13:42:43,403] Trial 75 pruned.
[I 2026-06-09 13:42:46,107] Trial 76 pruned.
[I 2026-06-09 13:42:50,080] Trial 77 pruned.
[I 2026-06-09 13:42:56,711] Trial 78 finished with value: 3.1985957622528076 and parameters: {'hidden_size': 64, 'lr': 0.007987668443083963, 'batch_size': 32, 'weight_decay': 2.0007227112067197e-06, 'dropout': 0.16739586009915622}. Best is trial 29 with value: 3.183743715286255.
[I 2026-06-09 13:42:59,390] Trial 79 pruned.
[I 2026-06-09 13:43:03,604] Trial 80 finished with value: 3.2007713317871094 and parameters: {'hidden_size': 128, 'lr': 0.0054568965994601605, 'batch_size': 32, 'weight_decay': 0.0003095491786120959, 'dropout': 0.4377747940394562}. Best is trial 29 with value: 3.183743715286255.
[I 2026-06-09 13:43:09,113] Trial 81 finished with value: 3.191218137741089 and parameters: {'hidden_size': 32, 'lr': 0.002477888957424047, 'batch_size': 16, 'weight_decay': 0.0005026960615975634, 'dropout': 0.19471960322723053}. Best is trial 29 with value: 3.183743715286255.
[I 2026-06-09 13:43:18,125] Trial 82 finished with value: 3.187701463699341 and parameters: {'hidden_size': 32, 'lr': 0.0032903978116036476, 'batch_size': 16, 'weight_decay': 0.000528870138135143, 'dropout': 0.18814674353646182}. Best is trial 29 with value: 3.183743715286255.
[I 2026-06-09 13:43:22,860] Trial 83 finished with value: 3.194366693496704 and parameters: {'hidden_size': 32, 'lr': 0.003130743264692832, 'batch_size': 16, 'weight_decay': 6.502921527829966e-06, 'dropout': 0.18304140672383426}. Best is trial 29 with value: 3.183743715286255.
[I 2026-06-09 13:43:27,005] Trial 84 pruned.
[I 2026-06-09 13:43:30,895] Trial 85 pruned.
[I 2026-06-09 13:43:35,981] Trial 86 pruned.
[I 2026-06-09 13:43:38,786] Trial 87 pruned.
[I 2026-06-09 13:43:42,407] Trial 88 finished with value: 3.2329654693603516 and parameters: {'hidden_size': 32, 'lr': 0.004739095501309697, 'batch_size': 32, 'weight_decay': 0.00028941589069195417, 'dropout': 0.1774410521498451}. Best is trial 29 with value: 3.183743715286255.
[I 2026-06-09 13:43:45,945] Trial 89 pruned.
[I 2026-06-09 13:43:51,036] Trial 90 pruned.
[I 2026-06-09 13:43:55,928] Trial 91 pruned.
[I 2026-06-09 13:44:00,836] Trial 92 finished with value: 3.195021390914917 and parameters: {'hidden_size': 32, 'lr': 0.0024268416106403468, 'batch_size': 16, 'weight_decay': 0.0005445488725765073, 'dropout': 0.1681501571313733}. Best is trial 29 with value: 3.183743715286255.
[I 2026-06-09 13:44:08,118] Trial 93 finished with value: 3.195801019668579 and parameters: {'hidden_size': 32, 'lr': 0.001614727591776754, 'batch_size': 16, 'weight_decay': 0.0009967198101921188, 'dropout': 0.20246155238616953}. Best is trial 29 with value: 3.183743715286255.
[I 2026-06-09 13:44:13,062] Trial 94 pruned.
[I 2026-06-09 13:44:19,716] Trial 95 finished with value: 3.1859776973724365 and parameters: {'hidden_size': 32, 'lr': 0.002884869206884815, 'batch_size': 16, 'weight_decay': 0.0005066899052191753, 'dropout': 0.11257742281788267}. Best is trial 29 with value: 3.183743715286255.
[I 2026-06-09 13:44:23,118] Trial 96 pruned.
[I 2026-06-09 13:44:30,127] Trial 97 finished with value: 3.193338394165039 and parameters: {'hidden_size': 64, 'lr': 0.002918926091292312, 'batch_size': 64, 'weight_decay': 0.000713772504355047, 'dropout': 0.11351459916392187}. Best is trial 29 with value: 3.183743715286255.
[I 2026-06-09 13:44:34,928] Trial 98 pruned.
[I 2026-06-09 13:44:38,459] Trial 99 pruned.

Best Params for MIB: {'hidden_size': 64, 'lr': 0.0047639846588888755, 'batch_size': 32, 'weight_decay': 0.0004627785003174142, 'dropout': 0.137398162298415}

MIB - Total Test MAE: 1.1194 ± 0.5330
--- Dedicated Pipeline: Mid-cap (L1) ---

[I 2026-06-09 13:46:15,458] A new study created in memory with name: mtl_imp_Mid-cap
[I 2026-06-09 13:46:20,249] Trial 0 finished with value: 1.3854198455810547 and parameters: {'hidden_size': 64, 'lr': 0.0007760041563306649, 'batch_size': 32, 'weight_decay': 0.00032688538898296537, 'dropout': 0.11462011092617184}. Best is trial 0 with value: 1.3854198455810547.
[I 2026-06-09 13:46:25,663] Trial 1 finished with value: 1.3796652555465698 and parameters: {'hidden_size': 32, 'lr': 0.0023475976550181347, 'batch_size': 64, 'weight_decay': 0.0008037673215877992, 'dropout': 0.10280236130787435}. Best is trial 1 with value: 1.3796652555465698.
[I 2026-06-09 13:46:29,413] Trial 2 finished with value: 1.405164361000061 and parameters: {'hidden_size': 64, 'lr': 0.0005172517117526508, 'batch_size': 32, 'weight_decay': 5.21249595830484e-05, 'dropout': 0.10665703567990432}. Best is trial 1 with value: 1.3796652555465698.
[I 2026-06-09 13:46:34,169] Trial 3 finished with value: 1.3795342445373535 and parameters: {'hidden_size': 64, 'lr': 0.0037119330433934487, 'batch_size': 32, 'weight_decay': 6.598982603840384e-06, 'dropout': 0.20723175899906898}. Best is trial 3 with value: 1.3795342445373535.
[I 2026-06-09 13:46:40,782] Trial 4 finished with value: 1.381734848022461 and parameters: {'hidden_size': 32, 'lr': 0.0002231080484554408, 'batch_size': 16, 'weight_decay': 1.1064956143385574e-05, 'dropout': 0.14429989922984054}. Best is trial 3 with value: 1.3795342445373535.
[I 2026-06-09 13:46:47,823] Trial 5 finished with value: 1.4099291563034058 and parameters: {'hidden_size': 32, 'lr': 0.0019769456819851076, 'batch_size': 16, 'weight_decay': 7.022868595609067e-05, 'dropout': 0.1657429998053072}. Best is trial 3 with value: 1.3795342445373535.
[I 2026-06-09 13:46:53,933] Trial 6 finished with value: 1.4076083898544312 and parameters: {'hidden_size': 128, 'lr': 0.0013040505968153792, 'batch_size': 16, 'weight_decay': 0.00024409017700172575, 'dropout': 0.41423395888360526}. Best is trial 3 with value: 1.3795342445373535.
[I 2026-06-09 13:47:02,584] Trial 7 finished with value: 1.3827710151672363 and parameters: {'hidden_size': 32, 'lr': 0.0031970794859084452, 'batch_size': 32, 'weight_decay': 0.000675602546781786, 'dropout': 0.3664306170891124}. Best is trial 3 with value: 1.3795342445373535.
[I 2026-06-09 13:47:17,555] Trial 8 finished with value: 1.4049960374832153 and parameters: {'hidden_size': 64, 'lr': 0.00016269884652988855, 'batch_size': 16, 'weight_decay': 3.7084926338205987e-06, 'dropout': 0.25186267546412894}. Best is trial 3 with value: 1.3795342445373535.
[I 2026-06-09 13:47:25,189] Trial 9 finished with value: 1.3786158561706543 and parameters: {'hidden_size': 32, 'lr': 0.00554754268455156, 'batch_size': 16, 'weight_decay': 3.910142854513963e-05, 'dropout': 0.2503566875806422}. Best is trial 9 with value: 1.3786158561706543.
[I 2026-06-09 13:47:30,117] Trial 10 finished with value: 1.3837518692016602 and parameters: {'hidden_size': 128, 'lr': 0.0099636460351796, 'batch_size': 64, 'weight_decay': 1.149269201967523e-06, 'dropout': 0.4919146118354183}. Best is trial 9 with value: 1.3786158561706543.
[I 2026-06-09 13:47:34,995] Trial 11 finished with value: 1.392459750175476 and parameters: {'hidden_size': 64, 'lr': 0.008724507815147243, 'batch_size': 32, 'weight_decay': 1.3438768770820905e-05, 'dropout': 0.24086235958020807}. Best is trial 9 with value: 1.3786158561706543.
[I 2026-06-09 13:47:42,344] Trial 12 finished with value: 1.3965858221054077 and parameters: {'hidden_size': 32, 'lr': 0.004812108589851203, 'batch_size': 16, 'weight_decay': 2.3251431225767593e-05, 'dropout': 0.24922006804145594}. Best is trial 9 with value: 1.3786158561706543.
[I 2026-06-09 13:47:47,030] Trial 13 finished with value: 1.3845361471176147 and parameters: {'hidden_size': 64, 'lr': 0.0046356988721208935, 'batch_size': 32, 'weight_decay': 3.142286563496263e-06, 'dropout': 0.3234669694963784}. Best is trial 9 with value: 1.3786158561706543.
[I 2026-06-09 13:47:51,706] Trial 14 finished with value: 1.3760648965835571 and parameters: {'hidden_size': 128, 'lr': 0.004771932737555349, 'batch_size': 64, 'weight_decay': 6.199299352360339e-05, 'dropout': 0.19808728371509407}. Best is trial 14 with value: 1.3760648965835571.
[I 2026-06-09 13:47:56,464] Trial 15 finished with value: 1.3808064460754395 and parameters: {'hidden_size': 128, 'lr': 0.006533642000658437, 'batch_size': 64, 'weight_decay': 9.469218971003695e-05, 'dropout': 0.2984279079473505}. Best is trial 14 with value: 1.3760648965835571.
[I 2026-06-09 13:47:59,750] Trial 16 finished with value: 1.3903498649597168 and parameters: {'hidden_size': 128, 'lr': 0.001476547359545534, 'batch_size': 64, 'weight_decay': 3.554901238991103e-05, 'dropout': 0.18901887932547595}. Best is trial 14 with value: 1.3760648965835571.
[I 2026-06-09 13:48:04,599] Trial 17 finished with value: 1.3819656372070312 and parameters: {'hidden_size': 128, 'lr': 0.005792363759787663, 'batch_size': 64, 'weight_decay': 0.00017010493682109652, 'dropout': 0.29273916708002934}. Best is trial 14 with value: 1.3760648965835571.
[I 2026-06-09 13:48:09,431] Trial 18 pruned.
[I 2026-06-09 13:48:18,484] Trial 19 finished with value: 1.3910619020462036 and parameters: {'hidden_size': 128, 'lr': 0.0026975668151823637, 'batch_size': 16, 'weight_decay': 2.511958389976215e-05, 'dropout': 0.3578849290625342}. Best is trial 14 with value: 1.3760648965835571.
[I 2026-06-09 13:48:23,445] Trial 20 pruned.
[I 2026-06-09 13:48:28,801] Trial 21 finished with value: 1.3994988203048706 and parameters: {'hidden_size': 64, 'lr': 0.0036870699213526225, 'batch_size': 32, 'weight_decay': 1.1723963331270868e-05, 'dropout': 0.203006246222529}. Best is trial 14 with value: 1.3760648965835571.
[I 2026-06-09 13:48:34,352] Trial 22 finished with value: 1.3835798501968384 and parameters: {'hidden_size': 64, 'lr': 0.007086056183660322, 'batch_size': 16, 'weight_decay': 5.104814094538304e-06, 'dropout': 0.2747796355547908}. Best is trial 14 with value: 1.3760648965835571.
[I 2026-06-09 13:48:38,334] Trial 23 finished with value: 1.3755091428756714 and parameters: {'hidden_size': 32, 'lr': 0.00392218282600513, 'batch_size': 32, 'weight_decay': 1.2289000030390197e-06, 'dropout': 0.21878637401830048}. Best is trial 23 with value: 1.3755091428756714.
[I 2026-06-09 13:48:43,462] Trial 24 finished with value: 1.3940852880477905 and parameters: {'hidden_size': 32, 'lr': 0.0016544003035334554, 'batch_size': 64, 'weight_decay': 1.080787071893955e-06, 'dropout': 0.22399718625447956}. Best is trial 23 with value: 1.3755091428756714.
[I 2026-06-09 13:48:47,816] Trial 25 finished with value: 1.4312041997909546 and parameters: {'hidden_size': 32, 'lr': 0.004518434247915782, 'batch_size': 32, 'weight_decay': 2.1777617870926393e-06, 'dropout': 0.18079075628591046}. Best is trial 23 with value: 1.3755091428756714.
[I 2026-06-09 13:48:54,103] Trial 26 finished with value: 1.4382715225219727 and parameters: {'hidden_size': 32, 'lr': 0.002696695732382966, 'batch_size': 16, 'weight_decay': 1.9413129078942466e-05, 'dropout': 0.2686412910478345}. Best is trial 23 with value: 1.3755091428756714.
[I 2026-06-09 13:48:58,855] Trial 27 finished with value: 1.3837767839431763 and parameters: {'hidden_size': 32, 'lr': 0.007286854211641528, 'batch_size': 64, 'weight_decay': 0.00037779942850726093, 'dropout': 0.326975184029044}. Best is trial 23 with value: 1.3755091428756714.
[I 2026-06-09 13:49:04,035] Trial 28 pruned.
[I 2026-06-09 13:49:13,791] Trial 29 finished with value: 1.3983079195022583 and parameters: {'hidden_size': 128, 'lr': 0.0011010374007000678, 'batch_size': 16, 'weight_decay': 0.00045189998536865664, 'dropout': 0.13149384312808637}. Best is trial 23 with value: 1.3755091428756714.
[I 2026-06-09 13:49:19,288] Trial 30 pruned.
[I 2026-06-09 13:49:25,370] Trial 31 finished with value: 1.394234538078308 and parameters: {'hidden_size': 64, 'lr': 0.003676103399274197, 'batch_size': 32, 'weight_decay': 6.076120075349756e-06, 'dropout': 0.19768515100699918}. Best is trial 23 with value: 1.3755091428756714.
[I 2026-06-09 13:49:30,635] Trial 32 finished with value: 1.391013741493225 and parameters: {'hidden_size': 64, 'lr': 0.003545155438935267, 'batch_size': 32, 'weight_decay': 7.576065361798276e-06, 'dropout': 0.1769643594851658}. Best is trial 23 with value: 1.3755091428756714.
[I 2026-06-09 13:49:38,178] Trial 33 finished with value: 1.3922048807144165 and parameters: {'hidden_size': 32, 'lr': 0.001991273235623587, 'batch_size': 32, 'weight_decay': 1.7270526810482584e-06, 'dropout': 0.20972712620083342}. Best is trial 23 with value: 1.3755091428756714.
[I 2026-06-09 13:49:44,063] Trial 34 finished with value: 1.4049530029296875 and parameters: {'hidden_size': 64, 'lr': 0.004132898061627463, 'batch_size': 32, 'weight_decay': 3.2485195452499764e-05, 'dropout': 0.12037722867949051}. Best is trial 23 with value: 1.3755091428756714.
[I 2026-06-09 13:49:51,330] Trial 35 pruned.
[I 2026-06-09 13:49:58,065] Trial 36 finished with value: 1.4118375778198242 and parameters: {'hidden_size': 128, 'lr': 0.0005684665134999183, 'batch_size': 16, 'weight_decay': 8.347529398345116e-06, 'dropout': 0.16047342832413014}. Best is trial 23 with value: 1.3755091428756714.
[I 2026-06-09 13:50:02,520] Trial 37 finished with value: 1.389910340309143 and parameters: {'hidden_size': 32, 'lr': 0.007709955956126164, 'batch_size': 64, 'weight_decay': 5.8642434402137395e-05, 'dropout': 0.22905834384124904}. Best is trial 23 with value: 1.3755091428756714.
[I 2026-06-09 13:50:07,442] Trial 38 finished with value: 1.3733106851577759 and parameters: {'hidden_size': 64, 'lr': 0.005426748767587874, 'batch_size': 32, 'weight_decay': 3.6520300079748134e-06, 'dropout': 0.2908379909201838}. Best is trial 38 with value: 1.3733106851577759.
[I 2026-06-09 13:50:12,352] Trial 39 finished with value: 1.3901114463806152 and parameters: {'hidden_size': 64, 'lr': 0.005591115511462178, 'batch_size': 32, 'weight_decay': 1.4745277513941973e-06, 'dropout': 0.30158532055967024}. Best is trial 38 with value: 1.3733106851577759.
[I 2026-06-09 13:50:20,879] Trial 40 finished with value: 1.3814282417297363 and parameters: {'hidden_size': 128, 'lr': 0.008709222087212885, 'batch_size': 16, 'weight_decay': 2.8238168578614906e-06, 'dropout': 0.4003945526865071}. Best is trial 38 with value: 1.3733106851577759.
[I 2026-06-09 13:50:25,160] Trial 41 finished with value: 1.3849372863769531 and parameters: {'hidden_size': 64, 'lr': 0.003100720955921292, 'batch_size': 32, 'weight_decay': 3.5343658701514466e-06, 'dropout': 0.26862549609412834}. Best is trial 38 with value: 1.3733106851577759.
[I 2026-06-09 13:50:29,796] Trial 42 finished with value: 1.3980202674865723 and parameters: {'hidden_size': 64, 'lr': 0.005275248504549227, 'batch_size': 32, 'weight_decay': 4.475621506105417e-06, 'dropout': 0.24264332394991614}. Best is trial 38 with value: 1.3733106851577759.
[I 2026-06-09 13:50:36,132] Trial 43 finished with value: 1.3924245834350586 and parameters: {'hidden_size': 64, 'lr': 0.002075890721704845, 'batch_size': 32, 'weight_decay': 8.242560843224457e-06, 'dropout': 0.2802856121074673}. Best is trial 38 with value: 1.3733106851577759.
[I 2026-06-09 13:50:41,139] Trial 44 finished with value: 1.394809603691101 and parameters: {'hidden_size': 64, 'lr': 0.00401574901325978, 'batch_size': 32, 'weight_decay': 1.461754965318998e-06, 'dropout': 0.20624599382723133}. Best is trial 38 with value: 1.3733106851577759.
[I 2026-06-09 13:50:49,079] Trial 45 pruned.
[I 2026-06-09 13:50:54,603] Trial 46 finished with value: 1.3911371231079102 and parameters: {'hidden_size': 64, 'lr': 0.008654530337517792, 'batch_size': 16, 'weight_decay': 0.00020715274440729739, 'dropout': 0.32382450084117054}. Best is trial 38 with value: 1.3733106851577759.
[I 2026-06-09 13:50:59,584] Trial 47 finished with value: 1.4025825262069702 and parameters: {'hidden_size': 128, 'lr': 0.00012684986379629743, 'batch_size': 64, 'weight_decay': 2.4948403077614644e-06, 'dropout': 0.3087291083379994}. Best is trial 38 with value: 1.3733106851577759.
[I 2026-06-09 13:51:05,154] Trial 48 finished with value: 1.3968461751937866 and parameters: {'hidden_size': 32, 'lr': 0.004798116969816668, 'batch_size': 32, 'weight_decay': 0.00012390094028248222, 'dropout': 0.24840000864824183}. Best is trial 38 with value: 1.3733106851577759.
[I 2026-06-09 13:51:08,614] Trial 49 finished with value: 1.4124013185501099 and parameters: {'hidden_size': 64, 'lr': 0.0024865348293448674, 'batch_size': 64, 'weight_decay': 4.6585843806514436e-05, 'dropout': 0.10081249745245091}. Best is trial 38 with value: 1.3733106851577759.
[I 2026-06-09 13:51:15,433] Trial 50 finished with value: 1.3854535818099976 and parameters: {'hidden_size': 128, 'lr': 0.009773663320347344, 'batch_size': 16, 'weight_decay': 2.8063278138424654e-05, 'dropout': 0.19213435993513234}. Best is trial 38 with value: 1.3733106851577759.
[I 2026-06-09 13:51:19,457] Trial 51 pruned.
[I 2026-06-09 13:51:25,090] Trial 52 finished with value: 1.4019979238510132 and parameters: {'hidden_size': 32, 'lr': 0.0034552454541221934, 'batch_size': 64, 'weight_decay': 0.0006368399201791893, 'dropout': 0.1695316674103235}. Best is trial 38 with value: 1.3733106851577759.
[I 2026-06-09 13:51:30,643] Trial 53 pruned.
[I 2026-06-09 13:51:38,527] Trial 54 finished with value: 1.392317771911621 and parameters: {'hidden_size': 32, 'lr': 0.0013739466750399406, 'batch_size': 64, 'weight_decay': 1.5127907795094277e-05, 'dropout': 0.14433524166724965}. Best is trial 38 with value: 1.3733106851577759.
[I 2026-06-09 13:51:43,852] Trial 55 pruned.
[I 2026-06-09 13:51:51,002] Trial 56 finished with value: 1.3965559005737305 and parameters: {'hidden_size': 128, 'lr': 0.003011461660225073, 'batch_size': 16, 'weight_decay': 1.0859980000942757e-05, 'dropout': 0.29190711252058166}. Best is trial 38 with value: 1.3733106851577759.
[I 2026-06-09 13:51:55,537] Trial 57 finished with value: 1.3939834833145142 and parameters: {'hidden_size': 64, 'lr': 0.004360920365824854, 'batch_size': 32, 'weight_decay': 1.0606623990462911e-06, 'dropout': 0.21919386300960136}. Best is trial 38 with value: 1.3733106851577759.
[I 2026-06-09 13:51:59,419] Trial 58 finished with value: 1.4038915634155273 and parameters: {'hidden_size': 32, 'lr': 0.002427972893917988, 'batch_size': 64, 'weight_decay': 3.955707751452033e-06, 'dropout': 0.11744047286884456}. Best is trial 38 with value: 1.3733106851577759.
[I 2026-06-09 13:52:04,425] Trial 59 pruned.
[I 2026-06-09 13:52:09,730] Trial 60 finished with value: 1.382267951965332 and parameters: {'hidden_size': 128, 'lr': 0.003266553807109758, 'batch_size': 16, 'weight_decay': 0.00030670455931727623, 'dropout': 0.18394211864142784}. Best is trial 38 with value: 1.3733106851577759.
[I 2026-06-09 13:52:14,339] Trial 61 finished with value: 1.3891457319259644 and parameters: {'hidden_size': 128, 'lr': 0.0069797523457303485, 'batch_size': 64, 'weight_decay': 8.337297890853298e-05, 'dropout': 0.28972527676921994}. Best is trial 38 with value: 1.3733106851577759.
[I 2026-06-09 13:52:18,683] Trial 62 finished with value: 1.3903154134750366 and parameters: {'hidden_size': 128, 'lr': 0.006350878304598395, 'batch_size': 64, 'weight_decay': 0.00014120603951155766, 'dropout': 0.28061846072706875}. Best is trial 38 with value: 1.3733106851577759.
[I 2026-06-09 13:52:23,516] Trial 63 pruned.
[I 2026-06-09 13:52:29,322] Trial 64 finished with value: 1.3933073282241821 and parameters: {'hidden_size': 128, 'lr': 0.0038391841080096865, 'batch_size': 64, 'weight_decay': 3.852460086344642e-05, 'dropout': 0.31538878095086564}. Best is trial 38 with value: 1.3733106851577759.
[I 2026-06-09 13:52:33,368] Trial 65 finished with value: 1.389743685722351 and parameters: {'hidden_size': 64, 'lr': 0.004465858695255656, 'batch_size': 64, 'weight_decay': 2.165540166167142e-05, 'dropout': 0.21305061083808918}. Best is trial 38 with value: 1.3733106851577759.
[I 2026-06-09 13:52:38,639] Trial 66 finished with value: 1.4109951257705688 and parameters: {'hidden_size': 32, 'lr': 0.007658733100902504, 'batch_size': 32, 'weight_decay': 0.0004927080744458387, 'dropout': 0.14933975304825237}. Best is trial 38 with value: 1.3733106851577759.
[I 2026-06-09 13:52:43,377] Trial 67 finished with value: 1.4091216325759888 and parameters: {'hidden_size': 128, 'lr': 0.005996779175497821, 'batch_size': 64, 'weight_decay': 0.00011513884135397783, 'dropout': 0.2616275933293209}. Best is trial 38 with value: 1.3733106851577759.
[I 2026-06-09 13:52:48,435] Trial 68 finished with value: 1.3967968225479126 and parameters: {'hidden_size': 32, 'lr': 0.005299971966605349, 'batch_size': 32, 'weight_decay': 0.000964514360556039, 'dropout': 0.4496787181361269}. Best is trial 38 with value: 1.3733106851577759.
[I 2026-06-09 13:52:55,025] Trial 69 pruned.
[I 2026-06-09 13:53:00,271] Trial 70 finished with value: 1.3901928663253784 and parameters: {'hidden_size': 128, 'lr': 0.004055286722828324, 'batch_size': 32, 'weight_decay': 1.1439274966072238e-05, 'dropout': 0.22732712774451871}. Best is trial 38 with value: 1.3733106851577759.
[I 2026-06-09 13:53:05,791] Trial 71 finished with value: 1.383662223815918 and parameters: {'hidden_size': 128, 'lr': 0.007855967096290994, 'batch_size': 16, 'weight_decay': 6.408639290534308e-06, 'dropout': 0.38882365225764415}. Best is trial 38 with value: 1.3733106851577759.
[I 2026-06-09 13:53:15,016] Trial 72 finished with value: 1.385828971862793 and parameters: {'hidden_size': 128, 'lr': 0.008168216758512066, 'batch_size': 16, 'weight_decay': 2.759219140673193e-06, 'dropout': 0.34018234394836283}. Best is trial 38 with value: 1.3733106851577759.
[I 2026-06-09 13:53:23,264] Trial 73 finished with value: 1.3757370710372925 and parameters: {'hidden_size': 128, 'lr': 0.009873793677354447, 'batch_size': 16, 'weight_decay': 3.104379439741139e-06, 'dropout': 0.4527520099882422}. Best is trial 38 with value: 1.3733106851577759.
[I 2026-06-09 13:53:33,120] Trial 74 finished with value: 1.3837013244628906 and parameters: {'hidden_size': 128, 'lr': 0.0063999580839775435, 'batch_size': 16, 'weight_decay': 2.1799753427232764e-06, 'dropout': 0.4254288049994142}. Best is trial 38 with value: 1.3733106851577759.
[I 2026-06-09 13:53:38,464] Trial 75 finished with value: 1.3905609846115112 and parameters: {'hidden_size': 128, 'lr': 0.00972945453248978, 'batch_size': 16, 'weight_decay': 3.3078878963352936e-06, 'dropout': 0.13221290758274362}. Best is trial 38 with value: 1.3733106851577759.
[I 2026-06-09 13:53:43,011] Trial 76 finished with value: 1.4034045934677124 and parameters: {'hidden_size': 64, 'lr': 0.0047189375528314285, 'batch_size': 32, 'weight_decay': 1.4382429435596318e-06, 'dropout': 0.19675279411899982}. Best is trial 38 with value: 1.3733106851577759.
[I 2026-06-09 13:53:50,085] Trial 77 finished with value: 1.3998533487319946 and parameters: {'hidden_size': 32, 'lr': 0.0028153564011985438, 'batch_size': 16, 'weight_decay': 4.471410236545315e-06, 'dropout': 0.1756290852554188}. Best is trial 38 with value: 1.3733106851577759.
[I 2026-06-09 13:53:56,096] Trial 78 finished with value: 1.3954310417175293 and parameters: {'hidden_size': 64, 'lr': 0.005486799511349797, 'batch_size': 64, 'weight_decay': 4.0853695706267474e-05, 'dropout': 0.4625086286702244}. Best is trial 38 with value: 1.3733106851577759.
[I 2026-06-09 13:54:01,269] Trial 79 finished with value: 1.388288140296936 and parameters: {'hidden_size': 128, 'lr': 0.003447593689188663, 'batch_size': 32, 'weight_decay': 0.00016540166167382125, 'dropout': 0.24588647799443328}. Best is trial 38 with value: 1.3733106851577759.
[I 2026-06-09 13:54:05,972] Trial 80 finished with value: 1.378318428993225 and parameters: {'hidden_size': 32, 'lr': 0.007044850431881941, 'batch_size': 64, 'weight_decay': 3.045136570032521e-05, 'dropout': 0.3023656783768205}. Best is trial 38 with value: 1.3733106851577759.

Best Params for Mid-cap: {'hidden_size': 64, 'lr': 0.005426748767587874, 'batch_size': 32, 'weight_decay': 3.6520300079748134e-06, 'dropout': 0.2908379909201838}

Mid-cap - Total Test MAE: 1.2394 ± 0.5697
--- Dedicated Pipeline: Small-cap (L1) ---

[I 2026-06-09 13:57:30,157] A new study created in memory with name: mtl_imp_Small-cap
[I 2026-06-09 13:57:42,166] Trial 0 finished with value: 13.257041931152344 and parameters: {'hidden_size': 64, 'lr': 0.005848022240010461, 'batch_size': 16, 'weight_decay': 3.736112590892339e-06, 'dropout': 0.3433044313153144}. Best is trial 0 with value: 13.257041931152344.
[I 2026-06-09 13:57:53,661] Trial 1 finished with value: 13.288570404052734 and parameters: {'hidden_size': 32, 'lr': 0.0015539476187347461, 'batch_size': 16, 'weight_decay': 4.5568320096635844e-05, 'dropout': 0.2718966340549591}. Best is trial 0 with value: 13.257041931152344.
[I 2026-06-09 13:58:07,763] Trial 2 finished with value: 13.258105278015137 and parameters: {'hidden_size': 32, 'lr': 0.00419146898779243, 'batch_size': 16, 'weight_decay': 2.272519836209071e-06, 'dropout': 0.1319286950823879}. Best is trial 0 with value: 13.257041931152344.
[I 2026-06-09 13:58:32,269] Trial 3 finished with value: 13.247562408447266 and parameters: {'hidden_size': 32, 'lr': 0.0003982073272685544, 'batch_size': 64, 'weight_decay': 6.707613819888943e-05, 'dropout': 0.18858105345548154}. Best is trial 3 with value: 13.247562408447266.
[I 2026-06-09 13:58:45,696] Trial 4 finished with value: 13.254721641540527 and parameters: {'hidden_size': 128, 'lr': 0.00988483104444834, 'batch_size': 64, 'weight_decay': 4.276877923361183e-06, 'dropout': 0.2314781902606678}. Best is trial 3 with value: 13.247562408447266.
[I 2026-06-09 13:59:04,917] Trial 5 finished with value: 13.276092529296875 and parameters: {'hidden_size': 32, 'lr': 0.0008328677294596044, 'batch_size': 64, 'weight_decay': 1.2556604412949375e-05, 'dropout': 0.3540063457349205}. Best is trial 3 with value: 13.247562408447266.
[I 2026-06-09 13:59:45,197] Trial 6 finished with value: 13.273951530456543 and parameters: {'hidden_size': 32, 'lr': 0.00042496458675079986, 'batch_size': 16, 'weight_decay': 0.00020502732949143868, 'dropout': 0.4992077187361267}. Best is trial 3 with value: 13.247562408447266.
[I 2026-06-09 14:00:00,651] Trial 7 finished with value: 13.317721366882324 and parameters: {'hidden_size': 64, 'lr': 0.00041137598823505066, 'batch_size': 16, 'weight_decay': 1.34064100513637e-06, 'dropout': 0.10318130955831868}. Best is trial 3 with value: 13.247562408447266.
[I 2026-06-09 14:00:09,016] Trial 8 finished with value: 13.255854606628418 and parameters: {'hidden_size': 128, 'lr': 0.002682600897115114, 'batch_size': 32, 'weight_decay': 0.0007664665838731778, 'dropout': 0.22520323306966974}. Best is trial 3 with value: 13.247562408447266.
[I 2026-06-09 14:00:25,036] Trial 9 finished with value: 13.259769439697266 and parameters: {'hidden_size': 128, 'lr': 0.005780424537518324, 'batch_size': 16, 'weight_decay': 5.098167689766668e-06, 'dropout': 0.45648767121172407}. Best is trial 3 with value: 13.247562408447266.
[I 2026-06-09 14:00:32,678] Trial 10 pruned.
[I 2026-06-09 14:00:53,689] Trial 11 pruned.
[I 2026-06-09 14:01:01,692] Trial 12 finished with value: 13.2564115524292 and parameters: {'hidden_size': 128, 'lr': 0.009473927248609319, 'batch_size': 64, 'weight_decay': 0.00014511584573984878, 'dropout': 0.19081721153318632}. Best is trial 3 with value: 13.247562408447266.
[I 2026-06-09 14:01:11,678] Trial 13 finished with value: 13.242308616638184 and parameters: {'hidden_size': 128, 'lr': 0.0012166808363442572, 'batch_size': 64, 'weight_decay': 9.439937279767432e-06, 'dropout': 0.2700727008349456}. Best is trial 13 with value: 13.242308616638184.
[I 2026-06-09 14:01:24,148] Trial 14 finished with value: 13.268844604492188 and parameters: {'hidden_size': 64, 'lr': 0.0008707432844517858, 'batch_size': 32, 'weight_decay': 0.00014383809844561567, 'dropout': 0.2927129344707238}. Best is trial 13 with value: 13.242308616638184.
[I 2026-06-09 14:01:31,694] Trial 15 pruned.
[I 2026-06-09 14:01:39,948] Trial 16 finished with value: 13.258286476135254 and parameters: {'hidden_size': 128, 'lr': 0.0017899168428139474, 'batch_size': 64, 'weight_decay': 0.0006364384348835527, 'dropout': 0.2975162127201281}. Best is trial 13 with value: 13.242308616638184.
[I 2026-06-09 14:01:47,886] Trial 17 pruned.
[I 2026-06-09 14:01:56,965] Trial 18 pruned.
[I 2026-06-09 14:02:14,629] Trial 19 finished with value: 13.264132499694824 and parameters: {'hidden_size': 64, 'lr': 0.0006133394516030766, 'batch_size': 64, 'weight_decay': 8.606510896920639e-05, 'dropout': 0.3991400851756949}. Best is trial 13 with value: 13.242308616638184.
[I 2026-06-09 14:02:22,694] Trial 20 pruned.
[I 2026-06-09 14:02:32,640] Trial 21 finished with value: 13.251757621765137 and parameters: {'hidden_size': 128, 'lr': 0.0026666237013172984, 'batch_size': 64, 'weight_decay': 5.381906504020547e-06, 'dropout': 0.2357944178709294}. Best is trial 13 with value: 13.242308616638184.
[I 2026-06-09 14:02:42,010] Trial 22 finished with value: 13.247169494628906 and parameters: {'hidden_size': 128, 'lr': 0.0029110599396308333, 'batch_size': 64, 'weight_decay': 1.8419949769951825e-05, 'dropout': 0.3132951988390351}. Best is trial 13 with value: 13.242308616638184.
[I 2026-06-09 14:02:50,947] Trial 23 finished with value: 13.2731351852417 and parameters: {'hidden_size': 128, 'lr': 0.001605833412504775, 'batch_size': 64, 'weight_decay': 2.3065679624450593e-05, 'dropout': 0.32433409560993626}. Best is trial 13 with value: 13.242308616638184.
[I 2026-06-09 14:03:00,063] Trial 24 finished with value: 13.24681568145752 and parameters: {'hidden_size': 128, 'lr': 0.0026692626346093854, 'batch_size': 64, 'weight_decay': 2.5507353584763968e-05, 'dropout': 0.27662854492313305}. Best is trial 13 with value: 13.242308616638184.
[I 2026-06-09 14:03:07,966] Trial 25 finished with value: 13.265652656555176 and parameters: {'hidden_size': 128, 'lr': 0.003027303915509756, 'batch_size': 32, 'weight_decay': 2.3256712918277105e-05, 'dropout': 0.30794226246123035}. Best is trial 13 with value: 13.242308616638184.
[I 2026-06-09 14:03:16,255] Trial 26 finished with value: 13.265155792236328 and parameters: {'hidden_size': 128, 'lr': 0.0011969357306511757, 'batch_size': 64, 'weight_decay': 1.0199618097268783e-05, 'dropout': 0.2675101776545153}. Best is trial 13 with value: 13.242308616638184.
[I 2026-06-09 14:03:26,746] Trial 27 finished with value: 13.24504566192627 and parameters: {'hidden_size': 128, 'lr': 0.0022021920705207676, 'batch_size': 64, 'weight_decay': 7.385610860902233e-06, 'dropout': 0.38042843213263955}. Best is trial 13 with value: 13.242308616638184.
[I 2026-06-09 14:03:36,221] Trial 28 finished with value: 13.272242546081543 and parameters: {'hidden_size': 128, 'lr': 0.0019163275200069366, 'batch_size': 64, 'weight_decay': 1.021512263506679e-06, 'dropout': 0.4194283103320916}. Best is trial 13 with value: 13.242308616638184.
[I 2026-06-09 14:03:47,038] Trial 29 finished with value: 13.257428169250488 and parameters: {'hidden_size': 64, 'lr': 0.004840924561189457, 'batch_size': 32, 'weight_decay': 6.674666402844312e-06, 'dropout': 0.35090377840397924}. Best is trial 13 with value: 13.242308616638184.
[I 2026-06-09 14:03:56,355] Trial 30 finished with value: 13.264617919921875 and parameters: {'hidden_size': 128, 'lr': 0.003782898198311416, 'batch_size': 64, 'weight_decay': 1.9494242566503983e-06, 'dropout': 0.4399508691676431}. Best is trial 13 with value: 13.242308616638184.
[I 2026-06-09 14:04:05,823] Trial 31 finished with value: 13.258979797363281 and parameters: {'hidden_size': 128, 'lr': 0.002247376257908739, 'batch_size': 64, 'weight_decay': 1.8415705330905934e-05, 'dropout': 0.3639170132099324}. Best is trial 13 with value: 13.242308616638184.
[I 2026-06-09 14:04:15,889] Trial 32 finished with value: 13.250134468078613 and parameters: {'hidden_size': 128, 'lr': 0.0013234349256883644, 'batch_size': 64, 'weight_decay': 3.4788762821697044e-05, 'dropout': 0.3259890020345097}. Best is trial 13 with value: 13.242308616638184.
[I 2026-06-09 14:04:24,564] Trial 33 finished with value: 13.248570442199707 and parameters: {'hidden_size': 128, 'lr': 0.003484578392940421, 'batch_size': 64, 'weight_decay': 7.695957534734816e-06, 'dropout': 0.2797350470692249}. Best is trial 13 with value: 13.242308616638184.
[I 2026-06-09 14:04:36,698] Trial 34 finished with value: 13.258221626281738 and parameters: {'hidden_size': 128, 'lr': 0.006951388610686194, 'batch_size': 64, 'weight_decay': 3.067147511695625e-06, 'dropout': 0.32716920217343876}. Best is trial 13 with value: 13.242308616638184.
[I 2026-06-09 14:04:48,566] Trial 35 finished with value: 13.256970405578613 and parameters: {'hidden_size': 128, 'lr': 0.002138110145782755, 'batch_size': 16, 'weight_decay': 1.858761230529781e-05, 'dropout': 0.26528943045191394}. Best is trial 13 with value: 13.242308616638184.
[I 2026-06-09 14:05:01,011] Trial 36 finished with value: 13.248576164245605 and parameters: {'hidden_size': 128, 'lr': 0.004599191445347665, 'batch_size': 64, 'weight_decay': 3.108715696551369e-06, 'dropout': 0.37953523700096226}. Best is trial 13 with value: 13.242308616638184.
[I 2026-06-09 14:05:10,480] Trial 37 finished with value: 13.255204200744629 and parameters: {'hidden_size': 128, 'lr': 0.0011996502882037192, 'batch_size': 64, 'weight_decay': 1.4776204583812379e-05, 'dropout': 0.31152144768568335}. Best is trial 13 with value: 13.242308616638184.
[I 2026-06-09 14:05:23,351] Trial 38 finished with value: 13.258102416992188 and parameters: {'hidden_size': 64, 'lr': 0.0015280500499315107, 'batch_size': 16, 'weight_decay': 3.207224113930978e-05, 'dropout': 0.24930483271931675}. Best is trial 13 with value: 13.242308616638184.
[I 2026-06-09 14:05:34,368] Trial 39 finished with value: 13.248454093933105 and parameters: {'hidden_size': 128, 'lr': 0.0006849038555483053, 'batch_size': 64, 'weight_decay': 7.515081914438448e-06, 'dropout': 0.34198262009597175}. Best is trial 13 with value: 13.242308616638184.
[I 2026-06-09 14:05:50,149] Trial 40 finished with value: 13.2551851272583 and parameters: {'hidden_size': 128, 'lr': 0.002727710747658073, 'batch_size': 64, 'weight_decay': 7.765552459746664e-05, 'dropout': 0.4905713267844018}. Best is trial 13 with value: 13.242308616638184.
[I 2026-06-09 14:05:57,689] Trial 41 pruned.
[I 2026-06-09 14:06:09,476] Trial 42 finished with value: 13.2674560546875 and parameters: {'hidden_size': 32, 'lr': 0.003341138085111124, 'batch_size': 64, 'weight_decay': 3.5471566586819453e-05, 'dropout': 0.15984047902346477}. Best is trial 13 with value: 13.242308616638184.
[I 2026-06-09 14:06:33,595] Trial 43 finished with value: 13.25915813446045 and parameters: {'hidden_size': 32, 'lr': 0.0022807526470096213, 'batch_size': 16, 'weight_decay': 9.578373410530174e-05, 'dropout': 0.28536053219134405}. Best is trial 13 with value: 13.242308616638184.
[I 2026-06-09 14:06:41,440] Trial 44 pruned.
[I 2026-06-09 14:06:53,381] Trial 45 finished with value: 13.25671100616455 and parameters: {'hidden_size': 32, 'lr': 0.005360750531250819, 'batch_size': 64, 'weight_decay': 9.136191926287453e-06, 'dropout': 0.10737841336665524}. Best is trial 13 with value: 13.242308616638184.
[I 2026-06-09 14:07:00,966] Trial 46 pruned.
[I 2026-06-09 14:07:15,885] Trial 47 pruned.
[I 2026-06-09 14:07:29,048] Trial 48 finished with value: 13.25389575958252 and parameters: {'hidden_size': 128, 'lr': 0.0006388591091754195, 'batch_size': 64, 'weight_decay': 5.5294206122402576e-05, 'dropout': 0.19579775215740952}. Best is trial 13 with value: 13.242308616638184.
[I 2026-06-09 14:07:40,882] Trial 49 pruned.
[I 2026-06-09 14:07:48,718] Trial 50 pruned.
[I 2026-06-09 14:08:00,634] Trial 51 finished with value: 13.259127616882324 and parameters: {'hidden_size': 128, 'lr': 0.0006761694058423096, 'batch_size': 64, 'weight_decay': 5.641280610559321e-06, 'dropout': 0.3410978727797767}. Best is trial 13 with value: 13.242308616638184.
[I 2026-06-09 14:08:08,911] Trial 52 pruned.
[I 2026-06-09 14:08:20,118] Trial 53 finished with value: 13.261691093444824 and parameters: {'hidden_size': 128, 'lr': 0.0006880532641391178, 'batch_size': 64, 'weight_decay': 2.0461553279000113e-06, 'dropout': 0.3939712775465668}. Best is trial 13 with value: 13.242308616638184.
[I 2026-06-09 14:08:28,147] Trial 54 pruned.
[I 2026-06-09 14:08:41,900] Trial 55 finished with value: 13.269185066223145 and parameters: {'hidden_size': 128, 'lr': 0.0005200339769852606, 'batch_size': 64, 'weight_decay': 6.69677879847138e-06, 'dropout': 0.2682841576895981}. Best is trial 13 with value: 13.242308616638184.
[I 2026-06-09 14:08:56,330] Trial 56 finished with value: 13.25204086303711 and parameters: {'hidden_size': 128, 'lr': 0.0007695789613516218, 'batch_size': 64, 'weight_decay': 0.0002091546053117374, 'dropout': 0.36440004998907605}. Best is trial 13 with value: 13.242308616638184.
[I 2026-06-09 14:09:07,804] Trial 57 finished with value: 13.267571449279785 and parameters: {'hidden_size': 128, 'lr': 0.0017369754368159818, 'batch_size': 32, 'weight_decay': 4.695722441139721e-05, 'dropout': 0.3208359883071296}. Best is trial 13 with value: 13.242308616638184.
[I 2026-06-09 14:09:36,060] Trial 58 finished with value: 13.257189750671387 and parameters: {'hidden_size': 64, 'lr': 0.00038542745420134313, 'batch_size': 64, 'weight_decay': 3.5660576764679843e-06, 'dropout': 0.23245581551270458}. Best is trial 13 with value: 13.242308616638184.
[I 2026-06-09 14:09:44,550] Trial 59 pruned.
[I 2026-06-09 14:09:52,422] Trial 60 finished with value: 13.265965461730957 and parameters: {'hidden_size': 128, 'lr': 0.0012565038427037004, 'batch_size': 64, 'weight_decay': 2.6989825445120776e-05, 'dropout': 0.3398865701499956}. Best is trial 13 with value: 13.242308616638184.
[I 2026-06-09 14:09:59,101] Trial 61 finished with value: 13.261894226074219 and parameters: {'hidden_size': 128, 'lr': 0.0036088953172187005, 'batch_size': 64, 'weight_decay': 7.03250602108362e-06, 'dropout': 0.27299851405364745}. Best is trial 13 with value: 13.242308616638184.
[I 2026-06-09 14:10:07,366] Trial 62 finished with value: 13.269347190856934 and parameters: {'hidden_size': 128, 'lr': 0.004016321779447687, 'batch_size': 64, 'weight_decay': 8.742372225445433e-06, 'dropout': 0.2798442363627579}. Best is trial 13 with value: 13.242308616638184.
[I 2026-06-09 14:10:17,349] Trial 63 finished with value: 13.242924690246582 and parameters: {'hidden_size': 128, 'lr': 0.002926050718449894, 'batch_size': 64, 'weight_decay': 1.261532718481105e-05, 'dropout': 0.30044340231175726}. Best is trial 13 with value: 13.242308616638184.
[I 2026-06-09 14:10:28,447] Trial 64 finished with value: 13.25560474395752 and parameters: {'hidden_size': 128, 'lr': 0.002682954336766329, 'batch_size': 64, 'weight_decay': 1.3498950786875323e-05, 'dropout': 0.30010907292190936}. Best is trial 13 with value: 13.242308616638184.
[I 2026-06-09 14:10:36,291] Trial 65 finished with value: 13.261836051940918 and parameters: {'hidden_size': 128, 'lr': 0.0014769281225824314, 'batch_size': 64, 'weight_decay': 2.013360927711532e-05, 'dropout': 0.3142587507845175}. Best is trial 13 with value: 13.242308616638184.
[I 2026-06-09 14:10:49,463] Trial 66 finished with value: 13.247676849365234 and parameters: {'hidden_size': 128, 'lr': 0.0021906876441379563, 'batch_size': 64, 'weight_decay': 1.1575904851578903e-05, 'dropout': 0.38226677164595596}. Best is trial 13 with value: 13.242308616638184.
[I 2026-06-09 14:11:04,348] Trial 67 finished with value: 13.256179809570312 and parameters: {'hidden_size': 32, 'lr': 0.0021203378152299312, 'batch_size': 32, 'weight_decay': 1.1957893476723846e-05, 'dropout': 0.47030730386955216}. Best is trial 13 with value: 13.242308616638184.
[I 2026-06-09 14:11:12,142] Trial 68 finished with value: 13.250140190124512 and parameters: {'hidden_size': 128, 'lr': 0.0030889292736118595, 'batch_size': 64, 'weight_decay': 1.4457003665263321e-05, 'dropout': 0.4168548014443888}. Best is trial 13 with value: 13.242308616638184.
[I 2026-06-09 14:11:29,511] Trial 69 finished with value: 13.241581916809082 and parameters: {'hidden_size': 128, 'lr': 0.0024073927504210404, 'batch_size': 16, 'weight_decay': 2.879599343783324e-05, 'dropout': 0.3793695200631374}. Best is trial 69 with value: 13.241581916809082.
[I 2026-06-09 14:11:45,243] Trial 70 finished with value: 13.261321067810059 and parameters: {'hidden_size': 128, 'lr': 0.0018970019022250468, 'batch_size': 16, 'weight_decay': 2.9831760068385556e-05, 'dropout': 0.18428727193991934}. Best is trial 69 with value: 13.241581916809082.
[I 2026-06-09 14:12:02,620] Trial 71 finished with value: 13.253369331359863 and parameters: {'hidden_size': 128, 'lr': 0.0024456640847128237, 'batch_size': 16, 'weight_decay': 2.095984889264985e-05, 'dropout': 0.3849580511625327}. Best is trial 69 with value: 13.241581916809082.
[I 2026-06-09 14:12:14,661] Trial 72 finished with value: 13.258837699890137 and parameters: {'hidden_size': 128, 'lr': 0.0030071576394992135, 'batch_size': 16, 'weight_decay': 1.6349243341900513e-05, 'dropout': 0.4079313941006018}. Best is trial 69 with value: 13.241581916809082.
[I 2026-06-09 14:12:26,690] Trial 73 finished with value: 13.25584888458252 and parameters: {'hidden_size': 128, 'lr': 0.004456750600038748, 'batch_size': 16, 'weight_decay': 4.2891538082835944e-05, 'dropout': 0.3612861480138245}. Best is trial 69 with value: 13.241581916809082.
[I 2026-06-09 14:12:43,948] Trial 74 finished with value: 13.258399963378906 and parameters: {'hidden_size': 128, 'lr': 0.0020087104427859875, 'batch_size': 16, 'weight_decay': 5.639684240716969e-06, 'dropout': 0.43629979124869034}. Best is trial 69 with value: 13.241581916809082.
[I 2026-06-09 14:12:56,566] Trial 75 finished with value: 13.256260871887207 and parameters: {'hidden_size': 64, 'lr': 0.0025093260129229475, 'batch_size': 64, 'weight_decay': 1.0086126915401528e-05, 'dropout': 0.3734573624272637}. Best is trial 69 with value: 13.241581916809082.
[I 2026-06-09 14:13:03,845] Trial 76 finished with value: 13.253681182861328 and parameters: {'hidden_size': 128, 'lr': 0.0017229381319371474, 'batch_size': 64, 'weight_decay': 3.551843989926884e-05, 'dropout': 0.24481762773081467}. Best is trial 69 with value: 13.241581916809082.
[I 2026-06-09 14:13:13,384] Trial 77 finished with value: 13.250236511230469 and parameters: {'hidden_size': 128, 'lr': 0.0030201369399005997, 'batch_size': 64, 'weight_decay': 6.738762556662751e-05, 'dropout': 0.22395471575599382}. Best is trial 69 with value: 13.241581916809082.
[I 2026-06-09 14:13:28,201] Trial 78 finished with value: 13.264213562011719 and parameters: {'hidden_size': 32, 'lr': 0.0013862947346608072, 'batch_size': 64, 'weight_decay': 2.293637595612556e-05, 'dropout': 0.3504127776985583}. Best is trial 69 with value: 13.241581916809082.
[I 2026-06-09 14:13:45,439] Trial 79 finished with value: 13.259174346923828 and parameters: {'hidden_size': 128, 'lr': 0.002276638735184678, 'batch_size': 16, 'weight_decay': 1.6677992398411088e-05, 'dropout': 0.2614914586605461}. Best is trial 69 with value: 13.241581916809082.
[I 2026-06-09 14:13:57,046] Trial 80 finished with value: 13.260687828063965 and parameters: {'hidden_size': 128, 'lr': 0.0011029821572214901, 'batch_size': 64, 'weight_decay': 1.139205334168415e-05, 'dropout': 0.38612358593224544}. Best is trial 69 with value: 13.241581916809082.
[I 2026-06-09 14:14:05,801] Trial 81 pruned.
[I 2026-06-09 14:14:15,967] Trial 82 finished with value: 13.246368408203125 and parameters: {'hidden_size': 128, 'lr': 0.0038705613263831868, 'batch_size': 64, 'weight_decay': 5.8176590798954795e-06, 'dropout': 0.2923940717635365}. Best is trial 69 with value: 13.241581916809082.
[I 2026-06-09 14:14:24,269] Trial 83 finished with value: 13.251116752624512 and parameters: {'hidden_size': 128, 'lr': 0.005031973748820616, 'batch_size': 64, 'weight_decay': 6.395206803080344e-06, 'dropout': 0.20313971894092725}. Best is trial 69 with value: 13.241581916809082.

Best Params for Small-cap: {'hidden_size': 128, 'lr': 0.0024073927504210404, 'batch_size': 16, 'weight_decay': 2.879599343783324e-05, 'dropout': 0.3793695200631374}

Small-cap - Total Test MAE: 1.9426 ± 0.1155

Group            MIB   Mid-cap  Small-cap
Target
EBITDA      1.872972  0.434066   2.098847
Net_Income  0.724902  1.663558   1.823405
ROA         0.760404  1.620463   1.905453
TOTAL       1.119426  1.239362   1.942568

In [22]:
# ============================================================
# TRAIN FINAL DEDICATED MODEL FOR EACH MARKET-CAP GROUP
# ============================================================

GROUP_PARAMS = {
    "MIB": {
        "hidden_size": 64,
        "lr": 0.0047639846588888755,
        "batch_size": 32,
        "weight_decay": 0.0004627785003174142,
        "dropout": 0.137398162298415
    },
    "Mid-cap": {
        "hidden_size": 64,
        "lr": 0.005426748767587874,
        "batch_size": 32,
        "weight_decay": 3.6520300079748134e-06,
        "dropout": 0.2908379909201838
    },
    "Small-cap": {
        "hidden_size": 128,
        "lr": 0.0024073927504210404,
        "batch_size": 16,
        "weight_decay": 2.879599343783324e-05,
        "dropout": 0.3793695200631374
    }
}

results = []

for group_name, tickers in ticker_groups.items():

    print("\n" + "=" * 60)
    print(group_name)
    print("=" * 60)

    params = GROUP_PARAMS[group_name]

    set_seed(42)

    group_df = improved_data_df[
        improved_data_df["company"].isin(tickers)
    ].copy()

    g_train, g_val, g_test = split_by_year(
        group_df,
        TRAIN_YEAR_CUTOFF,
        VALID_YEAR_CUTOFF
    )

    scaler = RobustScaler()

    train_windows = np.vstack([
        row[:, selected_indices]
        for row in g_train["window_data"]
    ])

    scaler.fit(train_windows)

    train_ds = ImprovedYoYDatasetMTL(
        extract_mtl_df(g_train),
        scaler,
        selected_indices
    )

    val_ds = ImprovedYoYDatasetMTL(
        extract_mtl_df(g_val),
        scaler,
        selected_indices
    )

    test_ds = ImprovedYoYDatasetMTL(
        extract_mtl_df(g_test),
        scaler,
        selected_indices
    )

    train_loader = DataLoader(
        train_ds,
        batch_size=params["batch_size"],
        shuffle=True,
        collate_fn=collate_fn_improved_mtl
    )

    val_loader = DataLoader(
        val_ds,
        batch_size=params["batch_size"],
        shuffle=False,
        collate_fn=collate_fn_improved_mtl
    )

    test_loader = DataLoader(
        test_ds,
        batch_size=params["batch_size"],
        shuffle=False,
        collate_fn=collate_fn_improved_mtl
    )

    model = ImprovedShallowLSTM(
        input_size=len(selected_indices),
        hidden_size=params["hidden_size"],
        num_targets=len(PREDICTION_TARGETS),
        dropout=params["dropout"]
    ).to(DEVICE)

    optimizer = torch.optim.Adam(
        model.parameters(),
        lr=params["lr"],
        weight_decay=params["weight_decay"]
    )

    model, _ = train_and_eval(
        model,
        train_loader,
        val_loader,
        optimizer,
        True,
        None,
        loss_type='l1'
    )

    print("\nTEST RESULTS")
    mae, rmse = evaluate_real_metrics(
        model,
        test_loader,
        DEVICE
    )

    n_samples = len(test_ds)

    results.append({
        "Group": group_name,
        "MAE": mae,
        "RMSE": rmse,
        "N": n_samples
    })

df_results = pd.DataFrame(results)

print("\n")
print("=" * 60)
print("FINAL RESULTS")
print("=" * 60)

print(df_results)

weighted_mae = (
    (df_results["MAE"] * df_results["N"]).sum()
    / df_results["N"].sum()
)

weighted_rmse = (
    (df_results["RMSE"] * df_results["N"]).sum()
    / df_results["N"].sum()
)

print("\nWeighted MAE:")
print(weighted_mae)

print("\nWeighted RMSE:")
print(weighted_rmse)

============================================================
MIB
============================================================

TEST RESULTS
Test MAE  (Real Scale): 1.1349
Test RMSE (Real Scale): 8.2930

============================================================
Mid-cap
============================================================

TEST RESULTS
Test MAE  (Real Scale): 1.2548
Test RMSE (Real Scale): 8.7773

============================================================
Small-cap
============================================================

TEST RESULTS
Test MAE  (Real Scale): 1.9577
Test RMSE (Real Scale): 8.6113


============================================================
FINAL RESULTS
============================================================
       Group       MAE      RMSE    N
0        MIB  1.134931  8.293011   87
1    Mid-cap  1.254799  8.777294  156
2  Small-cap  1.957686  8.611273  241

Weighted MAE:
1.5832434488722116

Weighted RMSE:
8.607575554493046